### ISSUE TITLE
Make the alignment process adaptive with respect to the "fitgeom"

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1003]
_Issue [HLA-527](https://jira.stsci.edu/browse/HLA-527) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

For practical purposes, each "fitgeom" supported by tweakwcs (shift, rshift, rscale, general) needs a minimum number of found sources to be considered a robust solution.  Implement an algorithm to adjust the requested "fitgeom" depending upon the number of GAIA sources found.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-527?focusedCommentId=523194#comment-523194):_

Git PR#&#x2060;1013 approved and merged 23 April 2021.

**Comment by stsci-hack** [comment]
Closed by #1013
