### ISSUE TITLE
MVM: Identify datasets for testing new alignment logic

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1004]
_Issue [HLA-528](https://jira.stsci.edu/browse/HLA-528) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The new alignment logic being developed under HLA-509, HLA-510 and HLA-511 (and HLA-527) will need to be carefully tested to insure that it not only runs without throwing an Exception, but that it successfully aligns the data.  This ticket will focus on identifying a small set of datasets that will exercise this new logic both for success and for handling error cases.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-528?focusedCommentId=521373#comment-521373):_

A test dataset has been identified to exercise the weights in alignment:  j94sb8010 (hst_10189_b8_acs_wfc_f850lp).  It only has 7 GAIA sources, but 47 Pan-STARRS sources and represents a complete SVM product (the only ASN in the visit).  HLA-533 has been updated with this test case information as well.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-528?focusedCommentId=521485#comment-521485):_

These datasets are part of the 1K SVM tests which were deemed not well aligned in one of the processing runs since October 2020.  While many of these issues may now be addressed, the datasets are good test candidates for evaluating the updated alignment algorithm.  The algorithm is essentially the same for SVM and MVM.  Please note the information will be fully fleshed out at a later time.

DateOfComment 

06 Oct 2020  12310  44  wfc3  uvis                   mis-alignment between filters

06 Oct 2020   8992  03  acs     wfc (j8cw03)   mis-alignment between exposures (all the same filter)

07 Oct 2020  13496  82  wfc3  ir                       few gaia sources, a priori wcs

08 Oct 2020 jbzoa3         acs                             a priori wcs, should at least be relative

08 Oct 2020 iczg72         wfc3  ir

03 Dec 2020 j8qy21         acs    hrc                   five filters

03 Dec 2020 10444  a1  acs  wfc

03 Nov 2020  jcau71                

04 Nov 2020 j8cw53

27 Oct 2020   ib6v13      wfc3  uvis

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-528?focusedCommentId=522862#comment-522862):_

With PR #&#x2060;1012 merged, I was able to successfully process 'ic8o82' and align to both GAIAeDR3 (default) and GSC242 (just for the test).  Se HLA-533 for discussion of results.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-528?focusedCommentId=522873#comment-522873):_

Another set of mis-aligned datasets from the 1k test:

idnm0n, idnm0u, idnm1h,  15238, ir, multi-filters - aligned on 1 image, rest in mosaic misaligned relative to first image

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-528?focusedCommentId=523278#comment-523278):_

After merging all PRs through #&#x2060;1013, 'jbzoa3' was able to be aligned successfully to GAIAeDR3 (20 matches) with apparent good alignment.

**Comment by stsci-hack** [comment]
Closed by #1013 and previous related PRs.
