### ISSUE TITLE
SVM: Investigate alignment issues for IB6V13 UVIS

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1021]
_Issue [HLA-542](https://jira.stsci.edu/browse/HLA-542) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The SVM visit ib6v13 contains both IR and UVIS data which successfully process with alignment.  However, examination of the UVIS "total" output image indicates the UVIS data is clearly not aligned properly.  Images y5 and y8 are mis-aligned to the other images, but they aligned to one another.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-542?focusedCommentId=527201#comment-527201):_

ib6v13y5, ib6v13y8, and remaining WFC3/UVIS observations:
* Standard pipeline processing resulted in alignment with WCSNAME='IDC_2731450pi-FIT_REL_GAIADR1'

ib6v13y0, ib6v13y1:
* Standard pipeline processing resulted in alignment with WCSNAME='IDC_2731450pi-FIT_REL_GAIADR2'
* This results in an offset of (104, -33)pixels in the common tangent plane with 'y5' and 'y8'
* Relative alignment parameters had max offset for 2D-histogram of 75 pixels, not large enough to correct this offset

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-542?focusedCommentId=527248#comment-527248):_

Expanding the `searchrad` parameter for the `match_relative_fit` mode of alignment from 75 or 100 to 125 allowed this dataset to be correctly aligned in a relative sense, then aligned to GAIA with WCSNAME = 'IDC_2731450pi-FIT_SVM_GAIAeDR3' for all drizzled products in this visit.

The new set of parameters were used to update [Drizzlepac PR #&#x2060;1028](https://github.com/spacetelescope/drizzlepac/pull/1028).

**Comment by stsci-hack** [comment]
Closed by #1028
