### ISSUE TITLE
updatewcs_with_shift() logic is broken and not longer works

### ISSUE THREAD

**Issue by npirzkal** [spacetelescope/drizzlepac#1022]
This function reads the name of the refimage from the comments but the new code ignores these line before trying to find out what the reference name is. It no longer works at all as the refimage name is now always None.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-545](https://jira.stsci.edu/browse/HLA-545)._

**Comment by mcara** [comment]
Could you, please elaborate and/or provide an example that illustrates a crash? What do you mean by

> ... as the refimage name is now always None

The value of `refimage` cannot be set by the caller to `None`. The code needs a valid reference image (WCS).

CC: @stsci-hack

**Comment by stsci-hack** [comment]
Solved with #1038.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-545?focusedCommentId=606108#comment-606108):_

Solved with [Drizzlepac PR #&#x2060;1038](https://github.com/spacetelescope/drizzlepac/pull/1038).
