### ISSUE TITLE
Investigate Astropy Modelling

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1024]
_Issue [HLA-548](https://jira.stsci.edu/browse/HLA-548) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Investigate and understand how to leverage the astropy modelling code for use in fitting coordinates for which we have proper motion values.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-548?focusedCommentId=525647#comment-525647):_

Attended a lecture and then team-burgundy continued the discussion and worked through a modeling notebook to highlight the functionality.  I have reviewed the notebook again and read more on the models and fitters.  While I have discovered a couple of items that I would like to discuss further, I think starting to work with the models in applying them to the problem at hand will reveal the items which need to be explained further, while also moving towards the actual implementation goal.

**Comment by mcara** [comment]
Take a look at https://github.com/spacetelescope/tweakwcs/pull/139 and the unit test: it illustrates typical use.
