### ISSUE TITLE
import drizzlepac causes package conflict with photutils modules

### ISSUE THREAD

**Issue by sosey** [spacetelescope/drizzlepac#1025]
with photutils 1.1 installed, and drizzlepac 3.1.8 I get the following error:

> lib/python3.7/site-packages/drizzlepac/haputils/align_utils.py in <module>
>      46 
>      47 NoDetectionsWarning = photutils.findstars.NoDetectionsWarning if \
> ---> 48                         hasattr(photutils.findstars, 'NoDetectionsWarning') else \
>      49                         photutils.utils.NoDetectionsWarning
>      50 
> ~/opt/miniconda3/envs/hstaxe-demo/lib/python3.7/site-packages/photutils/__init__.py in __getattr__(attr)
>      50         return obj
>      51     raise AttributeError('module {!r} has no attribute {!r}'
> ---> 52                          .format(__name__, attr))
>      53 
> 

I have to go down to photutils 1.0.2 to import drizzlepac without error...but I think the error is in drizzlepac specification of the photutils modules and NoDetectionsWarning, not necessarily a change in photutils.

@larrybradley mentions that `from photutils.detection import findstars` should work for all versions of photutils and that `photutils.utils.exceptions.NoDetectionsWarning` should be used.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-549](https://jira.stsci.edu/browse/HLA-549)._

**Comment by larrybradley** [comment]
I fixed the `photutils` imports in https://github.com/spacetelescope/drizzlepac/pull/988

**Comment by stsci-hack** [comment]
The photutils dependency in 'setup.py' was also modified in #983 to avoid using photutils 1.1.0 for now.  We also have work planned for this summer to update Drizzlepac to support Python 3.8 and newer (#968) at which time we will also implement PR #995 to add support for photutils 1.1.0 (as tracked on HLA-522 on Jira).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-549?focusedCommentId=606113#comment-606113):_

Resolved with [Drizzlepac PR#&#x2060;995](https://github.com/spacetelescope/drizzlepac/pull/995), along with other PRs mentioned in [Drizzlepac issue #&#x2060;1025](https://github.com/spacetelescope/drizzlepac/issues/1025).
