### ISSUE TITLE
MVM: Add support for compressed masks to SkyCell class

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1040]
_Issue [HLA-568](https://jira.stsci.edu/browse/HLA-568) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Use of python-blosc would allow the SkyCell code to compress/decompress the mask arrays and save enormous amounts of memory.  New methods should be added to the SkyCell class for interacting with the masks where the methods would compress/decompress automatically and the user would only ever work with native numpy objects.  

For example, a method to add a mask to the total_mask would take the native numpy ndarray for the mask to be added as input, then uncompress the total_mask, add the new mask, then compress the updated total mask again.

Another method would compress the native numpy arrays for use in saving as an attribute.  

This should allow the SkyCell class to support much larger numbers of input exposures and help resolve HLA-415.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-568?focusedCommentId=531925#comment-531925):_

The use of compression, even with python-blosc, did not result in enough of a benefit to justify the amount of changes needed to the code that would make the code more difficult to maintain.  In the process of testing this, a method to eliminate the memory use related to each input exposure was identified and implemented in [Drizzlepac PR #&#x2060;1049| <https://github.com/spacetelescope/drizzlepac/pull/1049].>

The intent of this ticket will be met by this PR instead of using compression as originally expected for this ticket.

**Comment by stsci-hack** [comment]
Closed by #1049.
