### ISSUE TITLE
MVM: Modify make_poller_files.py

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1050]
_Issue [HLA-572](https://jira.stsci.edu/browse/HLA-572) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Once I understood how to use make_poller_files.py (generate_poller_file) from within a python session, it works very well.  However, using it in this way I found:
 # if the skycell name is not provided, an improper poller file is produced (i.e., no exception is thrown).
 # the FLC files were not used even though there were both FLT and FLC files in the directory specified via DATA_PATH.

It seems as though if I had used the utility on the command line, item (1) would have been caught.

**Comment by stsci-hack** [comment]
Closed by #1138
