### ISSUE TITLE
SVM/MVM: Remove the return value from generate_metawcs() in the product.py module

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1053]
_Issue [HLA-578](https://jira.stsci.edu/browse/HLA-578) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The generate_metawcs method is defined in the HAPProduct (for SVM) and the SkyCellProduct (for MVM) which inherits from HAPProduct but overrides the functionality.  Both methods should not return a value, but rather they should set a class attribute.  This should be done carefully to ensure there are no repercussions.

**Comment by stsci-hack** [comment]
Attributes are saved by the latest versions of these methods, so this issue can be closed.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-578?focusedCommentId=566149#comment-566149):_

The SkyCellProduct version of the 'generate_metawcs' method returns a value specific to the SkyCell itself, which is NOT the full metawcs that gets saved in the 'meta_wcs' attribute as defined by the base class.  Having this method return the most appropriate value of the meta_wcs prevents confusion on the part of any calling routines, while attributes save all computed values as well for later use (as needed).
