### ISSUE TITLE
MVM: Recast the manifest filename to be predictable

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1062]
_Issue [HLA-583](https://jira.stsci.edu/browse/HLA-583) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

At this time the MVM manifest file is too specific, depending upon aspects of the first SkyCellProduct in the "total object list" (i.e., instrument, detector, filter).  As such the manifest file name is not predictable externally, and the operations software needs to be able to generate the MVM manifest file name independently.  Fix how the MVM filename is generated and update the comments in product.py (and also some comments in hapmultisequencer.py).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-583?focusedCommentId=538226#comment-538226):_

From discussion in team-violet meeting on 12 July 2021 ...

Name the MVM manifest file: hst_skycell-p<PPPP>x<XX>y<YY>_manifest.txt

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-583?focusedCommentId=538704#comment-538704):_

Redefined as a blocker due to the impact to the pipeline workflow; namely, without this, the pipeline does not work.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-583?focusedCommentId=539007#comment-539007):_

The manifest filename has been modified to adhere to the described format:

hst_skycell-p<PPPP>x<XX>y<YY>_manifest.txt

The update is Git PR#&#x2060;1070.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-583?focusedCommentId=539027#comment-539027):_

This code has been approved and merged.

**Comment by stsci-hack** [comment]
Closed by #1070
