### ISSUE TITLE
MVM: Develop custom MVM interface to astrocut 

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1084]
_Issue [HLA-605](https://jira.stsci.edu/browse/HLA-605) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The investigations under HLA-604 will identify how to use astrocut to work with MVM products.  A custom interface in Drizzlepac for performing specific tasks on MVM products would (potentially) simplify the generation of custom products derived from the MVM products.  

Specifically, a stand-alone task in Drizzlepac should be developed that allows users to generate a cutout from a single SkyCell in one call rather than multiple calls to astropy and astrocut.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-605?focusedCommentId=545343#comment-545343):_

This code is out for official review PR#&#x2060;1104.

**Comment by stsci-hack** [comment]
Closed by #1104
