### ISSUE TITLE
TST: Fix failed tests on pandokia

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#109]
Failed test logs: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=10365

```
UnboundLocalError Message: local variable 'errorobj' referenced before assignment 
```

**Comment by mcara** [comment]
PRs related to this issue: https://github.com/spacetelescope/drizzlepac/pull/107, https://github.com/spacetelescope/drizzlepac/pull/108, and https://github.com/spacetelescope/drizzlepac/pull/110

OKifying remaining tests now

**Comment by mcara** [comment]
@pllim What is the status?

**Comment by pllim** [comment]
Still failing, if you look at yesterday's log. But did you commit in time for yesterday's run to pick it up?

**Comment by mcara** [comment]
@pllim What if you look at today's log?

**Comment by mcara** [comment]
There was nothing to commit - just okify

**Comment by pllim** [comment]
Then, did you okify before or after 10:30 AM yesterday?

**Comment by pllim** [comment]
Today's log looks good. Thanks!
