### ISSUE TITLE
SVM: No segments found for total data product (TDP), only that TDP should cease processing

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1090]
_Issue [HLA-610](https://jira.stsci.edu/browse/HLA-610) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

SVM Results (29 July 2021)

1) results_2021-07-28/ib2t06/HAP_ib2t06.out:Output status = 1
No segments found in Total Detection Product, hst_11603_06_wfc3_uvis_total_ib2t06_drc.fits.

There are 24 images in this visit: 8 F814W UVIS, 8 F110W IR, and 8 F160W IR.

The UVIS total detection image has one small source in the center and a
smear in the upper-right corner. The IR total detection image has a 
number sources. If I align the two total detection images in ds9
according to WCS, I can see there really are two sources in the UVIS.

PROBLEM: Because the segmentation algorithm decided it could not find
any segments in the UVIS, the algorithm caused the entire processing to
end. ***This is a bug as only the products associated with the UVIS***
**_should have ceased processing._**

Having said this, if no segments can be identified and the processing must
cease, this is not an error as this code is doing what it is intended and
the code should pack up nicely.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-610?focusedCommentId=547605#comment-547605):_

Git PR#&#x2060;1115 reviewed and merged.

**Comment by stsci-hack** [comment]
Closed by #1115
