### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#1099]
CC: @stsci-hack `setup.py` lists dependencies that are not used by the `drizzlepac`, such as `tables` and `PyYAML` (and maybe other packages) - see https://github.com/spacetelescope/drizzlepac/blob/67232d48b7736ddba64dbe9b4e4ab0c881acdfc5/setup.py#L106-L107

These should be removed.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-615](https://jira.stsci.edu/browse/HLA-615)._
