### ISSUE TITLE
MVM: Improve the hapcut_utils.py to work on MVM exposure level images

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1105]
_Issue [HLA-616](https://jira.stsci.edu/browse/HLA-616) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Improve the hapcut utilities so they work on MVM exposure level drizzled images in addition to filter-level images.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-616?focusedCommentId=547814#comment-547814):_

This ticket is WIP though the code has been put out as Git PR#&#x2060;1119.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-616?focusedCommentId=549862#comment-549862):_

Reworked the mvm_combine function to use dictionaries to keep track of the filter-level and exposure level files. The img_combiner parameter is currently disabled.

Added try/except blocks and additional comments. Make sure variables are initialized as necessary.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-616?focusedCommentId=550364#comment-550364):_

Code approved and merged.

**Comment by stsci-hack** [comment]
Closed by #1119
