### ISSUE TITLE
MVM: Update API to allow any poller file name

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1113]
_Issue [HLA-622](https://jira.stsci.edu/browse/HLA-622) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The current interface for 'hapsequencer' and 'hapmultisequencer' expects the input poller file name to end with '.out', or else it throws a vague Exception.  This should be changed to allow a file with any extension to be used as input instead.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-622?focusedCommentId=546924#comment-546924):_

[Drizzlepac PR #&#x2060;1112](https://github.com/spacetelescope/drizzlepac/pull/1112) included the changes needed to resolve this ticket.

**Comment by stsci-hack** [comment]
Closed by #1112
