### ISSUE TITLE
SVM: Revise logic for segmentation catalog generation

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1120]
_Issue [HLA-624](https://jira.stsci.edu/browse/HLA-624) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The logic for determining whether or not to produce a segmentation catalog needs to be revised to account for fields which are dominated by extended sources, such as 'j92c01' (10265_01).  

The log for 'j92c01' reported:

> 2021251071811 INFO src=drizzlepac.haputils.catalog_utils- Analyzing segmentation image.
> 2021251071811 INFO src=drizzlepac.haputils.catalog_utils- Number of sources from segmentation map: 44630
> 2021251071812 INFO src=drizzlepac.haputils.catalog_utils- Biggest_source: 0.010628
> 2021251071812 INFO src=drizzlepac.haputils.catalog_utils- Source_fraction: 0.097759
> 2021251071812 WARNING src=drizzlepac.haputils.catalog_utils- 
> 2021251071812 WARNING src=drizzlepac.haputils.catalog_utils- The Round 2 of segmentation images still contain big sources/islands or a
> large source fraction of segments.
> 2021251071812 WARNING src=drizzlepac.haputils.catalog_utils- The segmentation algorithm is unable to continue and no segmentation catalog will be produced.

This is one case, however, where it would have been fine to continue with creation of the segmentation catalog.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-624?focusedCommentId=550433#comment-550433):_

The changes in the logic for generating the segmentation catalogs included in , [Drizzlepac PR #&#x2060;1122](https://github.com/spacetelescope/drizzlepac/pull/1122), [Drizzlepac PR #&#x2060;1131](https://github.com/spacetelescope/drizzlepac/pull/1131), and [Drizzlepac PR #&#x2060;1129](https://github.com/spacetelescope/drizzlepac/pull/1129) have resolved this problem.  Deblending now only occurs for 339 out of 15923 segments for `j92c01`, resulting in the generation of a valid segment catalog for this dataset.

**Comment by stsci-hack** [comment]
Closed by #1122, #1131 and #1129 .
