### ISSUE TITLE
MVM: Analyze MVM images to identify/tag data which should not be processed

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1130]
_Issue [HLA-628](https://jira.stsci.edu/browse/HLA-628) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Modify the cell_utils functionality to accommodate evaluation/analysis of MVM input files such that calibration or other types of files which contain data that should not be processed as "skycell" images are identified for alternative processing.  In contrast to returning the skycell designation for a given input image, the get_sky_cells function could return a special designation to be used as an indicator the data should not be processed in the nominal manner.  This indicator should be as granular (e.g., include instrument and detector?) as necessary to fulfill the needs of operations.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-628?focusedCommentId=550024#comment-550024):_

After some discussion with team-violet during our backlog grooming, it was decided not to modify cell_utils.py.  Rather we should create a standalone function akin to analyze.py (or re-use analyze.py) which can be invoked on a string (e.g., filename) and only returns a bool indicating whether or not the file should be processed under MVM conditions.  Because only a bool is being returned, the function should make sure to generate clear log messages as to the reason the file is being rejected for processing.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-628?focusedCommentId=550219#comment-550219):_

The new function, mvm_analyze_wrapper, in the analyze.py module is out for code review.  Rob and Lisa indicated the full filename would be provided as the input to the new function.  Invocation of this routine by operations would be:

from drizzlepac.haputils import analyze
viability = analyze.mvm_analyze_wrapper(input_filename)
input_filename is a string
viability is a boolean (True: use for MVM, False: do NOT use for MVM)

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-628?focusedCommentId=550363#comment-550363):_

Code approved and merged.

**Comment by stsci-hack** [comment]
Closed by #1132
