### ISSUE TITLE
Master is broken due to imports of debug modules

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#1223]
When attempting to import `drizzlepac` from the `master`, I get this error:

```
E   ModuleNotFoundError: No module named 'guppy'
```

This is due to [this import.](https://github.com/spacetelescope/drizzlepac/blob/d97700f5aa4c8742085989bdf10f432e71f3f01d/drizzlepac/haputils/cell_utils.py#L6)

Due to this all tests in https://github.com/spacetelescope/drizzlepac/pull/1222 Pr (and probably all other open PRs) are failing.

CC: @stsci-hack

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-682](https://jira.stsci.edu/browse/HLA-682)._

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-682?focusedCommentId=606116#comment-606116):_

Resolved with [Drizzlepac PR #&#x2060;1224](https://github.com/spacetelescope/drizzlepac/pull/1224).
