### ISSUE TITLE
Unit tests for the drizzlepac are failing for a long time

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1225]
_Issue [HLA-683](https://jira.stsci.edu/browse/HLA-683) was created on JIRA by [Mihai Cara](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mcara):_

Unit tests for the drizzlepac are failing consistently for a long time. This prevents testing of new PRs. Also, no PR should be merged if tests are not passing (either fix the PR or fix the tests).
 
=========================== short test summary info ============================ 
FAILED tests/hap/test_pipeline.py::TestSingleton::test_astrometric_singleton[iaaua1n4q] 
FAILED tests/hap/test_pipeline.py::TestSingleton::test_astrometric_singleton[iacs01t4q] 
FAILED tests/hap/test_svm_ibqk07.py::test_svm_wcs_ir - AssertionError: WCSNAM... 
FAILED tests/hap/test_svm_ibqk07.py::test_svm_point_cat_numsources - Assertio... 
FAILED tests/hap/test_svm_ibyt50.py::test_svm_wcs_ir - AssertionError: WCSNAM... 
FAILED tests/hap/test_svm_ibyt50.py::test_svm_segment_cat_numsources - Assert... 
FAILED tests/hap/test_svm_j97e06.py::test_svm_wcs - AssertionError: WCSNAMES ... 
FAILED tests/hap/test_svm_wfc3ir.py::test_svm_wcs - AssertionError: WCSNAME i... 
FAILED tests/hap/test_svm_wfc3ir.py::test_svm_point_cats - AssertionError: Po... 
= 9 failed, 29 passed, 117 skipped, 2 xfailed, 577 warnings in 1692.29s (0:28:12) = 
##[error]Bash exited with code '1'.

**Comment by stsci-hack** [comment]
All tests are now passing, while 0-weight pixel issue will be resolved with #1222.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-683?focusedCommentId=606390#comment-606390):_

All tests pass under 3.8.
