### ISSUE TITLE
TST: acs_tweak/test.py failed in pandokia

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#123]
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=142506281

```
stsci.tools.logutil.exc: ERROR: An unhandled exception ocurred:
Traceback (most recent call last):
  File "/srv/iraf/bldtmp/p8Eo/p/envs/dev/lib/python3.5/site-packages/drizzlepac/util.py", line 218, in wrapper
    func(*args, **kwargs)
  File "/srv/iraf/bldtmp/p8Eo/p/envs/dev/lib/python3.5/site-packages/drizzlepac/tweakreg.py", line 103, in run
    __version__,__version_date__,util._ptime()[0]))
NameError: name '__version_date__' is not defined
--------------------- >> end captured logging << ---------------------
Trigger: if errorobj:
```

**Comment by mcara** [comment]
CC: @jhunkeler

**Comment by jhunkeler** [comment]
I fixed the the other day in #119. Today's `acs_tweak` test is passing 😄

**Comment by mcara** [comment]
In the future, it would be great to check *current* test status (as opposite to yesterday's status reported through e-mail) before opening an issue about failing tests.

In fact, do we need to open issues about failing tests? Aren't failing test reports enough of notification?

**Comment by pllim** [comment]
Today's status wasn't available when I opened this. What would be *really* nice is move those tests back here, so you know whether it fails or not when the PR is *opened*, not merged. (But we'll get there.) :wink:

**Comment by pllim** [comment]
And thank you for the quick response, everyone!
