### ISSUE TITLE
Update Drizzlepac to support Python 3.10

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1239]
_Issue [HLA-695](https://jira.stsci.edu/browse/HLA-695) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

We need to update Drizzlepac to work with Python 3.10 as soon as all dependent third-party packages required by Drizzlepac work under Python 3.10.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-695?focusedCommentId=581329#comment-581329):_

Part of this update could also include resolving HLA-754.

**Comment by stsci-hack** [comment]
Closed by #1420

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-695?focusedCommentId=600196#comment-600196):_

[Fitsblender PR #&#x2060;35](https://github.com/spacetelescope/fitsblender/pull/35) was filed to address HLA-754 as a dependency which needed to be addressed for Drizzlepac to work under Python 3.10.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-695?focusedCommentId=600200#comment-600200):_

[Drizzlepac PR #&#x2060;1420](https://github.com/spacetelescope/drizzlepac/pull/1420) was submitted to turn on Python 3.10 Azure tests for PRs and builds.  An initial inspection of the code and dependent packages did not uncover any other changes that should be needed for Python 3.10 support.  Any test failures under PR #&#x2060;1420 will indicate what still needs to be done to finish adding Python 3.10 support.
