### ISSUE TITLE
Clean up the HSTCAL repo

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1240]
_Issue [HLA-697](https://jira.stsci.edu/browse/HLA-697) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

There are many issues residing in the HSTCAL repository.  Some of the issues can be closed as they have been done.  However, many others should be prioritized or closed because they have been superseded or there is a technical reason they cannot or should not be done.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-697?focusedCommentId=566216#comment-566216):_

Reviewed nearly all of the issues, and I was able to close ˜15 as they were: done or superseded by other updates.  A number of tickets were marked a low priority in that they are not critical to the continued functionality of the pipeline for operations.  There are a number of tickets of medium priority which should be addressed.

Nadia indicated this cleanup is sufficient for now.

**Comment by nden** [comment]
wrong repo
