### ISSUE TITLE
drizzlepac master is broken

### ISSUE THREAD

**Issue by nden** [spacetelescope/drizzlepac#1270]
#1256  broke drizzlepac (btw, the tests were failing on it).
The reason is there's no module called `drizzlepac.version.py` so an import
````
from drizzlepac.version import __version__
```
does not work. Instead the correct import is

```
from drizzlepac import __version__
```
or if you want to use relative imports
```
from . import __version__
```
This is a critical one as it blocks other work.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-719](https://jira.stsci.edu/browse/HLA-719)._

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-719?focusedCommentId=606154#comment-606154):_

Resolved with [Drizzlepac PR #&#x2060;1271](https://github.com/spacetelescope/drizzlepac/pull/1271).
