### ISSUE TITLE
Support Astropy 5.0

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1275]
_Issue [HLA-721](https://jira.stsci.edu/browse/HLA-721) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The Drizzlepac package needs to be updated to support astropy 5 in order to enable public release of Drizzlepac to the community using SPB's conda-forge-based YML.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-721?focusedCommentId=572905#comment-572905):_

Astropy 5.0 support was added through [Drizzlepac PR #&#x2060;1280](https://github.com/spacetelescope/drizzlepac/pull/1280).  

The use of astropy 5.0.1 was used to process data from visit 'iacs01' and the only differences reported by fitsdiff (aside from dates/times) was the PYWCSVER keyword for the astropy version with no pixel differences.  In addition, the 'hap' pytest tests were run using astropy 5.0 and there were NO failures. 

 

> (rthst38) bash-4.2$ pytest -n 4 -s --basetemp=/internal/1/data/pytest-hst >& astropy5_pytest.log
> (rthst38) bash-4.2$ tail astropy5_pytest.log
>  /user/hack/dev/release/stsci_python/pypi/drizzlepac/git/drizzlepac/drizzlepac/haputils/cell_utils.py:593: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
>  self.xy_corners = np.array(ordered_xy)
> 
> tests/hap/test_svm_je281u.py::test_svm_manifest_name
> tests/hap/test_svm_je281u.py::test_svm_cat_sources
>  /user/hack/dev/release/stsci_python/pypi/drizzlepac/git/drizzlepac/drizzlepac/haputils/cell_utils.py:594: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
>  self.corners = np.array(sky_corners)
> 
> -- Docs: <https://docs.pytest.org/en/stable/warnings.html>
> ========== 35 passed, 78 skipped, 2832 warnings in 1307.46s (0:21:47) ==========

**Comment by stsci-hack** [comment]
Closed by #1280
