### ISSUE TITLE
Protect from acting on NoneType objects

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1276]
_Issue [HLA-722](https://jira.stsci.edu/browse/HLA-722) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

In align.py at line
```java
total_num_sources += len(table[chipnum])```
(nominally line 375), it is possible for *table[chipnum]* to have no length as all the sources are in the other chip.  I will note the table has already been checked to ensure it is not None. This line needs protection.  The issue was found using dataset IDFQ06010.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-722?focusedCommentId=572699#comment-572699):_

Fix is out at Git Pr#&#x2060;1278.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-722?focusedCommentId=573100#comment-573100):_

This ticket was reviewed, approved, and merged.

**Comment by nden** [comment]
Jira ticket resolved. Closing

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-722?focusedCommentId=573100#comment-573100):_

This ticket was reviewed, approved, and merged.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-722?focusedCommentId=572699#comment-572699):_

Fix is out at Git Pr#&#x2060;1278.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-722?focusedCommentId=573100#comment-573100):_

This ticket was reviewed, approved, and merged.
