### ISSUE TITLE
How to control logging level in drizzlepac?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#128]
This came up in spacetelescope/acstools#54 . As reported by @mcara, using `astrodrizzle.log.setLevel(logging.ERROR)` does not change the default logging behavior. Let's say I have no interest in INFO or WARNING and only want to see ERROR. How do I do that in this package?

**Comment by mcara** [comment]
There is no way to control debugging level in `astrodrizzle` or `tweakreg` beyond `DEBUG/INFO` levels through the `verbose` parameter. See https://github.com/spacetelescope/drizzlepac/blob/f748cab8a4fc0582b231b6af4f81bc700768c0c4/drizzlepac/util.py#L134 Once I'll figure out #146 I will probably know how to implement a more refined control over logging levels.

**Comment by pllim** [comment]
Thanks for looking into this! And what a great milestone! :smile:

**Comment by stsci-hack** [comment]
Numerous PRs have been worked to enable more control over logging and to get the logging to report more reliably.
