### ISSUE TITLE
Generate the release candidate for HSTDP-2022.1.0 (MVMBETA)

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1281]
_Issue [HLA-723](https://jira.stsci.edu/browse/HLA-723) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

1) Tag HSTCAL to include the new ACSREJ updates

2) Tag Drizzlepac

3) Check for any other package updates

4) Check there is no change to use of Python 3.8

5) Check with Brendan

6) Submit build request

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-723?focusedCommentId=573226#comment-573226):_

1) *Done:* HSTCAL tagged as 2.7.4rc1.

5) *Done:* While there should be no conflicts, Brendan asked we wait until the Docker image for CALDP_20220214 is out.  S.Hahm is working on this.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-723?focusedCommentId=573455#comment-573455):_

3) *Done:* Check for any other package updates ==> The latest *fitsblender* package will be deployed to PyPi to be picked up by the build. 

4) *Done:* Check there is no change to use of Python 3.8 ==> continue to use Python 3.8.

5) *Done:* Check with Brendan. Waited until the docker image was deployed at Brendan's request.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-723?focusedCommentId=573610#comment-573610):_

2) **Done**: Drizzlepac has been tagged as drizzlepac@3.4.1rc0.

Build request submitted at 5:22 pm.

Codename: mvmbeta

Python 3.8

hstcal@2.7.4rc1
drizzlepac@3.4.1rc0
calcos@3.4.0
stwcs@1.7.2
tweakwcs@0.7.3
stsci.image@2.3.5
stsci.tools@4.0.1

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-723?focusedCommentId=573663#comment-573663):_

Processing ran fine, but PyTests failed. 
 * Three HSTCAL tests failed due to the ACSREJ updates, so this is just a matter of creating the new files.
 * Many DRIZZLEPAC tests failed even though the PR tests passed, except in two cases of documentation.  Will need to run the tests, and put truth files on Artifactory.

**Comment by nden** [comment]
Jira ticket resolved. Closing

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-723?focusedCommentId=573226#comment-573226):_

1) *Done:* HSTCAL tagged as 2.7.4rc1.

5) *Done:* While there should be no conflicts, Brendan asked we wait until the Docker image for CALDP_20220214 is out.  S.Hahm is working on this.  The Docker image is now available.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-723?focusedCommentId=573663#comment-573663):_

Processing ran fine, but PyTests failed. 
 * Three HSTCAL tests failed due to the ACSREJ updates, so this is just a matter of creating the new files.
 * Many DRIZZLEPAC tests failed even though the PR tests passed, except in two cases of documentation.  Will need to run the tests, and put truth files on Artifactory.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-723?focusedCommentId=573226#comment-573226):_

1) *Done:* HSTCAL tagged as 2.7.4rc1.

5) *Done:* While there should be no conflicts, Brendan asked we wait until the Docker image for CALDP_20220214 is out.  S.Hahm is working on this.  The Docker image is now available.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-723?focusedCommentId=573455#comment-573455):_

3) *Done:* Check for any other package updates ==> The latest *fitsblender* package has been deployed to PyPi to be picked up by the build.

4) *Done:* Check there is no change to use of Python 3.8 ==> continue to use Python 3.8.

5) *Done:* Check with Brendan. Waited until the docker image was deployed at Brendan's request.
