### ISSUE TITLE
Infinite magnitudes in catalogs for WFC3 FQ filters

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1284]
_Issue [HLA-724](https://jira.stsci.edu/browse/HLA-724) was created on JIRA by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw):_

The WFC3 ecsv catalogs using "FQ" filters have magnitudes that are effectively set to infinity.  Probably this is the result of missing calibration/throughput data for those filters.  An example is `hst_13089_09_wfc3_uvis_fq508n_ic5s09_segment-cat.ecsv`, which is a catalog that has 3 sources.  Extracting just the mag and flux columns, here are the columns for one of the sources:

` ID MagAp1 FluxAp1 MagAp2 FluxAp2 MagSegment FluxSegment`
` 3 1.7976931348623157e+308 2804.115982312668 1.7976931348623157e+308 6814.013499035062 3.4028235e+38 7596.1304`

The flux values look OK, but the magnitude values are obviously bad.
  
 The PHOTFLAM keyword value in the header of that image is zero, and the PHOTCORR step is turned off:

`PHOTCORR= 'OMIT ' / populate photometric header keywords`
` PHOTFLAM= 0.0     / Inverse sensitivity, ergs/cm2/A/e-`

When we encounter headers like this, I think we should just skip making catalogs for that filter.  Certainly we should avoid taking logs of zero, which I expect is the source of the effectively infinite values for the magnitudes.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573797#comment-573797):_

[Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw)

Just to clarify, do you want the entire catalog to NOT be produced, or do you just want the MagAp[1 | 2] and MageErrAp[1 | 2] to be set to -9999.0?

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573824#comment-573824):_

Hmm, so your answer is that we should produce a catalog with -9999 magnitudes, correct?  I think that is OK.  Either approach could be confusing to users, but this way we do meet your Prime Directive to produce a catalog.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573915#comment-573915):_

[Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw)

Yes, the catalog will be produced where the magnitude, magnitude error, and concentration index are all -9999.0.  As for the Prime Directive...we do try to adhere, but some Captains violated it all the time.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573916#comment-573916):_

Code is out as Git PR#&#x2060;1295.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573950#comment-573950):_

Make it so. (y)

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=574070#comment-574070):_

It has been done.

**Comment by nden** [comment]
Jira ticket resolved. Closing

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573797#comment-573797):_

[Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw)

Just to clarify, do you want the entire catalog to NOT be produced, or do you just want the MagAp[1 | 2] and MageErrAp[1 | 2] to be set to -9999.0?

I should note that we decided to check the value of photflam as the discriminant just in case this value is zero for any reason.  You are correct in that log(0.0) is done.

I think not creating the catalog may be confusing to folks.  I would suggest keeping the catalog and setting the values to -9999.0 (my opinion).

One more time (and this time with feeling), I am reminded we have the requirement to produce a catalog, even if it were empty.  So I believe I have answered my own question.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573916#comment-573916):_

Code is out as Git PR#&#x2060;1295.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573950#comment-573950):_

Make it so. (y)

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573797#comment-573797):_

[Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw)

Just to clarify, do you want the entire catalog to NOT be produced, or do you just want the MagAp[1 | 2] and MageErrAp[1 | 2] to be set to -9999.0?

I should note that we decided to check the value of photflam as the discriminant just in case this value is zero for any reason.  You are correct in that log(0.0) is done.

I think not creating the catalog may be confusing to folks.  I would suggest keeping the catalog and setting the values to -9999.0 (my opinion).

One more time (and this time with feeling), I am reminded we have the requirement to produce a catalog, even if it were empty.  So I believe I have answered my own question.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573824#comment-573824):_

Hmm, so your answer is that we should produce a catalog with -9999 magnitudes, correct?  I think that is OK.  Either approach could be confusing to users, but this way we do meet your Prime Directive to produce a catalog.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573915#comment-573915):_

[Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw)

Yes, the catalog will be produced where the magnitude, magnitude error, and concentration index are all -9999.0.  As for the Prime Directive...we do try to adhere, but some Captains violated it all the time.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=573950#comment-573950):_

Make it so. (y)

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-724?focusedCommentId=574070#comment-574070):_

It has been done.
