### ISSUE TITLE
readthedocs pointing to outdated documentation

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#129]
@pllim @jhunkeler Why does the readthedocs link point to an outdated documentation?

http://drizzlepac.readthedocs.io/en/deployment/

![screen shot 2018-05-01 at 12 09 43 pm](https://user-images.githubusercontent.com/5985250/39481165-80d43bbe-4d38-11e8-8684-20fe6e68e15f.png)

**Comment by pllim** [comment]
Why are you looking at "deployment"? Why is that the default? Where is "latest"? Who set this up? That sounds like an outdated branch build. Someone with admin access to RTD of this package need to fix this. There is nothing I can do.

**Comment by mcara** [comment]
CC: @nden @stsci-hack - I believe you have administrative rights.

**Comment by stsci-hack** [comment]
Unfortunately, readthedocs does not want to build the docs for the more recent versions, so they have been disabled.  The logs only give very cursory reasons for the failures.  For both the 'latest' and 'stable' versions, it simply can not successfully compile the C code (coordinate transformation and image resampling code not compiled) under Python 2.7.  Should anyone have any thoughts, then we can see about getting this to work again.

**Comment by mcara** [comment]
submit a ticket to help desk?

**Comment by sosey** [comment]
It's a real error that I get locally as well when I try and build.  I think the problem might be circular imports with ablot + cdriz

**Comment by sosey** [comment]
experiment in https://github.com/spacetelescope/drizzlepac/pull/130

**Comment by mcara** [comment]
I am not able to reproduce the `import` error **UNLESS** I start the interpreter in the package's directory in which case I get *exactly the same error* as reported by RTD's build.

**Comment by sosey** [comment]
It should be reproducible if you go into `doc/` and type `make html` as well.

**Comment by sosey** [comment]
true.  It shouldn't matter if I'm using `install` or `develop` though for making the docs, 

Go back and remove these lines from the `doc/source/conf.py` file in the `doc/` directory, I think they are messing with the import references, this should fix it for both:

>-sys.path.insert(0, os.path.abspath('..//'))
>-sys.path.insert(0, os.path.abspath('../../src/'))
>+# sys.path.insert(0, os.path.abspath('../'))
>+# sys.path.insert(0, os.path.abspath('../../src/'))

You could change the `../../src/` to `../../drizzlepac/`, but having just the one reference to the package main directory should be okay.

**Comment by mcara** [comment]
@sosey Thanks! I was already looking into `config.py` and exactly at the same lines. Currently testing several options...

**Comment by sosey** [comment]
did you try it?

**Comment by mcara** [comment]
yes

**Comment by mcara** [comment]
Fixed via https://github.com/spacetelescope/drizzlepac/pull/142
