### ISSUE TITLE
Add WHT statistics keywords to SVM and MVM products

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1301]
_Issue [HLA-726](https://jira.stsci.edu/browse/HLA-726) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Keywords with statistics from the WHT extension of the drizzled products which give the total exposure time are needed. Using similar naming conventions to the SCI extension, the new keywords would be **MEANWHT** and *MEDWHT.* 

For this dataset, the values would be ~2400 for an output scale of 0.12"/pix and ~266 for an output scale of 0.04"/pix. It would be great to have these for SVMs as well as MVMs.

See HLA-687 for background.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=579114#comment-579114):_

Code was reviewed as Git PR#&#x2060;1324 and merged.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587028#comment-587028):_

[Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena)   For SVM datasets processed April 8, 2022, e.g.

/ifs/archive/ops/hst/public/jacs/hst_11515_01/17:31 hst_11515_01_acs_wfc_f814w_jacs01_drc.fits

The definition of MEANWHT and MEDWHT is identical to MEANEXPT and MEDEXPT.   
```java
MEANWHT = 237.2126922607422 / Mean exposure time per pixel with data 
MEDWHT = 239.749755859375 / Median exposure time per pixel with data 

MEANEXPT= 234.9927062988281 / Mean exposure time per pixel with data 
MEDEXPT = 235.0 / Median exposure time per pixel with data ```
The former should be:

MEANWHT= Mean value in WHT image per pixel with data
MEDWHT   =Median value in WHT image per pixel with data

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587029#comment-587029):_

Interesting.  This was a problem, but it was corrected some time ago. The source code now says:

MEANWHT": Mean weight (typically exposure time) over pixels with data
 MEDWHT": Median weight (typically exposure time) over pixels with data

I will check what is going on.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587065#comment-587065):_

[Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack)

This bug was fixed on 19 April and the update is in the current build sequence.  We are currently on RC3 (1-based system).  Matt will need to regenerate the SVM results as they are already out-of-date.  Glad you are checking!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587260#comment-587260):_

Well, its not a showstopper in any means... but certainly a useful diagnostic to let us know what software was used for processing.  Thanks for checking!

**Comment by nden** [comment]
Jira ticket resolved. Closing

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=579114#comment-579114):_

Code was reviewed as Git PR#&#x2060;1324 and merged.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587028#comment-587028):_

[Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena)   For SVM datasets processed April 8, 2022, e.g.

/ifs/archive/ops/hst/public/jacs/hst_11515_01/17:31 hst_11515_01_acs_wfc_f814w_jacs01_drc.fits

The definition of MEANWHT and MEDWHT is identical to MEANEXPT and MEDEXPT.   
```java
MEANWHT = 237.2126922607422 / Mean exposure time per pixel with data 
MEDWHT = 239.749755859375 / Median exposure time per pixel with data 

MEANEXPT= 234.9927062988281 / Mean exposure time per pixel with data 
MEDEXPT = 235.0 / Median exposure time per pixel with data ```
The former should be:

MEANWHT= Mean value in WHT image per pixel with data
MEDWHT   =Median value in WHT image per pixel with data

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587029#comment-587029):_

Interesting.  This was a problem, but it was corrected some time ago. The source code now says:

MEANWHT": Mean weight (typically exposure time) over pixels with data
 MEDWHT": Median weight (typically exposure time) over pixels with data

I will check what is going on.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587065#comment-587065):_

[Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack)

This bug was fixed on 19 April and the update is in the current build sequence.  We are currently on RC3 (1-based system).  Matt will need to regenerate the SVM results as they are already out-of-date.  Glad you are checking!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587260#comment-587260):_

Well, its not a showstopper in any means... but certainly a useful diagnostic to let us know what software was used for processing.  Thanks for checking!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=579114#comment-579114):_

Code was reviewed as Git PR#&#x2060;1324 and merged.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587028#comment-587028):_

[Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena)   For SVM datasets processed April 8, 2022, e.g.

/ifs/archive/ops/hst/public/jacs/hst_11515_01/17:31 hst_11515_01_acs_wfc_f814w_jacs01_drc.fits

The definition of MEANWHT and MEDWHT is identical to MEANEXPT and MEDEXPT.   
```java
MEANWHT = 237.2126922607422 / Mean exposure time per pixel with data 
MEDWHT = 239.749755859375 / Median exposure time per pixel with data 

MEANEXPT= 234.9927062988281 / Mean exposure time per pixel with data 
MEDEXPT = 235.0 / Median exposure time per pixel with data ```
The former should be:

MEANWHT= Mean value in WHT image per pixel with data
MEDWHT   =Median value in WHT image per pixel with data

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587029#comment-587029):_

Interesting.  This was a problem, but it was corrected some time ago. The source code now says:

MEANWHT": Mean weight (typically exposure time) over pixels with data
 MEDWHT": Median weight (typically exposure time) over pixels with data

I will check what is going on.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587065#comment-587065):_

[Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack)

This bug was fixed on 19 April and the update is in the current build sequence.  We are currently on RC3 (1-based system).  Matt will need to regenerate the SVM results as they are already out-of-date.  Glad you are checking!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-726?focusedCommentId=587260#comment-587260):_

Well, its not a showstopper in any means... but certainly a useful diagnostic to let us know what software was used for processing.  Thanks for checking!
