### ISSUE TITLE
Deprecated photutils parameter needs to be replaced

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1310]
_Issue [HLA-728](https://jira.stsci.edu/browse/HLA-728) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Testing of Drizzlepac using photutils 1.2 triggered deprecation warnings for the 'filter_kernel' parameter for a function in `drizzlepac.haputils.catalog_utils`.  This needs to be replaced soon in order to prevent any problems with the next release of photutils.

**Comment by nden** [comment]
The fix for the same problem in jwst is here
https://github.com/spacetelescope/jwst/pull/6527/files

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-728?focusedCommentId=602591#comment-602591):_

Already resolved by HLA-749.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-728?focusedCommentId=602591#comment-602591):_

Already resolved by HLA-749.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-728?focusedCommentId=602591#comment-602591):_

Already resolved by HLA-749.
