### ISSUE TITLE
Units are incorrectly specified in source catalog headers

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1314]
_Issue [HLA-731](https://jira.stsci.edu/browse/HLA-731) was created on JIRA by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw):_

The units specified in the `unit` field in the headers of the ecsv files are not correct for the astropy.units module.  For example, some sample columns from a point.ecsv catalog are specified like this:
```
name: X-Center, unit: pixels
name: RA, unit: degrees
name: ID, unit: unitless
name: MagAp1, unit: ABMAG
```
If you read this catalog into astropy and print the column types using print(repr(tab[col].unit))
```java
from astropy.table import Table
tab = Table.read(filename,format="ascii.ecsv")
for col in tab.colname:
    print(col, repr(tab[col].unit))
```
... then you will see that the units were not read correctly:
```
X-Center UnrecognizedUnit(pixels)
RA UnrecognizedUnit(degrees)
ID UnrecognizedUnit(unitless)
MagAp1 UnrecognizedUnit(ABMAG)
```
The reason is that the units are specified incorrectly.  A correct version looks like:
```
name: X-Center, unit: pixel
name: RA, unit: degree
name: ID, unit: ''
name: MagAp1, unit: mag(AB)
```
Then the units as read into astropy are:
```
X-Center Unit("pix")
RA Unit("deg")
ID Unit(dimensionless)
MagAp1 Unit("mag(AB)")
```
I will give more details below, including a mapping of all the units to correct values.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-731?focusedCommentId=576620#comment-576620):_

The reason this was discovered is that the performance of `Table.read` when reading in the incorrect header units is very slow.  The units module spends a lot of time trying to guess what the units are supposed to be before it gives up.  We are reading all the ecsv files and inserting them into database tables, and about 25% of the time was being spent reading these headers!  It is about 3–4 times faster to read the corrected headers, which has a big impact on the execution time of our scripts.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Rick White](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rlw) on [JIRA](https://jira.stsci.edu/browse/HLA-731?focusedCommentId=576624#comment-576624):_

Here is a list of all the changes in units to get them into a format recognized by astropy.units:
```
Current version -> Correct version
pixels -> pixel
degrees -> degree
unitless -> '' (a null string)
ABMAG -> mag(AB)
electrons -> electron
electrons/s/pixel -> electron/(s pixel)
electrons/sec -> electron/s
radians -> radian```
There are some slight variants on these (e.g., `pixels**2` -> `pixel``**2`), but they should be obvious by searching for the above strings.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-731?focusedCommentId=576661#comment-576661):_

Issue addressed, tested, and out for review: Git PR#&#x2060;1316.

**Comment by mdlpstsci** [comment]
Resolved by JIRA HLA-731.
