### ISSUE TITLE
Review documentation for WFC3TOOLS

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1340]
_Issue [HLA-744](https://jira.stsci.edu/browse/HLA-744) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Review the documentation for the WFC3TOOLS as part of the WFC3 team effort.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-744?focusedCommentId=581347#comment-581347):_

The documentation is found here: <https://github.com/spacetelescope/wfc3tools/tree/master/docs/wfc3tools>

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-744?focusedCommentId=582723#comment-582723):_

I took a closer look at the documentation, and it is very out-of-date and outright incorrect in places.  It needs serious attention.  As such I will write a new ticket for actually fixing the issues with the documentation.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva) on [JIRA](https://jira.stsci.edu/browse/HLA-744?focusedCommentId=582725#comment-582725):_

In the interest of not duplicating work, I think the WFC3 team is working on this

spacetelescope/wfc3tools#61

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-744?focusedCommentId=582738#comment-582738):_

Understood, but they do not know what to do with the descriptions of calwf3 and its standalone components.  They were looking for help (for some reason they just did not ask me), and I offered.

**Comment by stsci-hack** [comment]
Issue relates to code outside of this package.
