### ISSUE TITLE
WFC3: Fix the outdated and incorrect WFC3TOOLS documentation for calwf3

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1352]
_Issue [HLA-759](https://jira.stsci.edu/browse/HLA-759) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The documentation for calwf3 and its standalone components is contained in the readthedocs for WFC3TOOLS.  The discussion is extensive as it is well beyond a discussion of function signatures, parameter descriptions, and high-level explanation.  Unfortunately, portions of the discussion are out-of-date, at best, or just wrong, at worst.  It will take time to update this documentation.    This WFC3 data handbook draws on this documentation for its contents, so it is important this information is correct.

Minimal background in HLA-744.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-759?focusedCommentId=582916#comment-582916):_

Git Issue #&#x2060;67 is the corresponding Git Ticket.

**Comment by stsci-hack** [comment]
Issue relates to code outside this package.
