### ISSUE TITLE
Release new fitsblender package and update dependency in drizzlepac

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1353]
_Issue [HLA-761](https://jira.stsci.edu/browse/HLA-761) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

A new version of fitsblender needs to be publicly released as v0.4.2.  Drizzlepac will then need to be updated to require this new version as the minimum in order to correctly process data after merging [Drizzlepac PR #&#x2060;1332](https://github.com/spacetelescope/drizzlepac/pull/1332) when fixing HLA-740.

This work is necessary in order to allow everything to install correctly.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-761?focusedCommentId=583061#comment-583061):_

[Fitsblender v0.4.2](https://github.com/spacetelescope/fitsblender/releases/tag/0.4.2) was publicly released to include the fix needed for HLA-740, while [stsci.skypac v1.0.9](https://github.com/spacetelescope/stsci.skypac/releases/tag/1.0.9) was also released to fix additional problems found during SVM reprocessing.  

Drizzlepac's installation dependencies were updated in the 'setup.cfg' file in [Drizzlepac PR #&#x2060;1354](https://github.com/spacetelescope/drizzlepac/pull/1354) to insure these new versions are included when this package gets installed.

**Comment by stsci-hack** [comment]
Closed by #1354
