### ISSUE TITLE
Verify that all datasets which failed in SVM Reprocessing have fixes

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1356]
_Issue [HLA-763](https://jira.stsci.edu/browse/HLA-763) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

A total of 67 datasets failed during SVM reprocessing after delivering the **mvmbeta** build to operations as part of HSTSDP2022.1.0.  We need to identify the type of error that each dataset triggered and document whether or not a fix has already been implemented or will be implemented based on tickets that have already been filed.  The list of dataset names has been attached for reference.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-763?focusedCommentId=583677#comment-583677):_

 
||Visit ID||Developer||Error||PR or Jira Ticket||
|ib7788
idkv19
jca541
ibr611
jbhj70
ibr62b
ibcdb1
jbhj63
idlh06
ie4r05
jca506
idk804
j8di78
jc1b05
icwz05
jca508
ibig07
ibtq22
ibg431
ibg421
icwz09
ibg451
jca502
j8hq9c
ibr641
icwz06
jbhm28
jc1b07
icvi45
icnk11
jbfuva
ie7h07
idio02
id5w03
ich316
ie4r06
icwz54
j9qo01
jc1b01
j8hqdu
icde41
jbhj08
jca501
icpd01
iec303
icwz31
j8yu10
icvd02
ie4220
j96a02
iepz25
ibdp14
jbfuvb
iege05
icde18
icwz07
icde39
ibg433
icwz44
jc1b11
ie3501
j8hqc1
j9i001
ibr63b
ibg409| | | |

**Comment by stsci-hack** [comment]
Resolved through a number of PRs, including #1354, #1355, #1431.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-763?focusedCommentId=602255#comment-602255):_

An additional set of failures were also reported on 4-Aug-2022 which need to be checked against the current version of the code on master (as of 17-Aug-2022 anyway).   The datasets include:
 *  acs_9ps_18, acs_9i0_01, acs_9qo_01, acs_8tq_13, wfc3_bdp_14, and wfc3_dlh_06 : 
*`IndexError: index -4 is out of bounds for axis 0 with size 3`*
 * wfc3_ch3_16 : 
*`AttributeError: 'list' object has no attribute 'icrs'`*

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-763?focusedCommentId=602277#comment-602277):_

HLA-817 was filed to fix the problem with *`ich316` (wfc3_ch3_16)* due to a missing 'icrs' attribute in the catalog generation step.

Turns out the cause of the problem is the fact that the input headers have 'REFFRAME' defined as 'OTHER', instead of the usual 'ICRS'.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-763?focusedCommentId=602309#comment-602309):_

I have confirmed that the visits which had the IndexError process successfully now, as they are the same problem as solved by HLA-753.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-763?focusedCommentId=602745#comment-602745):_

HLA-772 also refers to data that had problems during pipeline reprocessing.
