### ISSUE TITLE
SVM data with 'a priori' WCS need fit keywords reset to nan

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1391]
_Issue [HLA-788](https://jira.stsci.edu/browse/HLA-788) was created on JIRA by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack):_

For a number of datasets, the SVM FLC products with 'a priori' solution GSC240 have 6 keywords which should be 'nan':
 * **nmatches**
 * **rms_ra ,* *rms_dec**
 * **fitgeom**
 * **crder1, crder2**

Example:
#filename rootname asn_id instrume detector date-obs filter targname aperture subarray wcsname **nmatches rms_ra rms_dec fitgeom** naxis1 naxis2

hst_15518_01_wfc3_uvis_f606w_idxx01wx_flc.fits idxx01wxq IDXX01060 WFC3 UVIS 2019-06-07 F606W SDSSJ124535.626+423824.58 G280-REF False IDC_2731450pi-GSC240 **0.0 17.56070876748969 11.71322366887095 rscale** 4096 2051

The keywords appear to left over from a prior WCS solution:
{*}WCSNAMEC{*}= 'IDC_2731450pi-FIT_REL_GAIAeDR3' / Coordinate system title            

These data were reprocessed on April 20, 2022.
/ifs/archive/ops/hst/public/idxx/hst_15518_01

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=607388#comment-607388):_

Here is an example where we need to determine _*how*_ the keywords were set.  The problem is for the "A" solution, WCSNAMEA and HDRNAMEA, are inconsistent.  Also, it does not make sense for RMS_RAA and RMS_DECA to be present if the WCS is really `a priori`.  It should be noted the HDRNAMEA error with the "t" being cutoff in the string "flt" was previously noted and fixed.

**j94rc1owq**

WCSNAME = 'IDC_q692007bj-FIT_IMG_GAIAeDR3' / Coordinate system title
HDRNAME = 'j94rc1owq_flt_IDC_q692007bj-FIT_IMG_GAIAeDR3-hlet.fits'
RMS_RA  =    10.01431572502065 / RMS in RA of WCS fit(mas)
RMS_DEC =    23.41300665669865 / RMS in Dec of WCS fit(mas)

HDRNAMEA= 'j94rc1owq_fl_IDC_q692007bj-FIT_IMG_GAIAeDR3-hlet.fits'
RMS_RAA =     122.180644681692
RMS_DECA=    102.0041154465361
WCSNAMEA= 'IDC_q692007bj'      / Coordinate system title

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=611628#comment-611628):_

[Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack)

A value of **nan** only applies to floating point values.  However, the update to the keywords must adhere to the FITS standard, and **nan** is not allowed as a keyword value.  While I work this ticket, I will use the below values for the keywords in question.  We can then discuss if these values are suitable, change the values, or delete the keywords for the _*active*_ 'a priori' WCS solution altogether.

NMATCHES: 0

FITGEOM: ''

RMS_RA/RMS_DEC and CRDER1/CRDER2: 0.0

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612081#comment-612081):_

I noticed the WCSTYPE keyword for the active solution can also be incorrect.  For example,

WCSTYPE = 'undistorted a posteriori solution aligned by visit to GSC242'
WCSNAME = 'IDC_w3m18525i-GSC240' / Coordinate system title

The WCSTYPE here should actually be:

'undistorted a priori solution based on GSC240'

Not only will the keyword values for the 'active' WCS solution as specified in the description of this ticket by Jenn be corrected when the WCS solution is 'a priori', but the WCSTYPE keyword will also be updated (updatehdr module: interpret_wcsname_type) will also be corrected.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612312#comment-612312):_

So how is it that a "FIT" solution was rolled back to an 'a priori' solution?

In this case the specific dataset had a successful "FIT" WCS solution, but the 'active' WCS solution had to roll-back as the visit also is comprised of Grism data.  In this case, the common WCS solution for _*all*_ the images will be an 'a priori' solution as Grism data only have 'a priori' and a pipeline solutions.  During the roll-back, the above described keywords did not get reset to a default.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612323#comment-612323):_

[Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) 

I'm happy with your choices for the keyword values

NMATCHES: 0
FITGEOM: ''
RMS_RA/RMS_DEC and CRDER1/CRDER2: 0.0

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612615#comment-612615):_

The keywords associated with 'a posteriori' values retained their values even when the active WCS solution rolled back.  The roll-back is done for a dataset with Grism and direct images from the same detector.  It is desired that all the images in the dataset have the same 'active' WCS which requires the WCS to be 'a priori' as Grism images are not processed further.  When the 'a priori' WCS solution is restored, the keywords have their values reset as appropriate for the datatype (0, 0.0, and '').

This has been submitted as GitHub PR#&#x2060;1465.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612916#comment-612916):_

[Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) 

I am just checking as I am getting a lot of push-back regarding the 'a posteriori' keywords which no longer apply when the WCS solution is rolled back to an 'a priori' solution.  Are you sure you do not want these keywords **just deleted** from the active WCS solution?  The complaints are
 * these keywords are not appropriate for DRZ/DRC images, and
 * not all 'a priori' images will have these keywords so there is an inconsistency (or the keywords should be added with the default values which seems even more incorrect).

Thanks

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=613286#comment-613286):_

Sure!  Simply deleting, rather than resetting these keywords is definitely an acceptable solution.  :)

 

P.S.  I'm not sure I understand the comment 'these keywords are not appropriate for DRZ/DRC images', because drizzled data do inherit these keywords when there is a valid *a posteriori* solution.

**Comment by nden** [comment]
JIRA ticket resolved

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=607388#comment-607388):_

Here is an example where we need to determine _*how*_ the keywords were set.  The problem is for the "A" solution, WCSNAMEA and HDRNAMEA, are inconsistent.  Also, it does not make sense for RMS_RAA and RMS_DECA to be present if the WCS is really `a priori`.  It should be noted the HDRNAMEA error with the "t" being cutoff in the string "flt" was previously noted and fixed.

**j94rc1owq**

WCSNAME = 'IDC_q692007bj-FIT_IMG_GAIAeDR3' / Coordinate system title
HDRNAME = 'j94rc1owq_flt_IDC_q692007bj-FIT_IMG_GAIAeDR3-hlet.fits'
RMS_RA  =    10.01431572502065 / RMS in RA of WCS fit(mas)
RMS_DEC =    23.41300665669865 / RMS in Dec of WCS fit(mas)

HDRNAMEA= 'j94rc1owq_fl_IDC_q692007bj-FIT_IMG_GAIAeDR3-hlet.fits'
RMS_RAA =     122.180644681692
RMS_DECA=    102.0041154465361
WCSNAMEA= 'IDC_q692007bj'      / Coordinate system title

**_This is an issue for a different ticket._**

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=611628#comment-611628):_

[Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack)

A value of **nan** only applies to floating point values.  However, the update to the keywords must adhere to the FITS standard, and **nan** is not allowed as a keyword value.  While I work this ticket, I will use the below values for the keywords in question.  We can then discuss if these values are suitable, change the values, or delete the keywords for the _*active*_ 'a priori' WCS solution altogether.

NMATCHES: 0

FITGEOM: ''

RMS_RA/RMS_DEC and CRDER1/CRDER2: 0.0

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612081#comment-612081):_

I noticed the WCSTYPE keyword for the active solution can also be incorrect.  For example,

WCSTYPE = 'undistorted a posteriori solution aligned by visit to GSC242'
WCSNAME = 'IDC_w3m18525i-GSC240' / Coordinate system title

The WCSTYPE here should actually be:

'undistorted a priori solution based on GSC240'

Not only will the keyword values for the 'active' WCS solution as specified in the description of this ticket by Jenn be corrected when the WCS solution is 'a priori', but the WCSTYPE keyword will also be updated (updatehdr module: interpret_wcsname_type) will also be corrected.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612302#comment-612302):_

The WCS keywords named in the description above plus the WCSTYPE keyword will be updated for the 'active' WCS in all SCI extensions of an FLT/FLZ and DRZ/DRC file.

 Questions:
 # Should the alternate 'a priori' WCS solutions also be updated?
 # Should any headerlets containing 'a priori' solutions be updated?

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612312#comment-612312):_

So how is it that a "FIT" solution was rolled back to an 'a priori' solution?

In this case the specific dataset had a successful "FIT" WCS solution, but the 'active' WCS solution had to roll-back as the visit also is comprised of Grism data.  In this case, the common WCS solution for _*all*_ the images will be an 'a priori' solution as Grism data only have 'a priori' and a pipeline solutions.  During the roll-back, the above described keywords did not get reset to a default.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612323#comment-612323):_

[Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) 

I'm happy with your choices for the keyword values

NMATCHES: 0
FITGEOM: ''
RMS_RA/RMS_DEC and CRDER1/CRDER2: 0.0

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612615#comment-612615):_

The keywords associated with 'a posteriori' values retained their values even when the active WCS solution rolled back.  The roll-back is done for a dataset with Grism and direct images from the same detector.  It is desired that all the images in the dataset have the same 'active' WCS which requires the WCS to be 'a priori' as Grism images are not processed further.  When the 'a priori' WCS solution is restored, the keywords have their values reset as appropriate for the datatype (0, 0.0, and '').

This has been submitted as GitHub PR#&#x2060;1465.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-788?focusedCommentId=612916#comment-612916):_

[Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) 

I am just checking as I am getting a lot of push-back regarding the 'a posteriori' keywords which no longer apply when the WCS solution is rolled back to an 'a priori' solution.  Are you sure you do not want these keywords **just deleted** from the active WCS solution?  The complaints are
 * these keywords are not appropriate for DRZ/DRC images, and
 * not all 'a priori' images will have these keywords so there is an inconsistency (or the keywords should be added with the default values which seems even more incorrect).

Thanks
