### ISSUE TITLE
MVMs: Create larger thumnail preview images 

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1392]
_Issue [HLA-789](https://jira.stsci.edu/browse/HLA-789) was created on JIRA by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack):_

If the archive can handle the additional file size, it would be very helpful for the software to create larger preview images for MVMs.  The current binning makes them appear very blocky when viewing in the Portal.

The two JPGs listed below are attached for reference:

SIZE       FILENAME
636397  hst_skycell-p2058x07y05_acs_wfc_f814w_all_drc.jpg
1047       hst_skycell-p2058x07y05_acs_wfc_f814w_all_drc_thumb.jpg

**Comment by stsci-hack** [comment]
This issue relates to code outside this package.
