### ISSUE TITLE
WFC3: Review discussion of the varying IR background

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1403]
_Issue [HLA-796](https://jira.stsci.edu/browse/HLA-796) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

This is the initial ticket for the WFC3 IR varying background issue.  It is necessary first to become familiar with the issue and discussions as done by the instrument team in Slack channel {_}wfc3_flb{_}.  Notes should be taken and questions high-lighted for follow-up with the team point-of-contact, Harish Khandrika.  Determine if there are additional discussions or papers (ISR?) to be read.

**Comment by stsci-hack** [comment]
This issue relates to code outside this package.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-796?focusedCommentId=603977#comment-603977):_

Completed reading the discussion in Slack so I have a feeling for what is wanted. I still need to read the confluence pages associated with this issue.

<https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=WFC3CAL&title=TVB+testing>

<https://innerspace.stsci.edu/pages/viewpage.action?spaceKey=WFC3CAL&title=WFC3+Time+Variable+Background+Correction>
