### ISSUE TITLE
Review WFC3TOOLS documentation for calwf3 subcomponents

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1416]
_Issue [HLA-807](https://jira.stsci.edu/browse/HLA-807) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Review WFC3TOOLS documentation for calwf3 subcomponents: wf3cte, wf3ccd, wf32d, wf3ir, and wf3rej.  The documentation for calwf3 has already been done, as well as the history information.

**Comment by stsci-hack** [comment]
This issue relates to code outside of this package.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-807?focusedCommentId=606437#comment-606437):_

Working on the wfc3 CTE (wf3cte) documentation.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-807?focusedCommentId=606688#comment-606688):_

Updated the background discussion of the CTE step, particularly to inform users of the updated algorithm implemented/released at the end fo 2020. Still need to address API issues.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-807?focusedCommentId=608023#comment-608023):_

Due to the outdated documentation of the calibration pipeline components, this ticket is being split up.  This ticket covers: calwf3 (up to the description of the API) and wf3cte.  New tickets will be written to cover: wf3ccd, wf32d, wf3ir, and wf3rej.  Tickets will also be needed to correct any issues with both the C and Python APIs.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-807?focusedCommentId=608055#comment-608055):_

At this time waiting for some input from J. Anderson to describe the updated steps of the CTE correction.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-807?focusedCommentId=608573#comment-608573):_

Created PRs for the changes done to WFC3 `calwf3` and `wf3cte` in terms of the API description and noted any bugs (spacetelescope/hstcal #&#x2060;573).  SCSB needs to review.

Created PRs fo the chnages done to `calwf3` (previously done) and `wf3cte` both for code as well as the documentation (spacetelescope/wfc3tools #&#x2060;68 and #&#x2060;69).  WFC3 team needs to review.
