### ISSUE TITLE
Updating DrizzlePac's API Documentation

### ISSUE THREAD

**Issue by dsom-stsci** [spacetelescope/drizzlepac#1439]
I noticed several references to now-defunct TEAL and PyRAF in DrizzlePac's API documentation. The documentation needs to updated with the removal of these references.

**Comment by stsci-hack** [comment]
Good catch.  We will add this to our backlog of fixes for this package so that we can prioritize this work appropriately.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-866](https://jira.stsci.edu/browse/HLA-866)._

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-866](https://jira.stsci.edu/browse/HLA-866)._

**Comment by s-goldman** [comment]
This issue is now tracked in #1738
