### ISSUE TITLE
Updating  Drizzlepac to 3.1.2

### ISSUE THREAD

**Issue by miriamram96** [spacetelescope/drizzlepac#1442]
Hi,  I am currently learning how to use Drizzlepac. I am currently running the version 3.1.8.
I am trying to upgrade it to version 3.2.1  (or to the latest version).

Can anyone please help me with this?

I have tried running "$ conda update -n astroconda --all" and I am still stuck on Drizzlepac 3.1.8.

When I try to upgrade Drizzlepac I get the follwing:

`ERROR: Cannot install drizzlepac==2.2.1, drizzlepac==2.2.2, drizzlepac==2.2.3, drizzlepac==2.2.4, drizzlepac==2.2.5, drizzlepac==2.2.6, drizzlepac==3.0.2, drizzlepac==3.0.3, drizzlepac==3.0.4, drizzlepac==3.0.5, drizzlepac==3.1.3, drizzlepac==3.1.4, drizzlepac==3.1.5, drizzlepac==3.1.6, drizzlepac==3.1.8, drizzlepac==3.2.0, drizzlepac==3.2.1, drizzlepac==3.3.0, drizzlepac==3.3.1, drizzlepac==3.4.0, drizzlepac==3.4.1, drizzlepac==3.4.2 and drizzlepac==3.4.3 because these package versions have conflicting dependencies.
`
```
The conflict is caused by:
    drizzlepac 3.4.3 depends on stsci.tools>=4.0
    drizzlepac 3.4.2 depends on stsci.tools>=4.0
    drizzlepac 3.4.1 depends on stsci.tools>=4.0
    drizzlepac 3.4.0 depends on stsci.tools>=4.0
    drizzlepac 3.3.1 depends on stsci.tools>=4.0
    drizzlepac 3.3.0 depends on stsci.tools>=4.0
    drizzlepac 3.2.1 depends on stsci.image>=2.3.0
    drizzlepac 3.2.0 depends on stsci.image>=2.3.0
    drizzlepac 3.1.8 depends on stsci.image>=2.3.0
    drizzlepac 3.1.6 depends on stsci.image>=2.3.0
    drizzlepac 3.1.5 depends on stsci.image>=2.3.0
    drizzlepac 3.1.4 depends on stsci.image>=2.3.0
    drizzlepac 3.1.3 depends on stsci.image>=2.3.0
    drizzlepac 3.0.5 depends on stsci.image>=2.3.0
    drizzlepac 3.0.4 depends on stsci.image>=2.3.0
    drizzlepac 3.0.3 depends on stsci.image>=2.3.0
    drizzlepac 3.0.2 depends on stsci.image>=2.3.0
    drizzlepac 2.2.6 depends on stsci.convolve
    drizzlepac 2.2.5 depends on stsci.convolve
    drizzlepac 2.2.4 depends on stsci.convolve
    drizzlepac 2.2.3 depends on stsci.convolve
    drizzlepac 2.2.2 depends on stsci.convolve
    drizzlepac 2.2.1 depends on stsci.convolve

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```
Please help :( 

Thank you!

**Comment by stsci-hack** [comment]
The latest versions of this code can most easily be installed using the 'stenv' package found here:

https://github.com/spacetelescope/stenv

Please follow the directions for installing 'stenv' and you will end up running v3.4.3 (or later).  The instructions on the Drizzlepac main page show how to install from source code and those instructions will work just fine once you have created a new environment using 'stenv'.  I will see about updating those instructions to reflect this relatively new way to set up a Python environment to run this package.  Thank you for your patience while those updates to the documentation are made.

**Comment by nden** [comment]
No follow up for some time, closing this ticket. Please open a new one if necessary.
