### ISSUE TITLE
Add code to handle large displacements of stim pulses when COS is cold

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1456]
_Issue [HLA-812](https://jira.stsci.edu/browse/HLA-812) was created on JIRA by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij):_

As described in [COSPIP-160](https://jira.stsci.edu/browse/COSPIP-160).  Initial implementation.

**Comment by nden** [comment]
wrong repo
