### ISSUE TITLE
Fix the flake8 "white space" issues found in fitsblender source

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1457]
_Issue [HLA-819](https://jira.stsci.edu/browse/HLA-819) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Technical debt: Fix the flake8 "white space" (or other minor) issues detected in the source code while creating ci.yml/tox.ini.  These issues are documented in the new setup.cfg file, as well as in the comment in this ticket (note some line numbers may be slightly off due to important fixes having been done).

**Comment by stsci-hack** [comment]
Fixed by [Fitsblender PR #38](https://github.com/spacetelescope/fitsblender/pull/38).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-819?focusedCommentId=622965#comment-622965):_

These corrections were made under [FITSBLENDER PR#&#x2060;38](https://github.com/spacetelescope/fitsblender/pull/38).
