### ISSUE TITLE
jsons missing for astrodrizzle 3.5.0rc3 containing "-m" parameter

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1460]
_Issue [HLA-859](https://jira.stsci.edu/browse/HLA-859) was created on JIRA by [Lisa Sherbert](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sherbert):_

We decided to give drizzlepac 3.5.0rc2 a try on WFPC2 last week.  Came up with this error:

1665074290.080623: Calibration pipeline processing of u482c701r_d0m.fits started.*** astrodrizzle Processing Version 3.5.0rc3***    drizzlepac version 3.5.0rc3    tweakwcs version 0.8.0    stwcs version 1.7.2    numpy version 1.23.2_calfiles initialized as: ['u482c701r_flt.fits'][Errno 2] {*}No such file or directory{*}: '/ifs/pipeline/dms/rhel7/pkgs/miniconda3/envs/caldp_mvmdrizzle/lib/python3.9/site-packages/drizzlepac/pars/hap_pars/svm_parameters/{*}wfpc2/pc/wfpc2_pc_alignment_all.json'{*}ERROR: Cannot run astrodrizzle on -m.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-859?focusedCommentId=615893#comment-615893):_

This is an example of a problem with the installation scripts for this package.  The default WFPC2 parameter files found in the **drizzlepac/pars/hap_pars** directory for WFPC2 were not explicitly included in the list of data files that needs to be installed as specified in the \{*}'setup.py{*}' file.  A new PR will need to be filed to add these files to the installation code so that these files will be installed as expected for use in processing WFPC2 data.  

It is unfortunate that the error message causes confusion about the source of the error, implying a problem with an input parameter instead of simply not having the parameter files not installed.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-859?focusedCommentId=616055#comment-616055):_

It turns out this is NOT a problem for the code on master since those installation files were already updated to install all the WFPC2 parameter files using the new *'pyproject.toml'* configuration.  

This problem only affects the branch with Version *3.5.0rc2 and 3.5.0rc3.*

**Comment by nden** [comment]
Jira issue resolved. Closing

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-859?focusedCommentId=615893#comment-615893):_

This is an example of a problem with the installation scripts for this package.  The default WFPC2 parameter files found in the **drizzlepac/pars/hap_pars** directory for WFPC2 were not explicitly included in the list of data files that needs to be installed as specified in the \{*}'setup.py{*}' file.  A new PR will need to be filed to add these files to the installation code so that these files will be installed as expected for use in processing WFPC2 data.  

It is unfortunate that the error message causes confusion about the source of the error, implying a problem with an input parameter instead of simply not having the parameter files not installed.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-859?focusedCommentId=616055#comment-616055):_

It turns out this is NOT a problem for the code on master since those installation files were already updated to install all the WFPC2 parameter files using the new *'pyproject.toml'* configuration.  

This problem only affects the branch with Version *3.5.0rc2 and 3.5.0rc3.*
