### ISSUE TITLE
Prepare for CALSTIS changes required for time-dependent blaze shift work

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1493]
_Issue [HLA-871](https://jira.stsci.edu/browse/HLA-871) was created on JIRA by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij):_

Upcoming CALSTIS work on time-dependent blaze correction will require C code changes.  Since I am very rusty on C, do a little prep work to smooth the re-introduction, e.g. make sure I can build the code, maybe set up some testing infrastructure.

**Comment by nden** [comment]
wrong repo
