### ISSUE TITLE
Get github actions unit tests working on push for calcos

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1494]
_Issue [HLA-914](https://jira.stsci.edu/browse/HLA-914) was created on JIRA by [Robert Jedrzejewski](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rij):_

One of the unit tests isn't working because it relies on a file created in an earlier test.  It sometimes fails, probably need to set up a fixture or just recreate the file in the test

**Comment by nden** [comment]
wrong repo
