### ISSUE TITLE
AstropyDeprecationWarning: "clobber" was deprecated in version 1.3

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#15]
Example test: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=36464376

```
[WARNING ] /srv/iraf/bldtmp/porcelain.g23AA24Tm8/porcelain/envs/dev/lib/python2.7/site-packages/astropy/utils/decorators.py:470:
AstropyDeprecationWarning: "clobber" was deprecated in version 1.3
and will be removed in a future version. Use argument "overwrite" instead.
  AstropyDeprecationWarning)
```

**Comment by mcara** [comment]
While some of the warnings are coming from ``drizzlepac`` itself, others are coming from multiple dependent packages such as ``stsci.tools``, ``skymatch``, etc. I will start updating these packages and I will post back here each change.

**Comment by mcara** [comment]
So, I have created several PRs addressing the problem of deprecated ``clobber`` parameter in ``astropy.io.fits``:

- ``stsci.tools``: https://github.com/spacetelescope/stsci.tools/pull/20
- ``drizzlepac``: https://github.com/spacetelescope/drizzlepac/pull/28
- ``stsci.skypac``: https://github.com/spacetelescope/stsci.skypac/pull/2

@nden @stsci-hack However, the ``headerlet`` part of [``stwcs``](https://github.com/spacetelescope/stwcs) package needs to be updated as well as ``drizzlepac`` uses the headerlet facility. I have opened an issue https://github.com/spacetelescope/stwcs/issues/23 on ``stwcs``.

**Comment by pllim** [comment]
`stsci.tools`: It is merged and pushed to AstroConda via astroconda/astroconda-contrib#159

**Comment by mcara** [comment]
``stsci.skypac`` merged in https://github.com/spacetelescope/stsci.skypac/pull/2
``drizzlepac`` merged in https://github.com/spacetelescope/drizzlepac/pull/28

Only one more package left: https://github.com/spacetelescope/stwcs/issues/23

**Comment by mcara** [comment]
STWCS was updated in https://github.com/spacetelescope/stwcs/pull/24
Closing this issue.
