### ISSUE TITLE
TST: Add coverage test

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#153]
Once #149 is merged, perhaps you could simply make it also run a coverage report with the pytest coverage plugin. If #149 were to run in a matrix, only one of them need to generate coverage.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-700](https://jira.stsci.edu/browse/HLA-700)._

**Comment by stsci-hack** [comment]
Resolved with #1477 .

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-700](https://jira.stsci.edu/browse/HLA-700)._

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-700?focusedCommentId=630416#comment-630416):_

Resolved with [Drizzlepac PR #&#x2060;1477](https://github.com/spacetelescope/drizzlepac/pull/1477).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-700?focusedCommentId=630416#comment-630416):_

Resolved with [Drizzlepac PR #&#x2060;1477](https://github.com/spacetelescope/drizzlepac/pull/1477).
