### ISSUE TITLE
UnboundLocalError: local variable 'errorobj' referenced before assignment

### ISSUE THREAD

**Issue by griffin-h** [spacetelescope/drizzlepac#157]
When an exception occurs in a function called with `util.WithLogging`, that exception never makes it to the user because of an `UnboundLocalError` in the `wrapper` function. This is because `errorobj` is not defined inside the `finally` statement. It can be fixed by changing lines 219-220 of util.py from
```
            except Exception as errorobj:
                raise
```
to
```
            except Exception as e:
                errorobj = e
                raise
```

**Comment by mcara** [comment]
@griffin-h Thank you for reporting this and proposing a fix. I have implemented your fix in #158.
