### ISSUE TITLE
Implementing plan for drizzlepac readthedocs landing page

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1603]
_Issue [HLA-1048](https://jira.stsci.edu/browse/HLA-1048) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

Implement the outlined created in HLA-1032. This ticket is to improve the readability and flow of the current readthedocs landing page.

**Comment by nden** [comment]
Completed
