### ISSUE TITLE
Make program-level HASP filenames consistent with visit-livel

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1610]
_Issue [HLA-1055](https://jira.stsci.edu/browse/HLA-1055) was created on JIRA by [Matthew Burger](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mburger):_

HASP visit level filenames end in ipppss_cspec.fits where ipppss is from the underlying standard pipeline products.

Program-lelve filenames should end in ippp_cspec.fits for consistency.

Examples:

hst_11479_cos_grw+70d5824_g225m_laad01_cspec.fits

hst_11479_cos_grw+70d5824_g230l_laad_cspec.fits

Where the part in red is needs to be added.

**Comment by nden** [comment]
JIRA ticket is completed
