### ISSUE TITLE
Enable Teal support for drizCR and other tasks?

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#1618]
I do not know why but many years ago teal support for `drizCR` and other tasks was disabled - see https://github.com/spacetelescope/drizzlepac/commit/ac3a9d83df995e657b8862972ce5fa06b38ff4e7

Should this be re-enabled?

ATTN: @mdlpstsci @stsci-hack

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-1066](https://jira.stsci.edu/browse/HLA-1066)._

**Comment by s-goldman** [comment]
As we are planning on deprecating TEAL, this issue no longer seems relevant.
