### ISSUE TITLE
Add instructions for drizzlepac installation

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1621]
_Issue [HLA-1070](https://jira.stsci.edu/browse/HLA-1070) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

I've added a docs page for instructions on how to install drizzlepac. The current page just says _Coming Soon!_ but needs to describe how to install the package. This page may also want to describe the limitations, requirements, and easiest way to install it with stenv.

**Comment by etmeyer** [comment]
Is it possible to install the latest version of drizzlepac within stenv? Right now stenv ships with the broken version that has conflicts between numpy and minmed.

**Comment by nden** [comment]
We'll update stenv shortly. 
@zacharyburnett

**Comment by nden** [comment]
Meanwhile I think installing `pip install drizzlepac` should work.
