### ISSUE TITLE
Pyregion... but not really

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/drizzlepac#163]
@mcara @stsci-hack  This TODO is four years old give or take. If the fixes mentioned were not implemented upstream for whatever reason can't we put in a PR on `astropy/pyregion.git` to get this long standing issue resolved?

https://github.com/spacetelescope/drizzlepac/blob/42af55e913f71fe928621cb60aa830678ca3b6fe/drizzlepac/mapreg.py#L236-L239

Note: `spacetelescope/pyregion.git` is marked as an archived repo. As far as anyone knew _our special version_ wasn't used by anything (cc @SaOgaz)

**Comment by mcara** [comment]
@jhunkeler wrote:

> Note: `spacetelescope/pyregion.git` is marked as an archived repo. As far as anyone knew our special version wasn't used by anything.

My understanding was that even though it is archived, it will still be used by `drizzlepac` for the time being. The reason for this was given to @SaOgaz in an e-mail sent on 05/18/2018:

> I am not sure what this “archival” means. For now we do not need to make any changes/fixed to our copy of pyregion so you can continue keeping pyregion archived if you prefer so. We can un-archive it later if need be. Fundamentally `astropy/pyregion` removed support not only for tabular `WCS` corrections (by removing `WCS` support) but also they removed support for `SIP` distortions -  and this is too much [too large of an error]!

So, the link that you provide to the comment in the `drizzlepac` is not the only issue with the newest incarnation. Fundamentally, `astropy/pyregion` is a stripped-down version of the older package. I am not even sure it does anything better than the old one (except for not relying on `kapteyn` and using `astropy` instead - meh, IMO). Even worse, it looks like `astropy` intends to deprecate `pyregion` anyway (and that is why, probably, there isn't much activity there): https://github.com/astropy/pyregion/issues/66#issuecomment-235867631.

I can write my own function for writing regions re right way, but removed support for caller providing their own `WCS` - I can't fix that.

I also do not understand all this rush with archiving repositories anyway. What is the benefit of having `spacetelescope/pyregion` archived? I was hoping that it will not be harmful, but it looks like it was.

**Comment by jhunkeler** [comment]
On Slack @mcara suggested creating a `stregion` repo and changing the dependencies of `drizzlepac` to use it instead.

From my seat this is the only way to circumvent the current problem. If a user installs `drizzlepac` via `pip` they're going to end up with the Astropy release of `pyregion`, not ours. If we change the requirement to be `stregion` and throw it up on pypi, the user will always receive our version of the code.

**Comment by mcara** [comment]
@jhunkeler Let see if it would be possible to fast-track https://github.com/astropy/pyregion/pull/131 Maybe then we can start using `astropy/pyregion` though I am fearful of future changes to the package and API. If it is not stable enough, it will be more of a headache. So, maybe it still would make sense to switch to our own code. Also, I can't be sure that `astropy/pyregion` has kept all the capabilities of the older package _and_ that it will be easy enough to transition to `astropy/pyregion` (i.e., I will need to test that everything works as it should, and this is time consuming). What do you think @jhunkeler ?

**Comment by jhunkeler** [comment]
Regarding what was discussed inhttps://github.com/astropy/pyregion/pull/131 ... do you think https://github.com/astropy/regions is a viable alternative?

Side-note: All of these different `XYZregion` packages are going to confuse me at some point.

**Comment by mcara** [comment]
@jhunkeler I did not spend much time - just a quick look ... and it seems that it might be. However, it is not a drop-in replacement and it will definitely take more time to incorporate.

**Comment by mcara** [comment]
@jhunkeler Thank you very much for `stregion` and for really great `README.md`!!!
