### ISSUE TITLE
Background research on SVM catalog creation

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1635]
_Issue [HLA-1091](https://jira.stsci.edu/browse/HLA-1091) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

In order to work on HLA-625, I need to do research on how catalogs are created, the logic behind it, and the output results.

**Comment by nden** [comment]
JIRA ticket completed
