### ISSUE TITLE
Calwf3 support for IR time-dependent photometry (IMPTTAB)

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1647]
_Issue [HLA-1103](https://jira.stsci.edu/browse/HLA-1103) was created on JIRA by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack):_

The IR sensitivity is declining, similarly to UVIS, and we need calwf3 to be able to use a modified IMPHTTAB which has time-dependent columns correponding to the PHOTFLAM values for a set of uniformly spaced MJDs. 

The calwf3 code will then linearly interpolate the PHOTFLAM value for any MJD when populating keywords in the image header in the PHOTCORR step.

A github issue related to this issue is filed here: spacetelescope/hstcal#588

WFC3 hopes to have the calwf3 changes in place by end-September, if feasible, and we will wait to hear back from Michele regarding her workload.  For reference, this work is higher priority for WFC3 development than the IR TVB code.

**Comment by nden** [comment]
wrong repository, closing

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-1103?focusedCommentId=657459#comment-657459):_

I didn't realize there was already a ticket opened by Michele in June. 
<https://jira.stsci.edu/browse/HLA-1036>

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-1103?focusedCommentId=694403#comment-694403):_

This is a duplicate issue to HLA_1036 so I am cancelling this ticket as HLA-1036 already contains results.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-1103?focusedCommentId=694404#comment-694404):_

Duplicate of HLA-1036.
