### ISSUE TITLE
RTD failure: Invalid configuration option "python.system_packages".

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1670]
_Issue [HLA-1123](https://jira.stsci.edu/browse/HLA-1123) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

Readthedocs is failing with the following error. 

Error

Problem in your project's configuration. Invalid configuration option "python.system_packages". This configuration key has been deprecated and removed. Refer to <https://blog.readthedocs.com/drop-support-system-packages/> to read more about this change and how to upgrade your config file.

**Comment by nden** [comment]
This has been fixed in #1659 . If you are still seeing the issue, perhaps you need to rebase?

**Comment by pllim** [comment]
You should just close this issue. It is indeed fixed.
