### ISSUE TITLE
TST: Test against numpy 2.0.dev and Python 3.12

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#1673]
Should do it sooner than later. Probably should prioritize Python 3.12 if you cannot do both at the same time.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-1125](https://jira.stsci.edu/browse/HLA-1125)._

**Comment by pllim** [comment]
For stsci.tools , I tried at https://github.com/spacetelescope/stsci.tools/pull/153 to the extend of the test suite coverage.

But looking at your long list of dependencies, good luck.

p.s. PyPDF2? Why?
