### ISSUE TITLE
Reproduce error in HLA-1161

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1705]
_Issue [HLA-1163](https://jira.stsci.edu/browse/HLA-1163) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

Start debugging [HLA-1161](https://jira.stsci.edu/browse/HLA-1161) by reproducing the error on the main branch seen by rick using program: j8vo01. Check to see if the issue is with the point-source catalog, the segmentation catalog, or both.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman) on [JIRA](https://jira.stsci.edu/browse/HLA-1163?focusedCommentId=671837#comment-671837):_

Number of sources with negative values.

f435w
 * Point-source catalog:
 ** MagAp1: 0 
 ** MagAp2: 0
 ** MagErrAp1: 4 
 ** MagErrAp2: 6

 
 * Segmentation catalog:
 ** MagAp1: 0 
 ** MagAp2: 0
 ** MagErrAp1: 14014
 ** MagErrAp2: 6562
 ** FluxAp1: 6562
 ** FluxAp2: 14014
 ** FluxErrAp1: 0
 ** FluxErrAp2: 0

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman) on [JIRA](https://jira.stsci.edu/browse/HLA-1163?focusedCommentId=671840#comment-671840):_

I see cases with:

 

MagAp2: -9999

MagErrAp2: -16.866

**Comment by s-goldman** [comment]
closed by #1700
