### ISSUE TITLE
TST: Add test build with Astropy dev

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#177]
See https://github.com/spacetelescope/drizzlepac/pull/173#issuecomment-422118584

**Comment by nden** [comment]
I believe this is the test on boyle.

**Comment by pllim** [comment]
Feel free to close if it is done.

**Comment by nden** [comment]
There's a regression tests run on Jenkins using dev versions of dependencies in requirements-dev.txt, including astropy.
