### ISSUE TITLE
issues raised by SonarQube static code analysis

### ISSUE THREAD

**Issue by zacharyburnett** [spacetelescope/drizzlepac#1799]
resolves [SCSB-151](https://jira.stsci.edu/browse/SCSB-151)

before regression tests can be run on GHA for `drizzlepac`, these issues must be resolved:
https://plsonarqube.stsci.edu/project/issues?resolved=false&types=BUG&inNewCodePeriod=true&id=drizzlepac

- [x] `Change or remove this string; "getHelpAsString" is not defined.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/ablot.py#L32
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/findobj.py#L19-L23
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/pixreplace.py#L17

- [x] `Add 1 missing arguments; 'create_output' expects 2 positional arguments.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/adrizzle.py#L245
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/adrizzle.py#L312
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/adrizzle.py#L318

- [x] `Add 1 missing arguments; 'run' expects at least 2 positional arguments.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/devutils/comparison_tools/starmatch_hist.py#L870
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/starmatch_hist.py#L870

- [x] `Add 1 missing arguments; 'get_ci_info' expects at least 4 positional arguments.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/ci_table.py#L213

- [x] `Fix this attribute access on a value that can be 'None'.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/hapmultisequencer.py#L566
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/updatehdr.py#L520

- [x] `Remove this "return" statement from this "finally" block.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/hapsequencer.py#L758

- [x] `Verify this is the key that was intended; a value has already been saved for it on line 1437.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/align_utils.py#L1437-L1438

- [x] `Verify this is the key that was intended; a value has already been saved for it on line 517.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/tweakback.py#L521

- [x] `Fix this formatted string's syntax.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/astrometric_utils.py#L609

- [x] `Introduce a new variable or use its initial value before reassigning 'dao_threshold'.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/astrometric_utils.py#L960-L961

- [x] `Introduce a new variable or use its initial value before reassigning 'align_table'.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/product.py#L188

- [x] `Introduce a new variable or use its initial value before reassigning 'ivmlist'.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/processInput.py#L670

- [x] `Correct one of the identical sub-expressions on both sides of operator "and".`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/config_utils.py#L62

- [x] `str_ra is used before it is defined. Move the definition before.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/hapcut_utils.py#L118

- [x] `Remove or correct this useless self-assignment.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/mvm_quality_analysis.py#L892
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/haputils/product.py#L1522

- [x] `Raise this exception or remove this useless statement.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/imgclasses.py#L1052-L1053

- [x] `tddfile is used before it is defined. Move the definition before.`
https://github.com/spacetelescope/drizzlepac/blob/8fc110f831323f22c8af6b348e7dd3f081715ced/drizzlepac/nicmosData.py#L426

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-1252](https://jira.stsci.edu/browse/HLA-1252)._
