### ISSUE TITLE
Final Drizzle with Reference Image

### ISSUE THREAD

**Issue by wwaldron** [spacetelescope/drizzlepac#183]
I've had to drizzle together a large number of images with low SNR and decided to follow [the algorithm suggested by STSCI](http://www.stsci.edu/hst/acs/documents/isrs/isr1504.pdf). I created an [executable python script](https://github.com/wwaldron/AstrOptical/blob/dev/bin/sextweak) to try to pull all the images together. Everything seems to be working and all the FLCs I am using seem to be well aligned at this point, but I cannot get the final WCS to match across the three final DRCs. I would like them to match as closely as possible for use with SExtractor, but they are consistently a half pixel off.

This may not be a big issue, but I wanted to make sure I am not missing a final setting that needs to be there. Upon looking at the [output of the script](https://github.com/spacetelescope/drizzlepac/files/2460735/script_output.txt), it appears that the CRPIX values are not getting assigned to the same value.

This could be user error, and thought you all would be helpful or that this information might be useful.

**Comment by mcara** [comment]
It looks like in your python script you are not setting `final_wcs` parameter to `True`. Without this custom WCS parameters are ignored. Could you please verify that setting `final_wcs` to `True` solves this issue?

**Comment by mcara** [comment]
Also, I think this block is not necessary: https://github.com/wwaldron/AstrOptical/blob/81987bfd77145bffec77ff393811b459002ef9f4/bin/sextweak#L240 because reference WCS already has information about axis size.

**Comment by wwaldron** [comment]
Thanks for the quick reply and the note about the unneeded block. As far as the `final_wcs` goes, I think that is handled on [line 258](https://github.com/wwaldron/AstrOptical/blob/dev/bin/sextweak#L258).

**Comment by mcara** [comment]
I missed that (`final_wcs`): I was looking at `drizassoc()`. Still, could you please remove the code for explicitly setting `outnx` and `outny` sizes in L240? It seem that this automatically triggers re-computation of  `crpix` and overwrites the one from the `refimage`. If you want to drizzle all images onto a single output grid, simply provide a reference image.

**Comment by wwaldron** [comment]
That seems to have fixed the issue. Thank you very much for your help! I had beaten my head against the wall over this issue. The fixes are represented in the same file referenced before. If it is any use to your team, feel free to grab it. I hope to dress it up a little and document what it's doing a little better.

**Comment by mcara** [comment]
@wwaldron Thank you for letting us know that proposed fixed worked for you.
