### ISSUE TITLE
fix issues raised by sonarscan

### ISSUE THREAD

**Issue by zacharyburnett** [spacetelescope/drizzlepac#1841]
https://plsonarqube.stsci.edu/project/issues?resolved=false&types=BUG&id=drizzlepac

- [x] `Remove this unexpected named argument 'force'.`
https://github.com/spacetelescope/drizzlepac/blob/be51dfcada9025e4323ead5b9184851ac08e4a96/drizzlepac/hapmultisequencer.py#L340

- [x] `Remove this unexpected named argument 'force'.`
https://github.com/spacetelescope/drizzlepac/blob/be51dfcada9025e4323ead5b9184851ac08e4a96/drizzlepac/hapsequencer.py#L507

- [ ] `Fix this code; this expression does not have a "__getitem__" method.`
https://github.com/spacetelescope/drizzlepac/blob/be51dfcada9025e4323ead5b9184851ac08e4a96/drizzlepac/mapreg.py#L101

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-1285](https://jira.stsci.edu/browse/HLA-1285)._

**Comment by zacharyburnett** [comment]
@mdlpstsci do you know by chance if these lines are actually used / covered by tests?

**Comment by mdlpstsci** [comment]
@zacharyburnett 
I speculate these lines are NOT explicitly covered by tests.
