### ISSUE TITLE
WCS._naxis1/2 deprecated

### ISSUE THREAD

**Issue by nden** [spacetelescope/drizzlepac#186]
As a heads up - the next astropy release, 3.1,  deprecates `WCS._naxis1/2` . Instead `WCS.pixel_shape` should be used. `WCS.pixel_shape` is a list of `[NAXIS1, NAXIS2, ...]`.

**Comment by philhodge** [comment]
pixel_shape is not a good name.  Pixels can be rectangular, and they can even be hexagonal.

**Comment by nden** [comment]
`pixel_shape` is defined in the [WCS APE](https://github.com/astropy/astropy-APEs/pull/45). In this context it means the shape of the data array in pixel space. Please comment on the APE PR if you feel strongly about it.

**Comment by mcara** [comment]
I agree with @philhodge Why is it not `image_shape`?

**Comment by mcara** [comment]
or even `domain_shape`

**Comment by nden** [comment]
@mcara Because there's an ambiguity about the order of axes - numpy order vs FITS order. The compromise was to have two attributes - `pixel_shape` (for FITS ) and `array_shape` (for np ordering).

**Comment by mcara** [comment]
Fixed via https://github.com/spacetelescope/drizzlepac/pull/207 (which also drops support for Python 2).
