### ISSUE TITLE
Drizzlepac/HAP: Document recent change in s-region calculation

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#1890]
_Issue [HLA-1342](https://jira.stsci.edu/browse/HLA-1342) was created on JIRA by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman):_

**Comment by s-goldman** [comment]
closed with #1891

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Steve Goldman](https://jira.stsci.edu/secure/ViewProfile.jspa?name=sgoldman) on [JIRA](https://jira.stsci.edu/browse/HLA-1342?focusedCommentId=732291#comment-732291):_

Closed with [#&#x2060;1891](https://github.com/spacetelescope/drizzlepac/pull/1891).
