### ISSUE TITLE
VerifyWarning: Card is too long, comment will be truncated

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#19]
Example test: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=36464239

```
[WARNING ] VerifyWarning: Card is too long, comment will be truncated.
```

**Comment by mcara** [comment]
See my comment https://github.com/spacetelescope/drizzlepac/issues/18#issuecomment-277499137

CC: @nden @stsci-hack

**Comment by philhodge** [comment]
An alternative is to use a shorter comment, maybe much shorter.  If the 
warning is "comment will be truncated", then we could just ask DMS to 
use a shorter comment string when creating the raw file.

**Comment by mcara** [comment]
@philhodge I do not think that a shorter comment will help. The problem is in long _keyword names_. The warning message is:

> _Keyword name 'IDCSCALEO' is greater than 8 characters_ or contains characters not allowed by the FITS standard; a **HIERARCH** card will be created.

Also see https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/f_user/node28.html

**Comment by mcara** [comment]
@philhodge Ah, my bad... there is also another warning (the one mentioned in the original description of the issue):

> [WARNING ] VerifyWarning: Card is too long, comment will be truncated.

That one may be solved as you suggest.

**Comment by pllim** [comment]
> Keyword name 'IDCSCALEO' is greater than 8 characters...

@mcara , I am so glad that you are already working on this one, as I was just about to open another issue for it... :joy:

**Comment by mcara** [comment]
@stsci-hack @nden @pllim No, I am not working on this issue as I do not really know what to do about it. This is not really related to astrodrizzle software but rather to the length of the keywords used at STScI. I do not know who is responsible for re-defining keywords at STScI but it is definitely not me.

**Comment by pllim** [comment]
By the way, you can always tag this issue was "wont fix" and close it if it is out of scope.

**Comment by mcara** [comment]
Good to know. However, maybe it is worth keeping open until @stsci-hack gets a chance to look at it. Even though it is not a software issue (in my opinion), maybe it is something to be raised with other teams.

**Comment by mcara** [comment]
Fundamentally, this is not a problem with ``drizzlepac`` but rather due to the fact that STScI uses long comments in headers.
