### ISSUE TITLE
Fix failing tests on pandokia

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#20]
There are a bunch of failing tests on all platforms. For example, see https://ssb.stsci.edu/pandokia/pandokia.cgi?query=treewalk&host=%25&project=drizzlepac&test_run=conda-conda_tests_2017-01-24-10%3A30%3A01

**Comment by mcara** [comment]
I have OKified most tests (after undoing last OKification). However, there are 3-4 failing tests remaining that require more investigation. @stsci-hack

**Comment by mcara** [comment]
I have also updated (r1585 and r1586) two ``cfg`` files to get rid of configuration file validation warnings.

**Comment by mcara** [comment]
As a note, it is highly likely that _very large_ differences in in about ~7000 pixels in ``wfc3/ir/wfc3_ir_saturated`` tests are due to https://github.com/spacetelescope/drizzlepac/issues/12 
The unit conversion was affecting minmed option and thus small (=minor, negligible) differences in data values seen in some tests that use ``minmed`` option could be attributed to the same https://github.com/spacetelescope/drizzlepac/issues/12

**Comment by pllim** [comment]
FYI -- Number of failing tests have decreased but inconsistent between `nott` and `pembry`.

**Comment by mcara** [comment]
I have okified three more tests (``stis_01``, ``stis_04``, and ``wfc3_uvis_asn``) in OSX: when run against currently passing Linux reference files these tests show negligible differences in data.

**Comment by mcara** [comment]
I have fixed ``unit/unit.test_driz.TestDriz.test_lanczos_with_grid`` (and with it other "unit" tests) in r1589 (modified ``test_driz.py``). The code was comparing centroids in two images (test image and reference image) using different initial estimates for centroid position leading to different centroid positions => failing tests.

I expect unit tests to clear tomorrow once tests are re-run.

**Comment by mcara** [comment]
@stsci-hack There is a disabled test ``unit/test_drizzlepac`` (see, e.g., https://ssb.stsci.edu/pandokia/pandokia.cgi?query=summary&qid=5441) that is chronically disabled. Docstring for this test says:

> Call C unit tests for cdrizzlepac, which are in the src/tests directory

However, there is no such directory as ``src/tests``. Should this test be removed?

**Comment by mcara** [comment]
<img width="361" alt="teststatus2017-02-11" src="https://cloud.githubusercontent.com/assets/5985250/22858587/ce2c1c4e-f08f-11e6-9bf0-f431580f9e55.png">

**Comment by pllim** [comment]
I can confirm that all tests passed on all builds. Congratulations! 

Now you can fix the JWST pipeline tests? :wink:
