### ISSUE TITLE
RuntimeWarning: invalid value encountered

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#22]
Example test: https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=36464242

```
[WARNING ] /srv/iraf/bldtmp/porcelain.g23AA24Tm8/porcelain/envs/dev/lib/python2.7/site-packages/drizzlepac/minmed.py:220:
RuntimeWarning: invalid value encountered in sqrt
  __rms_file = np.sqrt(__median_file_weighted + __bkgd_file + __readnoise_file)

[WARNING ] /srv/iraf/bldtmp/porcelain.g23AA24Tm8/porcelain/envs/dev/lib/python2.7/site-packages/drizzlepac/minmed.py:247:
RuntimeWarning: invalid value encountered in less
  __minimum_flag_file = np.where(np.less(__minimum_file_weighted,__median_rms_file),1,0)

[WARNING ] /srv/iraf/bldtmp/porcelain.g23AA24Tm8/porcelain/envs/dev/lib/python2.7/site-packages/drizzlepac/minmed.py:301:
RuntimeWarning: invalid value encountered in less
  self.combArrObj = np.where(np.less(__minimum_file_weighted,__median_rms2_file),
```

**Comment by pllim** [comment]
Seems to have disappeared as of Feb 5, on dev.

**Comment by pllim** [comment]
Ops, sorry for the noise. It is still there.

**Comment by mcara** [comment]
The funny part is that this issue was foreseen since the beginning: https://github.com/spacetelescope/drizzlepac/blob/master/lib/drizzlepac/minmed.py#L219

**Comment by mcara** [comment]
I created a PR that fixes this issue: https://github.com/spacetelescope/drizzlepac/pull/33

However, because I expect this PR to break multiple tests, I would want to have existing failing tests to be OKified first before this PR can be merged.

CC: @stsci-hack

**Comment by mcara** [comment]
Solved by https://github.com/spacetelescope/drizzlepac/pull/33
