### ISSUE TITLE
Question about compute_photometry

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#231]
https://github.com/spacetelescope/drizzlepac/blob/96c099744e5ef429969acd023683e0631f6557b2/drizzlepac/hlautils/astrometric_utils.py#L761-L770

Why VEGAMAG? Why use PySynphot do to real-time calculation? Why not use IMPHTTAB to be consistent with how HSTCAL calculate photometric zeropoints and reduce number of dependencies of this package?

**Comment by mcara** [comment]
CC: @mdlpstsci @stsci-hack @dulude

**Comment by pllim** [comment]
Please strongly consider not using PySynphot in Drizzlepac. It is a legacy package.

**Comment by pllim** [comment]
Looks like this is fixed in #440
