### ISSUE TITLE
Remove astropy.six import

### ISSUE THREAD

**Issue by nden** [spacetelescope/drizzlepac#237]
From the tests with dev versions on boyle
```
miniconda/envs/tmp_env1/lib/python3.6/site-packages/astropy/extern/six.py:15
  /srv/jenkins/workspace/RT/drizzlepac@2/miniconda/envs/tmp_env1/lib/python3.6/site-packages/astropy/extern/six.py:15: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed
    AstropyDeprecationWarning)
```

If six is still needed it should be imported directly.

**Comment by mcara** [comment]
@nden There is no explicit import of `astrpy.six` in the `drizzlepac`. Could it be that this message is generated in a dependent package?

**Comment by nden** [comment]
It's possible. It may be coming from any package that is run as part of a test.
