### ISSUE TITLE
Order of releases and tags, i.e., versioning scheme

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#239]
@jhunkeler I am trying to fix some code in the hla pipeline and also update `CHANGELOG.rst` with all the recent changes that have not been logged, but I am confused about labeling and timing of tags. Normally, I would assume that tags increase with time. However, I see that is not the case with most recent releases. Specifically, it seems that `3.0.0.rc2` was released after `3.0.1a`. Any explanation for what I see?

<img width="704" alt="driz_releses_tags" src="https://user-images.githubusercontent.com/5985250/53157437-83d6d200-358f-11e9-9503-cb12462a0262.png">

CC: @mdlpstsci @stsci-hack

**Comment by nden** [comment]
I'll ping you when we discuss this.
