### ISSUE TITLE
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#27]
Examples:
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=38489285
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=38489286

```
[WARNING ] .../drizzlepac/updatehdr.py:321: VisibleDeprecationWarning:
using a non-integer number instead of an integer will result in an error in the future
  a = inv[0.0]
```

**Comment by mcara** [comment]
@pllim have mercy

**Comment by pllim** [comment]
@stsci-hack asked me to do it. I'm sorry. I think this is the last of the batch, for now.

**Comment by mcara** [comment]
I do not like this "..., __for now__" 😄

**Comment by pllim** [comment]
Because of you, I have a cron job to monitor. So it goes both ways...

**Comment by mcara** [comment]
Fixed in https://github.com/spacetelescope/drizzlepac/pull/29
