### ISSUE TITLE
Address code and efficiency clean-up as noted in PR#283/PR#259

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/drizzlepac#295]
The purpose of this ticket is to document there is code and efficiency clean-up which needs to be done to the alignment portion of the drizzlepac package.  The comments and details can be found as part of the code review done on PR#283 and PR#259.  While some items were addressed, particularly bugs, the remaining items are blanket covered by this issue.  This ticket should be subdivided into more targeted issues to avoid code smuggling which has already happened in order to satisfy PR#283.

**Comment by dulude** [comment]
PR #298  addresses two items raised in #283  : Namely [this one](https://github.com/spacetelescope/drizzlepac/pull/283#discussion_r268901463), and [this one](https://github.com/spacetelescope/drizzlepac/pull/283#discussion_r268903028).
