### ISSUE TITLE
Make new releases

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#31]
New releases of `drizzlepac` and its affected dependencies are needed to propagate the fixes of deprecation warnings to our public build on AstroConda. (So, really the process is GitHub releases + AstroConda recipe updates.)

EDIT: Deprecation warning is not as urgent as critical bug fix, so for packages with only fixes to these warnings, the release can wait but should be done before the deprecated codes are removed completely from their dependencies (e.g., Astropy).

p.s. If you maintain PyPi etc, that needs updating too but I don't care about that.

**Comment by larrybradley** [comment]
Please include `fitsblender` in the new releases to include a fix I made there.

**Comment by mcara** [comment]
I do not understand the need for this "issue". Of course we will make a release once some other issues are taken care of. at this moment I am not ready to make a release.

@larrybradley @jhunkeler Isn't each package "independent", at least with regard to releases? Why realeasing of ``fitsblender`` is even mentioned here?

**Comment by larrybradley** [comment]
I mentioned it here only ecause it's an "affected dependency" and if you're going to make new releases to include it.  I would do it myself, but I don't know if you have any other pending changes.

**Comment by pllim** [comment]
If `fitsblender` is used by `drizzlepac` and will cause the latter to emit such warning, then it is counted as one of the "affected dependencies". I opened this issue because there are so many packages involved, and I am loosing track, so this serves as a reminder.

**Comment by mcara** [comment]
@larrybradley 
> ... I would do it myself, but I don't know if you have any other pending changes.
I do not have any pending changes for ``fitsblender``.

@pllim 
> ... I am loosing track, so this serves as a reminder.
I promise not to forget all the packages affected by recent changes (while working on latest ~2 weeks ago issues).

**Comment by mcara** [comment]
@jhunkeler Please make releases for:
stsci.convolve
stsci.skypac
stsci.tools (maybe pending your investigation of https://github.com/spacetelescope/stsci.tools/issues/22)
stwcs (if @nden agrees)
pysynphot
reftools
fitsblender

Please hold off releasing ``drizzlepac``: I am still working on two issues (unless @pllim add more as we speak 😄 ).

**Comment by pllim** [comment]
EDIT: I cross out pysynphot in the list above. The changes made has no effect on user-facing API.

**Comment by nden** [comment]
Are we supposed to make a public release after every change in master now? There's one change in stwcs since the last release and it's to hide this DeprecationWarning, it's not even a bug fix release.
I don't understand ...

**Comment by mcara** [comment]
@nden Specifically this last change is not urgent at all now according to https://github.com/astropy/astropy/issues/5644#issuecomment-277701013

**Comment by mcara** [comment]
@jhunkeler Please make releases for packages listed in https://github.com/spacetelescope/drizzlepac/issues/31#issuecomment-277803027 AND ``drizzlepac``

Issue https://github.com/spacetelescope/drizzlepac/issues/32 may take longer time to solve and if a problem will be found, it will be fixed in a separate release.

**Comment by pllim** [comment]
@mcara , @jhunkeler -- As @nden wisely pointed out, the releases are not critical until deprecated codes are actually removed from Astropy (we have a few months, at least). Do you agree? Or are there enough actual bug fixes (not just deprecation) that warrant immediate release?

**Comment by mcara** [comment]
@pllim Updated version of my previous post:

@jhunkeler Please make releases for packages listed in https://github.com/spacetelescope/drizzlepac/issues/31#issuecomment-277803027 AND ``drizzlepac`` **EXCEPT for ``stwcs`**`.

@pllim Yes, most of the packages listed in https://github.com/spacetelescope/drizzlepac/issues/31#issuecomment-277803027 (except ``stwcs``) have changes other than ``clobber`` deprecation warning. And even if some packages have *only* ``clobber`` deprecation warning, it is still something that is worth releasing.

**Comment by mcara** [comment]
@pllim @jhunkeler 

- ``stsci.convolve``: fixed ``rank`` deprecation warning: https://github.com/spacetelescope/stsci.convolve/issues/5
- ``stsci.tools``): fixed ``clobber`` deprecation warning (see https://github.com/spacetelescope/stsci.tools/pull/20) and fix for removed ``new_table`` (see https://github.com/spacetelescope/stsci.tools/pull/18)
- ``fitsblender``: fix for removed ``new_table`` (see https://github.com/spacetelescope/fitsblender/pull/6)
- ``reftools``: fix for removed ``new_table`` (see https://github.com/spacetelescope/reftools/pull/10)
- ``drizzlepac``: too many issues to list
- ~~``stsci.skypac`~~`: fixed ``clobber`` deprecation warning: https://github.com/spacetelescope/stsci.skypac/pull/2 (@jhunkeler if releasing, make version 0.9.1)
- ~~``stwcs``~~: fixed ``clobber`` deprecation warning (https://github.com/spacetelescope/stwcs/pull/24)

**Comment by jhunkeler** [comment]
@mcara FYI

https://github.com/astroconda/astroconda-contrib/pull/167
https://github.com/astroconda/astroconda-contrib/pull/166
https://github.com/astroconda/astroconda-contrib/pull/165
https://github.com/astroconda/astroconda-contrib/pull/164
https://github.com/astroconda/astroconda-contrib/pull/159

All merged.

I didn't touch `drizzlepac` or `stwcs`.

**Comment by mcara** [comment]
@jhunkeler URGENT: Please touch ``drizzlepac``: it is ready for release.

**Comment by jhunkeler** [comment]
https://github.com/astroconda/astroconda-contrib/pull/168 🚀

**Comment by mcara** [comment]
@pllim In light of https://github.com/spacetelescope/drizzlepac/issues/31#issuecomment-278527554 and https://github.com/spacetelescope/drizzlepac/issues/31#issuecomment-278529157, can we now close this issue?

**Comment by pllim** [comment]
When my cron job tells me the warnings are gone on the production side at 4PM, I'll close this.

**Comment by pllim** [comment]
Okay, I am satisfied.
