### ISSUE TITLE
3 unique AstroDrizzle errors for WFC3/IR when skymethod='match' 

### ISSUE THREAD

**Issue by mackjenn** [spacetelescope/drizzlepac#376]
MAST pipeline drizzle reprocessing failed for ~300/150,000 IR associations when changing skymethod from 'localmin' to 'match' in the MDRIZTAB reference file.  The WFC3 team requests that these be looked at by @mcara so that the remaining drizzled data products will be generated.

Datasets and a readme file have been provided for each type of error in the directories below with priority from highest to lowest:

**Error 1:  Perfect overlap between exposures in the ASN  (no dither or RPT-OBS)**
/user/mack/for_mihai/14074_error_perfect_overlap/ 

- File "/Users/mack/miniconda3/envs/astroconda/lib/python3.5/site-packages/spherical_geometry/graph.py", line 392, in _sanity_check
- assert len(node._edges) >= 2
- “No module named 'mpl_toolkits.basemap”

**Error 2: Overlap between some, but not all exposures in the ASN**
/user/mack/for_mihai/15153_error_some_overlap/ 

- "Keyword 'MDRIZSKY' not found."

**Error 3: No overlap between any exposures in the ASN    (only 1 dataset has this)**
/user/mack/for_mihai/15146_error_no_overlap/

- "Arrays cannot be empty"

**Comment by mackjenn** [comment]
I've tested the updates, and all 3 errors are resolved pending this change to sky.py 

#subtracted_sky     = skysubimage[extname,extver].header[skyKW]
subtracted_sky = skysubimage[extname, extver].header.get(skyKW, 0.)

**Comment by mcara** [comment]
@mackjenn Thank you for testing!
