### ISSUE TITLE
Missing colons before datatypes in variable names in docs

### ISSUE THREAD

**Issue by yotam-stsci** [spacetelescope/drizzlepac#377]
Very minor issue: All the variable names in the docs for the primary user interface (https://drizzlepac.readthedocs.io/en/latest/astrodrizzle.html) are missing a colon and some spaces between the variable name and datatype (e.g. "outputstr should be output : str"). This issue was not present in the deployment version.

**Comment by mcara** [comment]
It may be a minor issue but very annoying. It looks like this is caused by using `sphinx` version `2.0.0` and higher. I will specify in the requirements to use `sphinx<=1.8.5` using which the documentation seems to be rendered correctly.

**Comment by mcara** [comment]
Solved via #378
