### ISSUE TITLE
Use of mdriztab overwrites user specified parameter values

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/drizzlepac#386]
Testing of the use of AstroDrizzle() for single_visit mosaic generation uncovered a use-case where setting 'mdriztab=True' caused other parameters set on the command line to be ignored; specifically, final_rot.  This needs to be sorted out, since any user-specified parameter MUST take precedent at all times.

**Comment by s-goldman** [comment]
duplicated by [HLA-1209](https://jira.stsci.edu/browse/HLA-1209)
