### ISSUE TITLE
AstroDrizzle broken with astropy v1.3 

### ISSUE THREAD

**Issue by gbrammer** [spacetelescope/drizzlepac#40]
After updating astropy in an astroconda environment, AstroDrizzle now dies with the error:
`AttributeError: 'module' object has no attribute 'new_table'`.  The `astropy.io.fits.new_table` function was deprecated and removed as discussed [here](https://github.com/astropy/astropy/issues/5704).

**Comment by mcara** [comment]
@gbrammer Sorry for the late response. Drizzlepac itself does not use ``new_table`` anywhere, at least I do not think so. However, if I am wrong, could you, please, point to the location in the code where drizzlepac code uses ``new_table``?

On the other hand, our other packages do use ``new_table`` and I have tried to fix as many of them as I could find in https://github.com/spacetelescope/drizzlepac/issues/31#issuecomment-278470165 Did you update you astroconda packages to the latest versions?

It may have been that I have missed a couple of places where our code uses ``new_table``. If so, it would be helpful if you could post here the traceback that you are getting and also package versions.

Thanks!

**Comment by OlyDLG** [comment]
@gbrammer: may I ask which "astroconda environment"?

**Comment by mcara** [comment]
I am unable to reproduce the problem and without additional info from @gbrammer there is nothing much that I can do on this issue.
