### ISSUE TITLE
AstroDrizzle crashes when finalizing drizzle final product

### ISSUE THREAD

**Issue by NorPirzkal** [spacetelescope/drizzlepac#409]
When drizzling from FLT files, I get the following error.

File "/Users/npirzkal/anaconda3/envs/latestpy3/lib/python3.7/site-packages/drizzlepac/adrizzle.py", line 438, in updateInputDQArray
    np.bitwise_or(infile[dq_extn,chip].data,__bitarray,infile[dq_extn,chip].data)
TypeError: ufunc 'bitwise_or' output (typecode 'i') could not be coerced to provided output parameter (typecode 'H') according to the casting rule ''same_kind''

**Comment by mcara** [comment]
This is likely because you are using some sort of modified (non-standard) FITS files. Specifically, I suspect that you have modified FLT files to have `uint16` data type. Make sure DQ arrays are of type *signed* `int16`.

**Comment by mcara** [comment]
@NorPirzkal Was the issue solved? What was the cause.

**Comment by mcara** [comment]
Assuming the issue was solved, this ticket is being closed...
