### ISSUE TITLE
Why is Travis CI on?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#45]
There is not even a `.travis.yml` present. As a result, everything fails and it is misleading.

**Comment by jhunkeler** [comment]
@pllim I think Justin was implementing travis under the `deployment` branch so it was activated. I'll change it so it only runs when a `.travis.yml` exists.

**Comment by jhunkeler** [comment]
PS - Done.

**Comment by pllim** [comment]
Thanks!
