### ISSUE TITLE
AstroDrizzle should issue a warning when combine_type='minmed' for N>6 frames

### ISSUE THREAD

**Issue by mackjenn** [spacetelescope/drizzlepac#473]
An experienced in-house user tried to combine ~100 frames using AstroDrizzle with default parameters. This caused bad results due to setting combine_type='minmed'. Several members of WFC3 have requested that AstroDrizzle issue a warning to the user (on the screen and in the logfile) when drizzling N>6 frames. 

The following sentence from readthedocs should be highlighted in bold for more clarity, and it may also be used for the warning message: 
**“minmed” is highly recommended for three images, and is good for four to six images, but should be avoided for ten or more images.**

https://drizzlepac.readthedocs.io/en/latest/astrodrizzle.html

**Comment by stsci-hack** [comment]
Simple enough to fold in to the work we are currently doing on the drizzlepac package (see #476).

**Comment by stsci-hack** [comment]
Resolved by merging #476
