### ISSUE TITLE
Change debug to diagnostic

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/drizzlepac#500]
Rename the `--debug` command-line parameter for `runsinglehap` to be: `--diagnostic_mode` and `-d`.

The help text needs to be revised to better explain what processing this switch actually turns on; namely, pickle and regions files and such.

All use of the `debug` parameter in the code for SVM processing should be renamed as well to `diagnostic_mode`.  

The default value of this parameter should be `False`.

**Comment by dulude** [comment]
See PR #505!
