### ISSUE TITLE
Add log_level parameter to runsinglehap

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/drizzlepac#501]
A new parameter, `--log_level` and `-l`, should be added to the `runsinglehap` task to set the Python logging level to one of the pre-defined values: DEBUG, INFO, WARNING, ERROR, CRITICAL and so on. 

This parameter will then need to be used to reset the global Python logging level as the first operation in the `perform()` function, if defined by the user at the command line.

**Comment by s-goldman** [comment]
Looks like this work was completed in #506
