### ISSUE TITLE
Solution needed for SIGKILL generated during background computation of drizzled image

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/drizzlepac#507]
When running a number of poller files through the runsinglehap process, a number of datasets have failed due to a SIGKILL.  The meager output from strace is:

    sched_yield()                           = 0
    mmap(NULL, 440836096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f9146ad1000
    +++ killed by SIGKILL +++
    Killed

Note that SIGKILL cannot be caught as it is issued by the OS kernel so this issue will require some diagnosis.   The last log messages preceeding the SIGKILL are:

    INFO:drizzlepac.hapsequencer:Generating total product source catalogs
    INFO:drizzlepac.hlautils.catalog_utils:
    INFO:drizzlepac.hlautils.catalog_utils:Computation of image background - Input Parameters
    INFO:drizzlepac.hlautils.catalog_utils:File: hst_14990_03_wfc3_uvis_total_idoq03_drz.fits
    INFO:drizzlepac.hlautils.catalog_utils:Box size: 27
    INFO:drizzlepac.hlautils.catalog_utils:Window size: 3
    INFO:drizzlepac.hlautils.catalog_utils:Percentile in use: 10

Some datasets that can be used for this testing are: idoq03.out and jd8f16.out.

**Comment by mdlpstsci** [comment]
[brief_dmesg.txt](https://github.com/spacetelescope/drizzlepac/files/3860705/brief_dmesg.txt)

**Comment by mdlpstsci** [comment]
The `brief_dmesg.txt` generated on the VM (Linux) confirms the process ran out of memory.

**Comment by s-goldman** [comment]
@mdlpstsci Is this still a relevant issue?

**Comment by mdlpstsci** [comment]
@s-goldman 
I would say this is no longer an issue.  We, as well as DSB, have processed hundreds of poller files with runsinglehap.
