### ISSUE TITLE
Numpy loadtxt returns byte strings in update_from_shiftile

### ISSUE THREAD

**Issue by rjavila** [spacetelescope/drizzlepac#509]
Trying to run `drizzlepac.updatehdr.update_from_shiftfile` and saw the following error:

`updatehdr.update_from_shiftfile('xyshift',wcsname='xyshift')                                

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-29502af20f20> in <module>
----> 1 updatehdr.update_from_shiftfile('xyshift',wcsname='xyshift')

~/anaconda3/envs/scienv37/lib/python3.7/site-packages/drizzlepac/updatehdr.py in update_from_shiftfile(shiftfile, wcsname, force)
     96                 xsh=img['xsh'], ysh=img['ysh'],
     97                 xrms=img['xrms'], yrms=img['yrms'],
---> 98                 force=force)
     99 
    100 def updatewcs_with_shift(image,reference,wcsname=None, reusename=False,

~/anaconda3/envs/scienv37/lib/python3.7/site-packages/drizzlepac/updatehdr.py in updatewcs_with_shift(image, reference, wcsname, reusename, fitgeom, rot, scale, xsh, ysh, fit, xrms, yrms, verbose, force, sciext)
    238 
    239     # reset header WCS keywords to original (OPUS generated) values
--> 240     extlist = get_ext_list(image, extname='SCI')
    241     if extlist:
    242         if image_update:

~/anaconda3/envs/scienv37/lib/python3.7/site-packages/stsci/skypac/utils.py in get_ext_list(img, extname)
    438 
    439     """
--> 440     extver = get_extver_list(img=img, extname=extname)
    441     if extname is None:
    442         return extver

~/anaconda3/envs/scienv37/lib/python3.7/site-packages/stsci/skypac/utils.py in get_extver_list(img, extname)
    374         doRelease = True
    375     else:
--> 376         raise TypeError("Argument 'img' must be either a file name (string), "  \
    377                         "an ImageRef, or a `astropy.io.fits.HDUList` object.")
    378 

TypeError: Argument 'img' must be either a file name (string), an ImageRef, or a `astropy.io.fits.HDUList` object.`

Turns out the filenames are being returned as byte strings from np.loadtxt. I was able to fix this by changing line 77 in `updatehdr.py` from:

 fname_fmt = 'S{0}'.format(max(fnames))

to

 fname_fmt = 'U{0}'.format(max(fnames))

**Comment by s-goldman** [comment]
It looks like this was fixed in #448
