### ISSUE TITLE
Implement analyze for SVM processing

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/drizzlepac#517]
The analyze function 'analyze_data' needs to be called to remove input exposures from the single-visit processing poller files before instantiating the TDP/FDP/EDP instances.  The function 'poller_utils.build_poller_table' can be updated to call this when interpreting the original input file for SVM processing. 

Test dataset idt002 can be used to verify that this works as expected.

**Comment by mdlpstsci** [comment]
This issue has been fixed in PR#519.
