### ISSUE TITLE
Drizzle question

### ISSUE THREAD

**Issue by abhijithrajan** [spacetelescope/drizzlepac#52]
Hello, 

I have a question regarding the drizzlepac software. I have it installed via the astroconda package and would like to use the adrizzle function within drizzlepac to singly drizzle Keck NIRC2 data to correct distortion, where I have distortion correction images. The original drizzle function allowed the user to specify the following three parameters (I've found all the others that I need),

    ir.drizzle.coeffs, 
    ir.drizzle.xgeoim, and
    ir.drizzle.ygeoim 

When I run help for the adrizzle.drizzle task, it states that - 
Aside from the input parameters, this step requires:
    * valid input images with SCI extensions
    * valid distortion coefficients tables
    * any optional secondary distortion correction images

But it doesn't specify what keywords to use to assign them when running.

**Comment by mcara** [comment]
@abhijithrajan ``drizzlepac`` was designed to work with STScI data and it was never intended as a replacement for the ``drizzle`` task in IRAF's ``stsdas`` package.

It seems to me that your best bet would be to create your own "pixel maps" and then use functions from the https://github.com/spacetelescope/drizzle package.

CC: @bernie-simon @stsci-hack Any ideas?

**Comment by bernie-simon** [comment]
As Mihai says, the drizzle package was designed to make the drizzle algorithm available for images other than the HST. The only requirements are that the images should be in FITS format and have a valid world coordinate system (wcs). Although this version of drizzle uses a pixel map instead of a functional form to model the coordinate transformation, you don't need to worry about that. The pixel map is constructed from the wcs of the input and output images. Examples of how to use drizzle package are in the README file.

**Comment by mcara** [comment]
Another alternative is to use the original ``drizzle`` task from ``stsdas`` package in IRAF.

**Comment by abhijithrajan** [comment]
Thanks @mcara and @bernie-simon, the original drizzle task definitely still works, so I might just fall back to it. I'd like to give the drizzle task you pointed to and not have to depend on having IRAF installed. 

Unfortunately the Keck/NIRC2 data headers do not come populated with WCS information. And what I really want to accomplish is distortion correction using pre-generated distortion maps. Would I still be able to use drizzle without WCS information? Any suggestions on how I can generate the necessary pixel maps from the distortion fits files?

**Comment by mcara** [comment]
@nden Any ideas on how to convert ``drizzle``'s (from IRAF) ``xgeoim`` and ``ygeoim`` images to modern ``NPOLFILE`` and WCS?

**Comment by nden** [comment]
These files are supposed to store only small shifts. A proper WCS, and possibly a distortion model, is still needed.

**Comment by mcara** [comment]
Closing this issue due to both inactivity and due to the fact that it is not directly related to the ``drizzlepac``.
