### ISSUE TITLE
Sort SVM images before alignment

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/drizzlepac#521]
For SVM processing, the images in the poller file or input list should be sorted so the reference (first image) has a maximum number of potential sources.  The images be sorted in the following priority:
- redder filters with priority over bluer filters
- wider filters with priority over narrower filters
- longer exposures with priority over shorter exposures

Use FITS keywords photplam, photbw, and the exposure time for the algorithm.

**Comment by mdlpstsci** [comment]
Jen suggests
To determine which filter to align first, use the number of sources in each catalog. (This gives a simple way to approximate the combined effect of bandwidth, exposure time, and spectral energy distribution on the signal to noise for each observation).

**Comment by stsci-hack** [comment]
Sorting can be more precisely done by computing the intersection of the GAIA DR2 passband with a flat source spectrum computed for the observation based on PHOTFLAM, PHOTPLAM, PHOTBW and EXPTIME. 

-   The [GAIA DR2 passband](https://www.cosmos.esa.int/documents/29201/1645651/GaiaDR2_Revised_Passbands_ZeroPoints.zip/54db454f-69cb-ea0c-15be-f1b1f597f191) can be found online and added to the code as an parameter file. 
-   This intersection can be computed using [pysynphot's FlatSpectrum() for the observation](https://pysynphot.readthedocs.io/en/latest/spectrum.html#flat) and [pysynphot's custom spectrum tutorial for the GAIA DR2 passband](https://pysynphot.readthedocs.io/en/latest/tutorials.html#tutorial-10-spectrum-from-custom-text-file).

The count rate from this Composite spectrum can then be used as the primary sorting mechanism for observations taken in filters which overlap the GAIA passband.  For observations outside the GAIA passband (WFC3/IR, UV filters), the total integrated counts for the observations spectra sorted by distance from the central wavelength from the GAIA passband will need to be used instead.  This may simply be estimated as the area of the flat passband (PHOTFLAM*EXPTIME*PHOTBW) sorted by abs(delta(PHOTPLAM - GAIA_PEAK_LAMBDA)).

**Comment by stsci-hack** [comment]
Successful sorting of inputs will then be used to update the input poller list for creation of the total and filter products. 
The final alignment across all inputs will then need to be performed by adding code AFTER the current filter-by-filter alignment to gaia.  This new code will create a single input to tweakwcs which contains the WCS and source catalog for each input FLT/FLC file in the order established by the poller file.  Tweakwcs will then need to be run with 'enforce_user_order=True' and 'expand_refcat=True' to get a single WCS solution across all inputs/filters.  These updated WCS will then need to be passed back to the filter product list object and the total product meta_wcs will need to be regenerated using the 'generate_metawcs()' method.  The rest of the processing should then be able to continue without further modification using the now consistent WCS's.
