### ISSUE TITLE
Modify existing configuration files for SVM processing

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/drizzlepac#525]
WFC3/IR cfgs update → 
We would like to change skystat from 'mode' to 'median' in these files:
wfc3_ir_astrodrizzle_any_n2.json
wfc3_ir_astrodrizzle_any_n4.json
wfc3_ir_astrodrizzle_grism_n2.json
wfc3_ir_astrodrizzle_grism_n4.json

(Ref: Jen's confluence page https://innerspace.stsci.edu/display/hstdms/Astrometry+Testing)

**Comment by dulude** [comment]
issue resolved by PR #528.
