### ISSUE TITLE
New keywords for SVM products

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/drizzlepac#537]
A set of new keywords has been identified as being potentially useful for evaluating the single-visit products; namely, 

- Fraction of pixels with data
- Mean exposure time in the pixels with data
- Median exposure time in the pixels with data
- Mean number of exposures in the pixels with data
- Median number of exposures in the pixels with data

Names for these keywords which are FITS compliant need to be defined, and these values need to be computed based on `drizzlepac.hlautils.cell_utils` products.  The keywords will then need to be added to the PRIMARY header of the FILTER SVM products and TOTAL SVM product at the least, and perhaps also to the single EXPOSURE SVM products as well.

Additional keywords may still be identified for addition by INS as part of this development.

**Comment by nden** [comment]
Resolved in #569
