### ISSUE TITLE
Offsets due to HLA classic RA and Dec aren't in the same ref frame as HAP RA and Dec. are messing up  sourcelist comparisons in some cases

### ISSUE THREAD

**Issue by dulude** [spacetelescope/drizzlepac#544]
HLA classic RA and Dec aren't in the same ref frame as HAP RA and Dec. This can result in offsets between the two datasets that at can introduce an an new artificial source of error when comparing RA and dec values, and also interfere with the source matching process in compare_sourcelists.py

Rick has code to transform HLA classic RA/Dec into the HAP GAIA DR2 reference frame

- test and integrate Rick's code into compare_sourcelists.py.

**Comment by dulude** [comment]
see @dulude's [hla-544_transform_HLAClassic_to_HAP](https://github.com/dulude/drizzlepac/tree/hla-544_transform_HLAClassic_to_HAP) branch

**Comment by nden** [comment]
Resolved in #548
