### ISSUE TITLE
Finalize pass/fail criteria in compare_sourcelists.py

### ISSUE THREAD

**Issue by dulude** [spacetelescope/drizzlepac#572]
This issue stems from some of the unfinished todos from issue #556 that were not implemented in PR #571 .
* Known action items:
     - [x] Verify max_diff_dict values for _x, y_, combined ra & dec on-sky seperation, and _flag_ (initial values for all columns defined in PR #571) 
     - [x] Replace max_diff_dict placeholder values with actual values for _flux_inner, flux_outer, mag_inner, mag_outer, mag_inner_error, mag_outer_error, msky, stdev,_ and _ci_ (initial values for all columns defined in PR #571) 

* Possible additional to do items:
     - [ ] Values currently stored as a hard-coded dictionary in compare_sourcelists.py. It might be a good idea to instead store them in the configuration json files. They can be summoned from the config object in hapsequencer.run_sourcelist_comparision() and the dictionary can then be passed into compare_sourcelists.comparesourcelists() as a subroutine input.
     - [x] Are any of the pass/fail criteria instrument-dependant? If so, set up instrument-specific sets of pass/fail criteria sets (**NOT INSTRUMENT-DEPENDANT)**

**Comment by stsci-hack** [comment]
Resolved with #602 and subsequent work on this module.
