### ISSUE TITLE
SVM processing when no alignment to GAIA possible

### ISSUE THREAD

**Issue by mdlpstsci** [spacetelescope/drizzlepac#600]
If the alignment to GAIA is unsuccessful, what should we do?  We need to ensure the relative alignment is good.  If no HSC solution, perform relative alignment if possible or fall back on the pipeline produced results.

**Comment by stsci-hack** [comment]
The alignment code for SVM processing will only update the input exposures with a solution fit to GAIA when the fit to GAIA is successful.  In cases where alignment to GAIA is NOT possible, it will simply revert to the solution found in the initial pipeline alignment which will most likely be just the _a priori_ WCS.
