### ISSUE TITLE
Incorrect pixel center used when computing CRPIX

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#63]
As mentioned in https://github.com/spacetelescope/drizzlepac/issues/62, setting ``CRPIX`` to ``NAXIS/2`` is not really correct because the "center" is at the center of the pixel and not at its corner. The "center" issue is explained in https://fits.gsfc.nasa.gov/users_guide/users_guide/node52.html For example, if we have an image containing a single pixel, then the index of that pixel is at the center of the pixel and thus ``NAXIS/2`` would give 1/2=0.5 instead of 0 (using Python indexing). Secondly, FITS WCS is not using Python indexing but rather 1-based indexing so that the CRPIX of a single pixel image should be 1 instead of 0. Succinctly, _correct (for FITS WCS) formula for a CRPIX at the middle of an image_ should be: ``(NAXIS+1)/2``. This is also explained in section 2.1.4 of [Greisen & Calabretta 2002](https://www.aanda.org/articles/aa/pdf/2002/45/aah3859.pdf)

CC: @stsci-hack

**Comment by philhodge** [comment]
Unless CRPIX has a physical basis, it can be anywhere; it does not need 
to be at the center of a pixel.

In the case of a telescope and camera with a rotational axis of symmetry 
(not the only possibility, just an example), CRPIX should be the 
location where the optical axis crosses the detector, IF the optical 
axis is perpendicular to the surface of the detector.  The reason is 
that the simple distortion models (tangent projection, etc.) will give 
the best results with this choice.  This point could be determined by 
computing the plate solution, including some distortion terms.  It's 
very unlikely that CRPIX so determined would be at the center of a pixel.

There may well be a problem with drizzlepac if the CRPIX for the output 
image is not at the center of a pixel.  If so, I don't understand it, 
but I can't argue otherwise.  I'm only saying that, in general, there is 
no reason for CRPIX to be at the center of a pixel.

**Comment by mcara** [comment]
@philhodge wrote:
> *__Unless CRPIX has a physical basis,__ it can be anywhere; it does not need
to be at the center of a pixel.*

I agree with this [and everything else that follows - all good points].

Besides the physical basis, the correctness of the WCS is also important. This was partially explained in _"Succinctly, correct (for FITS WCS) formula for a **CRPIX at the middle of an image** should be: (NAXIS+1)/2"_ and I should have added to this **"... provided CRVAL is not adjusted accordingly"**.

Let me expand the above point in the context of drizzle and the user setting custom WCS parameters and I apologize if it looks too detailed but I do not know how to describe this better.

Let's say user drizzled a set of images creating ``output1.fits``. This image may have dimensions ``10,000x10,000`` and an off-center CRPIX=(800,800) - quite extreme but good for illustration purposes and the position of CRPIX can be arbitrary as you mention in your message. Now, let's assume user drizzles another set of images of the same object perhaps observed with a different filter and decides to: i) use ``output1.fits`` as a reference image so that second drizzle's output (``output2.fits``) is aligned to first drizzled image and ii) decide to drizzle to a smaller output size (e.g., ``2,000x2,000``). In that case, using existing code, the WCS for the ``output2.fits`` is identical to the WCS of the reference image (``output1.fits``) __except for *two*__ differences: ``_naxis1=_naxis2=2,000`` AND, more importantly, CRPIX will be set to ``NAXIS/2=1,000`` **without updating ``CRVAL``** and that is the problem. Let's say in ``output1.fits`` there was a star at position (1000,1000) using FITS indexing or (999,999) using Python indexing. Because of the convention that integer coordinates are at the centers of the pixels, this star should appear at coordinates (1000+1)/2=500.5 in ``output2.fits``. However, because our WCS has incorrect ``CRPIX`` (while keeping the same ``CRVAL``), this star will be mapped to the pixel (500,500) in the output image. That is, we introduce shifts of 1/2 pixel in the output image.

**Comment by mcara** [comment]
@philhodge wrote:
> *__Unless CRPIX has a physical basis,__ it can be anywhere; it does not need
to be at the center of a pixel.*

I agree with this [and everything else that follows - all good points].

Besides the physical basis, the correctness of the WCS is also important. This was partially explained in _"Succinctly, correct (for FITS WCS) formula for a **CRPIX at the middle of an image** should be: (NAXIS+1)/2"_ and I should have added to this **"... provided CRVAL is not adjusted accordingly"**.

Let me expand the above point in the context of drizzle and the user setting custom WCS parameters and I apologize if it looks too detailed but I do not know how to describe this better.

Let's say user drizzled a set of images creating ``output1.fits``. This image may have dimensions ``10,000x10,000`` and an off-center CRPIX=(800,800) - quite extreme but good for illustration purposes and the position of CRPIX can be arbitrary as you mention in your message. Now, let's assume user drizzles another set of images of the same object perhaps observed with a different filter and decides to: i) use ``output1.fits`` as a reference image so that second drizzle's output (``output2.fits``) is aligned to first drizzled image and ii) decide to drizzle to a smaller output size (e.g., ``1,000x1,000``). In that case, using existing code, the WCS for the ``output2.fits`` is identical to the WCS of the reference image (``output1.fits``) __except for *two*__ differences: ``_naxis1=_naxis2=1,000`` AND, more importantly, CRPIX will be set to ``NAXIS/2=500`` **without updating ``CRVAL``** and that is the problem. Let's say in ``output1.fits`` there was a star at position (800,800) using FITS indexing or (799,799) using Python indexing. Because of the convention that integer coordinates are at the centers of the pixels, this star should appear at coordinates (1000+1)/2=500.5 in ``output2.fits``. However, because our WCS has incorrect ``CRPIX`` (while keeping the same ``CRVAL``), this star will be mapped to the pixel (500,500) in the output image. That is, we introduce shifts of 1/2 pixel in the output image.

**Comment by mcara** [comment]
@philhodge To summarize previous point in context of your comment https://github.com/spacetelescope/drizzlepac/issues/63#issuecomment-299456230...
1. When talking in the context of a "real" (=observed) image as it comes out of the detector (i.e., FLT images), ``CRPIX`` should be as close to the optical axis as possible as you mention: _"The reason is that the simple distortion models (tangent projection, etc.) will give the best results with this choice.  This point could be determined by computing the plate solution, including some distortion terms.  It's very unlikely that CRPIX so determined would be at the center of a pixel."_
2. When talking in the context of a drizzled image previous point is irrelevant since drizzle essentially re-maps ("re-projects", etc.) input to a different grid and so ``CRPIX`` can be set anywhere **as long as ``CRVAL`` is adjusted accordingly** otherwise this will result in incorrect celestial positions of the objects in the image. That is, **``CRPIX`` cannot be set arbitrarily if ``CRVAL`` is fixed**.

**Comment by philhodge** [comment]
I don't agree.  If crpix = (800, 800) and the star's centroid is at 
(800, 800), then the star's right ascension and declination are crval1 
and crval2.  If you make another image with crpix set to (500.5, 500.5), 
then you have to put the star at pixel (500.5, 500.5).  Yes, the star is 
now at the corner instead of the center of a pixel.  That doesn't matter 
at all; you'll get the correct right ascension and declination of the 
star via the WCS.  It has nothing to do with whether the center of a 
pixel has integer coordinates; whatever convention you use, just be 
consistent.  If the star is at crpix, its right ascension and 
declination will be crval.  If you put the star somewhere else, you will 
get the wrong coordinates.

"... this star will be mapped to the pixel (500,500) in the output image."
I don't understand that at all.  If a star's coordinates are equal to 
the values in crval, the star's centroid has to be at crpix.  If not, 
you've put the star in the wrong place.

**Comment by mcara** [comment]
> Yes, the star is now at the corner instead of the center of a pixel.  That doesn't matter at all; you'll get the correct right ascension and declination of the star via the WCS.

This is true for this particular example unless I actually **expect** to see the star exactly in the middle but I get it shifted by 1/2 pixels. Then it is important. Last sentence in my previous comment should have been: _"That is, ``CRPIX`` cannot be set arbitrarily if ``CRVAL`` is fixed"_ **without getting shifts in drizzled images**.

The point here is that if you think of a single image not in context of ``astrodrizzle`` then changing ``CRPIX`` without adjusting ``CRVAL`` would result in WCS errors. However, if this image now serves as a reference image to ``astrodrizzle`` then drizzle will produce a shifted image. You said: _"It has nothing to do with whether the center of a pixel has integer coordinates; **whatever convention you use, just be consistent**."_ That is the point: FITS WCS uses a different convention from our software!

Let me modify my example that will show this from a different perspective... Let's say user has an image from Spitzer of size 1000x1000 with a star exactly at position (500.5, 500.5). Let's also assume that whatever software was used, it set CRPIX at the center of the image using FITS WCS convention: (500.5, 500.5). If user now drizzles some HST images AND provides this Spitzer image as a reference image AND decides to provide some custom WCS parameters, i.e., by specifying ``outnx`` and ``outny`` to be exactly 1000 as in the reference image, then our code in ``mergeWCS()`` would change ``CRPIX`` of the output WCS to be (500, 500) without changing ``CRVAL`` and then using this WCS to drizzle input to the output grid and this will result in a shifted image.

**Comment by philhodge** [comment]
OK, yes; I understand now.  The star would be at (500, 500), if that's what you set crpix to.  Thanks for the clarification.  You'll still compute the correct right ascension and declination for objects in the image, however.

FITS WCS does not have the convention of setting crpix to outn[xy] // 2.  The default for crpix is 0.

If the user specifies some output WCS parameters but not others, why not keep all the other WCS parameters the same as in the reference image?  If the output image is a different size from the reference image, it would make sense to change crpix, but why not leave that up to the user?  You could populate the menu for output WCS parameters with default values (and maybe show the values in the reference image as well), so the user would know what to expect.  If crpix in the reference image is 379.1762, and drizzle creates a value based on (outnx + 1) // 2, the output will be shifted with respect to the input.

What if the reference image is 1000 x 1000 in size and crpix = 20000?  If the output image is 1000 x 1000 and drizzle sets crpix to 500, is that really what you want?

**Comment by mcara** [comment]
> If the user specifies some output WCS parameters but not others, why not keep all the other WCS parameters the same as in the reference image?

Correct! That is what I am trying to do (=not change projection's center) while working on https://github.com/spacetelescope/drizzlepac/issues/62 and now I think if I fix https://github.com/spacetelescope/drizzlepac/issues/62 it may fix this issue as well (at least, most of it). Currently, if user sets scale or rotation then this automatically triggers setting CRPIX to the "center" (minus 1/2). Setting ``outnx`` also triggers re-computation of ``CRPIX`` to ``outnx/2``. This would be correct if we want to the output image to be a "crop" of size (outnx, outny) "centered" on the CRPIX of the reference image (except this "centering" is off by 1/2 pix shift that we currently get).

> If the output image is a different size from the reference image, it would make sense to change crpix, but why not leave that up to the user?

That's great except for https://github.com/spacetelescope/drizzlepac/issues/64 which needs to be fixed as well.

**Comment by mcara** [comment]
Solved in https://github.com/spacetelescope/drizzlepac/pull/65
