### ISSUE TITLE
Need updates to DGEO warning message

### ISSUE THREAD

**Issue by samanthalh** [spacetelescope/drizzlepac#644]
Hello! I'm working on a WFPC2 DrizzlePac ticket (INC0154128, for reference) and the user asked about the lengthy warning message below. I feel this needs to be updated for two reasons: 1) it provides users with an IRAF hedit command, and IRAF is deprecated, and 2) it should explain that for WFPC2 and other archival instruments, it is **fine** and **expected** to type 'c' and continue running drizzle. I don't believe that's clear at that moment. Thanks!!

> 
> A 'DGEOFILE' keyword is present in the primary header but 'NPOLFILE' keyword was not found.
> This version of the software uses a new format for the residual distortion DGEO files.
> Please consult the instrument web pages for which reference files to download.
> A small (new style) dgeofile is needed ('_npl.fits' extension) and possibly a
> detector to image correction file ('_d2i.fits' extension).
> The names of these files must be added to the primary header either using the task XXXX
> or manually, for example:
> 
> hedit u2pq0505t_c0m.fits[0] npolfile fname_npl.fits add+
> hedit u2pq0505t_c0m.fits[0] d2imfile fname_d2i.fits add+
> 
> where fname_npl.fits is the name of the new style dgeo file and fname_d2i.fits is
> the name of the detector to image correction. After adding these keywords to the
> primary header, updatewcs must be run to update the science files:
> 
> from stwcs import updatewcs
> updatewcs.updatewcs("u2pq0505t_c0m.fits")
> 
> Alternatively you may choose to run astrodrizzle without DGEO and detector to image correction.
> 
> To stop astrodrizzle and update the dgeo files, type 'q'.
> To continue running astrodrizzle without the non-polynomial distortion correction, type 'c':

**Comment by stsci-hack** [comment]
@samanthalh Please check out #647 to see whether this will make the warning more appropriate for the users.

**Comment by stsci-hack** [comment]
Resolved with #647 on 22-Apr-2020.
