### ISSUE TITLE
use interpret_bit_flags from astropy.nddata.bitmask

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/drizzlepac#649]
These imports

https://github.com/spacetelescope/drizzlepac/blob/6d681f8d5d8fb94dcf4c46231dfd52b318e8d244/drizzlepac/sky.py#L17-L19

https://github.com/spacetelescope/drizzlepac/blob/5b993df3a7d5f65a41bc585dcb1499901038b25b/drizzlepac/processInput.py#L45-L48

https://github.com/spacetelescope/drizzlepac/blob/c655ccd8ebe5af5b46bc7bace316fbc12dbabbac/drizzlepac/imgclasses.py#L29-L32

https://github.com/spacetelescope/drizzlepac/blob/fe7004e66952ffc5dff5c1caaef46e0265af3ccc/drizzlepac/resetbits.py#L70-L73

should now be

```
from astropy.nddata.bitmask import interpret_bit_flags
```

This has been available since `astropy 3.1`.

**Comment by stsci-hack** [comment]
Closed with #665 being merged.
