### ISSUE TITLE
SVM Q&A: Generate plots for cross-filter comparisons

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#703]
_Issue [HLA-382](https://jira.stsci.edu/browse/HLA-382) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Summary plots should be generated for the cross-filter point-source catalog comparisons generated in HLA-381.  The set of plots to be generated should include (at a minimum) a plot of delta_X vs delta_Y for each filter relative to the filter with the most sources along with a summary plot of the RMS(delta_X) vs RMS(delta_Y), mean(delta_X) vs mean(delta_Y) and other stats as well.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-382?focusedCommentId=474726#comment-474726):_

development branch url: <https://github.com/dulude/drizzlepac/tree/HLA-382_interfilter_crossmatch_graphics](https://github.com/dulude/drizzlepac/tree/HLA-382_interfilter_crossmatch_graphics)>

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-382?focusedCommentId=475319#comment-475319):_

See [PR #&#x2060;741](https://github.com/spacetelescope/drizzlepac/pull/741)

**Comment by stsci-hack** [comment]
Resolved with #741 on 21-Jul-2020.
