### ISSUE TITLE
Define conditions under which the RickerWavelet2DKernel should be used

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#704]
_Issue [HLA-383](https://jira.stsci.edu/browse/HLA-383) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Rick White has researched when one should switch between source detection kernels for use with the Segmentation algorithms. Use Rick's discussion found at the following URL as a cookbook for identifying crowded fields and incorporate Rick's seg_rejection2.py for the actual initial evaluation.

<https://innerspace.stsci.edu/display/HLA/Strategy+for+switching+SExtractor+kernels+for+crowded+fields>

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-383?focusedCommentId=475604#comment-475604):_

Asked Rick for some background on the empirical choices for the parameter values.  Working with Rick's code standalone to generate reference output. Integrated his code as method of the HAPSegmentCatalog and testing against standalone module.

Note: MexicanHatKernel is RickerWavelet2DKernel in astropy.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-383?focusedCommentId=475792#comment-475792):_

Comparison testing to ensure the standalone version of the algorithm and the code incorporated into the SVM code base produce the same output given, effectively, the same input.  This was successful.  It should be noted there still needs to be a thorough evaluation of the parameters which control the determination of crowding.  These values should be in the catalog_utils configuration files which are instrument/detector specific.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-383?focusedCommentId=477313#comment-477313):_

Code implemented and Git PR #&#x2060;756 approved and merged on 30 July 2020.

**Comment by stsci-hack** [comment]
Code implemented and Git PR #⁠756 approved and merged on 30 July 2020.
