### ISSUE TITLE
Modify Segmentation algorithm for SVM to incorporation a RickerWavelet2DKernel

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#705]
_Issue [HLA-384](https://jira.stsci.edu/browse/HLA-384) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Rework the current Segmentation algorithm to incorporate the use of a Mexican Hat kernel, if is deemed the Gaussian kernel is inappropriate for the field of view.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-384?focusedCommentId=477314#comment-477314):_

Code implemented and Git PR #&#x2060;756 approved and merged on 30 July 2020.

**Comment by stsci-hack** [comment]
Resolved with #756 (on 30-Jul-2020).
