### ISSUE TITLE
adrizzle.py needs to import stwcs.wsutil

### ISSUE THREAD

**Issue by npirzkal** [spacetelescope/drizzlepac#710]
Line 159 of adrizzle.py calls wcsutil() but it is never imported.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-385](https://jira.stsci.edu/browse/HLA-385)._

**Comment by stsci-hack** [comment]
Fixed in #712.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-385?focusedCommentId=473430#comment-473430):_

Fixed in PR #&#x2060;712 by using the same syntax for that line as already used in previous calls to that module.
