### ISSUE TITLE
Automatic PyPI publication enabled

### ISSUE THREAD

**Issue by rendinam** [spacetelescope/drizzlepac#717]
When making final, public releases of this software please use the Github release feature (https://github.com/spacetelescope/drizzlepac/releases/new). This will trigger the build and upload of the corresponding package at the tag specified to PyPI.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-386](https://jira.stsci.edu/browse/HLA-386)._

**Comment by stsci-hack** [comment]
Resolved with #716.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-386?focusedCommentId=606104#comment-606104):_

Resolved via [Drizzlepac PR #&#x2060;716](https://github.com/spacetelescope/drizzlepac/pull/716).
