### ISSUE TITLE
pembry public test failure

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#72]
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=104227551

**Comment by mcara** [comment]
@pllim Thanks. I will look into it.

**Comment by mcara** [comment]
@pllim @jhunkeler It is interesting that my "check your tests" e-mail looks like this:
```
nott dev
=======
drizzlepac
    Pass: 74     Fail: 0      Error: 0      Disable: 0      Missing: 0  
hstcal
    Pass: 184    Fail: 12     Error: 0      Disable: 2      Missing: 0      (FIX ME)
stsci_python
    Pass: 200    Fail: 2      Error: 4      Disable: 14     Missing: 0      (FIX ME)
stsdas
    Pass: 18     Fail: 0      Error: 0      Disable: 12     Missing: 0  

nott public
=======
drizzlepac
    Pass: 73     Fail: 1      Error: 0      Disable: 0      Missing: 0      (FIX ME)
hstcal
    Pass: 73     Fail: 99     Error: 24     Disable: 2      Missing: 0      (FIX ME)
stsci_python
    Pass: 188    Fail: 16     Error: 0      Disable: 16     Missing: 0      (FIX ME)
stsdas
    Pass: 18     Fail: 0      Error: 0      Disable: 12     Missing: 0  
```

First of all, this e-mail does not include any info about ``pembry`` but more interestingly, it shows that public ``nott`` is failing while in reality it is public ``pembry`` that is failing:

![screen shot 2017-07-06 at 4 25 29 pm](https://user-images.githubusercontent.com/5985250/27931383-12b51c40-6268-11e7-879b-6bbbfddf08b3.png)

**Comment by mcara** [comment]
okified.

**Comment by pllim** [comment]
I just added pembry to email today. You'll see it tomorrow. Again, the email reports results from "last night". You're looking at today's results, which might not be the same anymore.

**Comment by mcara** [comment]
@pllim No, the test was failing for quite some time (it is one of the tests that I missed somehow to okify). But it is reported as failing on nott and not on pembry (in the e-mail)

**Comment by pllim** [comment]
Report from last night seems fine this morning (with that one failure that you have since fixed):
```
nott dev
=======
drizzlepac
    Pass: 37     Fail: 0      Error: 0      Disable: 0      Missing: 0  

nott public
=======
drizzlepac
    Pass: 37     Fail: 0      Error: 0      Disable: 0      Missing: 0  

pembry dev
=======
drizzlepac
    Pass: 37     Fail: 0      Error: 0      Disable: 0      Missing: 0  

pembry public
=======
drizzlepac
    Pass: 36     Fail: 1      Error: 0      Disable: 0      Missing: 0      (FIX ME)
```
