### ISSUE TITLE
MVM: Add alignment verification to MVM processing

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#730]
_Issue [HLA-390](https://jira.stsci.edu/browse/HLA-390) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Standard pipeline processing of separate associations relies on a few types of verification to assess whether or not the alignment has been corrupted by each of the available WCS solutions.  Some of this verification should be implemented as part of the MVM processing to insure that the alignment did not get skewed by erroneous sources or did not result in fits which eliminate the relative alignment of the input images being combined into the sky cell mosaic.  

Implementation of any verification steps will require modifying the workflow within the sequencer to account for failures of the alignment.  Plans should be made for such failures, based on what alignment steps are implemented.  Such changes will require modifying how the alignment gets done to attempt to recover from recognizable failure modes, if possible.

Open questions remain as to whether this alignment should span the multiple layers for each sky cell and if so, what layers should be included in this alignment since some fields may not be alignable over the lifetime of a detector due to proper motions. 

Completion Criteria:
 * Logic gets implemented that allows for successful verification of image alignment
 * Logic gets implemented that results in successful handling of alignment failure cases; successful in the sense that the sky cell gets produced without the mis-aligned WCS and the user has a way to recognize the situation. 
 * MVM processing can verify successful alignment of the images in a single sky cell for a majority (>70%?) of the sky cell layers. 
 ** Exact criteria for overall success will need to be provided by INS after evaluating the results for multiple sky cells they identify as test cases.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-390?focusedCommentId=606119#comment-606119):_

Alignment of input exposures to MVM products was not implemented and probably will not be implemented.  MVM products will rely exclusively on SVM processing for alignment in order to better handle proper motion of the sources in the exposures over time.

**Comment by nden** [comment]
Jira ticket was cancelled. Closing
