### ISSUE TITLE
MVM: Generate Q&A results for MVM products

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#731]
_Issue [HLA-391](https://jira.stsci.edu/browse/HLA-391) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

A key aspect of insuring that the MVM processing works as desired is having test results readily accessible that demonstrate the quality of the MVM drizzle products.  Tests should be defined and implemented for MVM processing in much the same manner as was done for SVM processing.  These tests should provide analysis of the alignment to GAIA, alignment across the layers of the sky cell, and the photometry across layers of the sky cell.  It is expected that only a minimal set of tests should be developed initially to provide the most basic evaluation of the MVM products possible and to develop an understanding of what data can be extracted from the MVM products for Q&A results.

Completion Criteria:
 * JSON files can be generated (when run in debug mode) containing an initial, minimal set (not final complete set) of Q&A results.
 ** One set should of results should include some measure of the astrometry
 ** Another set should report of the photometry (for a future ticket)

**Comment by stsci-hack** [comment]
Resolved with #1396 and #1408.
