### ISSUE TITLE
MVM: Generate Q&A plots for MVM products

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#732]
_Issue [HLA-392](https://jira.stsci.edu/browse/HLA-392) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

A basic set of Bokeh-based plots should be generated based on Q&A JSON files that were created in HLA-391.  

Completion Criteria:
 * A set of HTML files with the plots gets generated for all the available MVM Q&A JSON files.

**Comment by stsci-hack** [comment]
Resolved with #1396 and related subsequent PRs.
