### ISSUE TITLE
SVM Q&A: Update WCS graphics to use latest API

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#735]
_Issue [HLA-393](https://jira.stsci.edu/browse/HLA-393) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Update the SVM Q&A plots related to the WCS statistics to use the latest version of the plotting API developed.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-393?focusedCommentId=475157#comment-475157):_

The routine has been updated and integrated into the svm_quality_graphics.py module.  It is out for review: git PR#&#x2060;738.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-393?focusedCommentId=475305#comment-475305):_

PR#&#x2060;738 approved and merged on 21 July 2020.

**Comment by stsci-hack** [comment]
PR#⁠738 approved and merged on 21 July 2020.
