### ISSUE TITLE
SVM Q&A: Finish cross-match plot update to latest API

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#736]
_Issue [HLA-394](https://jira.stsci.edu/browse/HLA-394) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Update the plotting in 'build_svm_plots' so that all plots are generated and use the latest API.  This may also require debugging the histogram generation based on test results with dataframe 'results_2020-06-17_svm_qa_all.h5'.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-394?focusedCommentId=475280#comment-475280):_

Work was completed when [DrizzlePac PR 739](https://github.com/spacetelescope/drizzlepac/pull/739) was merged.  The new code was used to generate an initial set of new plots based on the single-visit test results from 'results_2020-07-09', and were posted at <https://ssb.stsci.edu/hack/astrometry/testing/svm_results_2020-07-09/> along with the master file used as the basis for the plots.

**Comment by stsci-hack** [comment]
Resolved with #739 (on 21-Jul-2020).
