### ISSUE TITLE
SVM Q&A: Help DSB generate test results 

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#737]
_Issue [HLA-395](https://jira.stsci.edu/browse/HLA-395) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Meet with DSB to discuss how to generate harvested results and HTML plots in the pipeline testing environment.

**Comment by stsci-hack** [comment]
Provided demo for DSB on how to run:

- diagnostic_json_harvester.json_harvester()
- pipeline_graphics.build_astrometry_plots()
- svm_quality_graphics.build_svm_plots()

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-395?focusedCommentId=476831#comment-476831):_

Provided demo of how to run the JSON harvester from haputils.diagnostic_json_harvester and both the pipeline graphics as well as the SVM graphics generators from within the ipython command-line.  

Recent upgrades to the code (specifically, merging PR #&#x2060;723) changed the naming convention and API in use for the harvester for pipeline astrometry JSON file generation.  As a result, DSB had to wait until the delivery of 2020.4rc2 in order to run the code through completion.
