### ISSUE TITLE
Error when aligning FITS files to Ref Catalog

### ISSUE THREAD

**Issue by wwaldron** [spacetelescope/drizzlepac#74]
[ESO_Guide_Star_Coords_J2000.txt](https://github.com/spacetelescope/drizzlepac/files/1185983/ESO_Guide_Star_Coords_J2000.txt)

I have 4 FITS files that I am trying to align to a reference catalog. After tweakreg has found the sources in each image and moves its focus to the reference catalog, I get an error in drizzlepac/catalogs.py which says: TypeError: 'NoneType' object has no attribute '__getitem__'. This error occurs on line 263. I did nothing in regards to setting the flux limits so I do not know why the program entered the 'if' statement to begin with. I've attached the reference catalog I am using.

**Comment by mcara** [comment]
@wwaldron Replace commas with white space (space, tab, etc.) in your reference catalog file.

**Comment by mcara** [comment]
Updated documentation to include white-space separation requirement for catalog files in https://github.com/spacetelescope/drizzlepac/pull/75
