### ISSUE TITLE
SVM Q&A: Develop command-line interface for pipeline graphics

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#750]
_Issue [HLA-398](https://jira.stsci.edu/browse/HLA-398) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Command-line interfaces for the harvester and SVM plots already exist, but it would be helpful for pipeline use of the code in testing to have a command-line interface for generating the pipeline graphics as well, much like the interface found in 'svm_quality_graphics.py'.

**Comment by stsci-hack** [comment]
Resovled with #768.
