### ISSUE TITLE
PIPELINE and SVM Q&A: Capture exceptions generated by the PIPELINE and SVM quality analysis routines

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#751]
_Issue [HLA-399](https://jira.stsci.edu/browse/HLA-399) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Surround each PIPELINE and SVM quality analysis test with a try/except block.  In case of failure in the analysis, this should not cause the overall processing to abort.  At this stage all the important image/data processing has already completed.  If an analysis test fails, the analysis should "move on" as appropriate (e.g., another dataset or another test).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-399?focusedCommentId=478623#comment-478623):_

See [PR # 762](https://github.com/spacetelescope/drizzlepac/pull/762)

**Comment by stsci-hack** [comment]
Resolved with #762.
