### ISSUE TITLE
PIPELINE and SVM Q&A: Capture exceptions generated by the PIPELINE and SVM quality graphics routines

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#752]
_Issue [HLA-400](https://jira.stsci.edu/browse/HLA-400) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Surround each graphics routine with a try/except block. In case of failure in a particular graphics routine, this should not cause the overall graphics generation to abort. If a graphics routine fails, the driver should "move on" to the next graphics routine.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-400?focusedCommentId=478845#comment-478845):_

See [PR #&#x2060;763](https://github.com/spacetelescope/drizzlepac/pull/763)

**Comment by stsci-hack** [comment]
Resolved with #763.
