### ISSUE TITLE
Tune RickerWavelet scaling factors

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#757]
_Issue [HLA-401](https://jira.stsci.edu/browse/HLA-401) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The RickerWavelet algorithm has been implemented to handle crowded fields.  A number of factors drive the algorithm which may well be instrument/detector-dependent.  Placeholder values have been put into the HAP configuration files, but the values need to be refined.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-401?focusedCommentId=483239#comment-483239):_

List of visit names provided by Rick used for testing and tuning the RickerWavelet algorithm:

HLA      Dataset                   HAP

G2RW  hst_9793_43_acs - examined, RW (WFC and HRC)
RW       hst_9973_4a_acs 
G           hst_10332_20_acs - examined, Gaussian
RW        hst_10775_32_acs
G2RW   hst_11700_2o_wfc3 - examined,  RW 
RW        hst_12206_02_wfc3
RW        hst_12254_02_acs
RW        hst_12445_8p_wfc3  - examined, RW (UVIS and IR)
G2RW   hst_12445_9e_wfc3 - examined, RW (UVIS and IR)
G           hst_12459_a4_wfc3  - examined, Gaussian
RW        hst_12576_52_wfc3
G2RW   hst_12911_08_acs - examined, should switch to RW (did not), bkg too low?
G           hst_12939_1y_acs - examined, Gaussian
RW        hst_12979_02_wfc3

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-401?focusedCommentId=483249#comment-483249):_

Dataset hst_10775_32_acs will be reviewed to evaluate performance of current RW implementation compared to default source identification method.

**Comment by stsci-hack** [comment]
Fixed with #810 (on 23-Sep-2020) and #895.
