### ISSUE TITLE
SVM: Investigate scale of alignment issues in SVM processing

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#758]
_Issue [HLA-402](https://jira.stsci.edu/browse/HLA-402) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

HLA-377 seeks to address issues with aligning SVM products that come up during processing.  Unfortunately, there have been no statistics yet on how well the SVM products are aligned, so it is not clear how serious or critical a problem we have with aligning SVM inputs.  An investigation needs to be undertaken to quantify in at least a couple of ways how many problems there are in SVM processing related to mis-aligned or poorly aligned products.

This investigation should be strictly limited to information that is readily available; namely,
* Tracebacks from SVM processing as documented on hlalab1 in  /home/hack/qa_dev/svm_results_2020-07-29_err.log.
* Filter-to-filter alignment comparisons generated as interfilter comparison JSON files from the singlevisits/results_2020-07-28 test on hlalab1 
    * master file already available at  <https://ssb.stsci.edu/hack/astrometry/testing/svm_results_2020-07-28/svm_results_2020-07-28_svm_qa_all.h5>

Results of this analysis should provide:
* percent of visits which can NOT be aligned as a visit (all filters to the same WCS) 
* mean and stddev of filter-to-filter alignment across each visit
* percent of filter-to-filter alignment offsets which exceed a limit deemed to affect the science (0.1pixels?? 0.25 pixels?? 1 pixel??) [Need to discuss with INS]
* confirmation that filter-to-filter misalignment results in poor mosaics or poor comparisons of images across the filters in the visit
    * this will require visual evaluation of images from visits which show both poor alignment and good alignment to confirm what the plots report
    * this confirmation only needs to be done for a small sample of well aligned visits and poorly aligned visits, not an exhaustive analysis

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-402?focusedCommentId=482220#comment-482220):_

RESULTS
Crossmatched interfilter mean separation value breakdown:
n = 383
percent less than 0.1 pixels: 68.9295039164491%
percent less than 0.5 pixels: 94.7780678851175%
percent less than 1.0 pixels: 97.65013054830287%
percent greater than or equal to than 1.0 pixels: 2.3498694516971277%

**Comment by stsci-hack** [comment]
Analysis completed on 1-Sep-2020.
