### ISSUE TITLE
[TEST] ImportError no module named calc_pixmap

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#76]
While combing through pandokia back-end logs, I saw this and it is not reported in the daily reports because pandokia cannot pick up such things (don't ask me why).

https://ssb.stsci.edu/steuermann/steuermann.cgi?action=log&name=conda_tests_2017-07-30-10:30:02/nott:conda_testing/dev_tests

```
COMMAND : 'pdknose --pdk --with-doctest --doctest-tests test_pixmap.py' (for file /srv/rt/betadrizzle/unit/test_pixmap.py) 2017-07-30 10:38:23.180210
E
======================================================================
ERROR: Failure: ImportError (No module named calc_pixmap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/iraf/bldtmp/pGNj/p/envs/dev/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/srv/iraf/bldtmp/pGNj/p/envs/dev/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/srv/iraf/bldtmp/pGNj/p/envs/dev/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/srv/rt/betadrizzle/unit/test_pixmap.py", line 20, in <module>
    from drizzlepac.calc_pixmap import calc_pixmap
ImportError: No module named calc_pixmap

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
return from wait, status= 1
COMMAND EXIT: exit 0 2017-07-30 10:38:25.586787
pass=0 fail=0 error=0
```

**Comment by mcara** [comment]
@pllim It's hard to fix something that never worked. I have a feeling this test was designed ahead of ``calc_pixmap`` being implemented in ``drizzlepac``. ``calc_pixmap`` was never in the ``drizzlepac`` and most likely @stsci-hack please confirm, this test was designed for the "new and improved" drizzle module https://github.com/spacetelescope/drizzle/blob/master/drizzle/calc_pixmap.py#L5 and not for the ``drizzlepac``. I would suggest that you simply delete this test file from the repository.

**Comment by pllim** [comment]
Who works on the "drizzle"? Should this test be moved instead of deleted? Please discuss amongst yourselves and reach a consensus.

**Comment by mcara** [comment]
Feel free to contact @bernie-simon

**Comment by stsci-hack** [comment]
That test can probably be moved to support JWST drizzle code use, and deleted from the drizzlepac test environment.

**Comment by pllim** [comment]
If it is going to be moved, obviously it cannot be deleted *before* the move. Please let me know when the move is complete. Thanks!

**Comment by mcara** [comment]
@stsci-hack @pllim These "pixmap" tests seem to have been moved to the ``drizzle`` package (see https://github.com/spacetelescope/drizzle/blob/master/drizzle/tests/test_pixmap.py) by @bernie-simon around 3 years ago (or so). I think it is safe to nuke this test from pandokia.

**Comment by bernie-simon** [comment]
I've got no idea how the this test got into drizzlepac, it belongs on my iteration of the drizzle library. And yes, it's already there.

**Comment by pllim** [comment]
I removed the test. Unfortunately, I also accidentally updated two other modified files. I don't know how to undo the latter, so the best I could do is go into the other trees and did a "svn update" and resolved conflicts as "mc". Hope that worked. Sorry for any inconvenience caused.
```
--- r1643
D    test_pixmap.py
M    data/reference_lanczos_grid.fits
M    data/difference_lanczos_grid.txt
```

**Comment by mcara** [comment]
> Unfortunately, I also accidentally updated two other modified files. I don't know how to undo the latter, so the best I could do is go into the other trees and did a "svn update" and resolved conflicts as "mc". Hope that worked.

@stsci-hack @jhunkeler Is that OK? Can you verify, please?
