### ISSUE TITLE
Investigate problems found in SVM testing 

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#767]
_Issue [HLA-404](https://jira.stsci.edu/browse/HLA-404) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Matt reported these results from the latest test run from 15-Aug-2020:

Science Visits
	Successfully processed: 1181
	Failed processing: 8
	No Output Status Reported: 21
I’ve sent the ones that failed to Warren, Michele, and Mike.

These failures need to be reviewed and debugged.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-404?focusedCommentId=479899#comment-479899):_

A review of all the exceptions reported in the 2020-08-13 test results uncovered a few basic modes of failure; namely,

ib2t06/HAP_ib2t06.err:Traceback (most recent call last)
  - Empty data: no catalogs generated

  -   File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/astrometric_utils.py", line 742, in extract_sources
          num_brightest = 10 if len(segm.areas) > 10 else len(segm.areas)
      AttributeError: 'NoneType' object has no attribute 'areas'

  -   File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/catalog_utils.py", line 1709, in _seg_rejection
          nbins = segm_img.max_label
      AttributeError: 'NoneType' object has no attribute 'max_label'


ib8c5k/HAP_ib8c5k.err:Traceback (most recent call last):
  - Network problems during processing


icmo02/HAP_icmo02.err:Traceback (most recent call last):
  - not all data was available/present for processing


idnm0u/HAP_idnm0u.err:Traceback (most recent call last):
  - Problem with skymatch 
    File "/ifs/archive/dev/processing/hla/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/stsci/skypac/region.py", line 226, in <listcomp>
        x = [int(np.ceil(e.compute_AET_entry(scan_line)[1])) for e in AET if e is not None]
    ValueError: cannot convert float NaN to integer


j9irw4/HAP_j9irw4.err:Traceback (most recent call last):
  - Tried to perform astrometry on ASN_raw.fits file
	Running astrometry for j9irw4040
	ERROR: Input file - j9irw4040_raw.fits - does not exist.
	{asn} astrometry: No drz file created.

  - Processing stopped in the middle of applying apriori solutions (network connection problems?)


ja2h01/HAP_ja2h01.err:Traceback (most recent call last):
  - No sources in 1 of the input images causes problems with align_utils
	File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/align_utils.py", line 198, in configure_fit
    self.extracted_sources[image])
	KeyError: 'ja2h01axq_flt.fits'

  - Secondary problem with quality control code:  No background causes divide by infinity
	File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/astrometric_utils.py", line 1954, in sigma_clipped_bkg
    		maxiters = int(np.log10(arr.max() / 2) + 0.5)
	OverflowError: cannot convert float infinity to integer


jb2o06/HAP_jb2o06.err:Traceback (most recent call last):
  - Missing input files


jbt7b6/HAP_jbt7b6.err:Traceback (most recent call last):
  - Problem accessing astrometry database mid-processing caused processing to quit completely

jcw502/HAP_jcw502.err:Traceback (most recent call last):
  - No available cores for use by AstroDrizzle single-drizzle step caused processing to quit before finishing

jdkq04/HAP_jdkq04.err:Traceback (most recent call last):
  - Ran out of virtual file handles (?) in driz_cr causing 'Broken pipe' exception and processing to quit before finishing

jdmy02/HAP_jdmy02.err:Traceback (most recent call last):
  - No sources in or fit for 1 of the images
	File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/align_utils.py", line 198, in configure_fit
    self.extracted_sources[image])
	KeyError: 'jdmy02iuq_flt.fits'
  - problem creating total catalog due to lack of sources for 1 image?
	Traceback (most recent call last):
	  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/hapsequencer.py", line 475, in run_hap_processing
	    phot_mode=phot_mode)
	  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/hapsequencer.py", line 120, in create_catalog_products
	    total_product_catalogs.identify(mask=total_product_obj.mask)
	  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/catalog_utils.py", line 323, in identify
	    self.catalogs[catalog].identify_sources(**pars)
	  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/catalog_utils.py", line 986, in identify_sources
	    max_source_fraction=self._max_source_fraction)
	  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/catalog_utils.py", line 1667, in _evaluate_segmentation_image
	    max_source_fraction=max_source_fraction)
	  File "/home/mburger/anaconda3/envs/caldp/lib/python3.6/site-packages/drizzlepac/haputils/catalog_utils.py", line 1709, in _seg_rejection
	    nbins = segm_img.max_label
	AttributeError: 'NoneType' object has no attribute 'max_label'



idi534/HAP_idi534.out:Output status = 1
  - Expected to fail due to too large of an output frame for all inputs.
     ==> Need to develop logic to look for this situation and figure a solution to avoid it.

idnm0u/HAP_idnm0u.out:Output status = 1
  - Skymatch error (see above)

j8fd06/HAP_j8fd06.out:Output status = 1
  - Same problem as 'jdmy02' with total catalog creation

j9qu06/HAP_j9qu06.out:Output status = 1
  - Same problem as 'jdmy02' with total catalog creation


ja0001/HAP_ja0001.out:Output status = 1
  - Same problem as 'jdmy02' with total catalog creation


jb4g02/HAP_jb4g02.out:Output status = 1
  - Same problem as 'jdmy02' with total catalog creation

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-404?focusedCommentId=480170#comment-480170):_

Issue associated with "ib2t06/HAP_ib2t06.err:Traceback (most recent call last)" resolved (see HLA-406).

**Comment by stsci-hack** [comment]
Resolved with #772 and #775.
