### ISSUE TITLE
Fix logic for SVM with multiple detectors and possiblity of detection of no sources

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#770]
_Issue [HLA-406](https://jira.stsci.edu/browse/HLA-406) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Thus far, the problem seems to be only if the Segment catalog does not find any sources. If neither catalog finds sources, the code works properly.  If only the Point catalog does not find any sources, the code works properly.

Test dataset ib2t06 (wfc3, both UVIS and IR detectors).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-406?focusedCommentId=480081#comment-480081):_

Update: The problem is *at least* manifested when there are multiple detectors in a single visit, and the initial detector processed results in one of the current catalogs (Point or Segment) finding no sources.  The associated products are processed correctly. However, when the next detector is processed and both catalogs have sources, some residue from the previous processing confuses the software and causes a failure.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-406?focusedCommentId=480117#comment-480117):_

This problem was caused by a combination of two bugs which have been addressed.
 * Ensure the phot_mode variable is reset to its input setting for every total product
 being processed. The phot_mode can be modified during processing if one of the
 source detection algorithms does not find any sources.
 * Bubble up the stack the "no sources detected" warning for the segmentation algorithm
 and return to the invoking algorithm.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-406?focusedCommentId=480118#comment-480118):_

Bug has been addressed in Git PR#&#x2060;771 and is out for review.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-406?focusedCommentId=480169#comment-480169):_

Git PR#&#x2060;771 approved and merged.

**Comment by stsci-hack** [comment]
Resolved with #771 (on 19-Aug-2020).
