### ISSUE TITLE
Improve collection of "number of detected sources" for JSON output

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#774]
_Issue [HLA-407](https://jira.stsci.edu/browse/HLA-407) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Improve comparison of sources found based on the white light image by protecting
against the cases where no sources are found and no catalog is actually written.
This allows the collection of data for the JSON files to continue as only the comparison
is skipped versus the entire evaluation function.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-407?focusedCommentId=480260#comment-480260):_

Improved comparison of sources found based on the white light image by protecting against the cases where no sources are found and no catalog is actually written.  This modification allows the collection of data for the JSON files to continue as only the single comparison where there may only be a catalog from one source (Point or Segment) is skipped versus the entire evaluation function.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-407?focusedCommentId=480261#comment-480261):_

Done as Git PR#&#x2060;773.  Reviewed and merged on 19 August.

**Comment by stsci-hack** [comment]
Resolved with #773 (on 19-Aug-2020).
