### ISSUE TITLE
Dependencies listed are wrong

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#777]
You don't need `tables` and `nose`.

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-408](https://jira.stsci.edu/browse/HLA-408)._

**Comment by nden** [comment]
It looks like this was addressed. I'm going to close it though I think there's still room for improvement in the dependencies list.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-408?focusedCommentId=606124#comment-606124):_

Resolved with [Drizzlepac PR #&#x2060;780](https://github.com/spacetelescope/drizzlepac/pull/780).
