### ISSUE TITLE
test_lanczos_with_grid failed on nott dev

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#78]
I accidentally messed this up in fixing #76. My bad! The file of interest was in a "modified" mode and I accidentally committed it. Then I panicked and reverted the commit but only on nott dev. Not sure how reverting that commit would have changed it as my svn-fu is not very strong...

https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&key_id=107533042

**Comment by mcara** [comment]
> The file of interest was in a "modified" mode ...

What file? Was it ``test_driz.py``? If so, I think I may have fixed it in a recent commit. Let's see if tests will pass tomorrow. Just, please, do not OKify anything.

**Comment by mcara** [comment]
> Then I panicked and reverted the commit but only on nott dev. 

What do you mean by this? CC: @jhunkeler Is it possible to revert a commit **only on nott**? Aren't changes to the repository pulled to test machines before tests are run? Is it possible to make a commit only to one machine? I am confused...

**Comment by jhunkeler** [comment]
@mcara @pllim 
FYI - The storm took down pembry this evening:
https://ssb.stsci.edu/steuermann/steuermann.cgi?action=status&run=conda_tests_py3_2017-08-03-18:00:02

Anyway to answer your question, @mcara, the repositories run a forced `svn update` every day so they remain in sync with each other. It should not be possible for changes committed/reverted on one machine _not_ to show up the next day on the other. Ahem... unless the power goes out.

**Comment by pllim** [comment]
I mean the data files are marked as "modified" by SVN on all the trees. Night test cron magic does "svn update" but that does not change the "modified" status (only "svn commit" can resolve that), so they will remain "modified" until someone commits them in. And being in "modified" state does not appear to disrupt the tests. Although, why they are even version controlled if they are supposed to be different in each tree (as suggested by the "modified" state) is beyond me.

Problem is when I accidentally committed it on "nott dev" and then reverted *something*; could be the last change you did to that file, which now causes the test to fail. So all you need to do now is to apply that change to the data file (not the test) to make the test pass again. This is only a problem on "nott dev" because I went into the other trees and did resolve the conflict in such a way that they are still in their own "modified" state and did not pick up what I committed into "nott dev".

The test script itself is not the issue here. You need to do some magic to the data but only on "nott dev". Does that make sense now?

**Comment by pllim** [comment]
To be more specific, you might need to modify one or both of these

* data/reference_lanczos_grid.fits
* data/difference_lanczos_grid.txt

**Comment by pllim** [comment]
> The storm took down pembry this evening

Argh, we need UPS...

**Comment by mcara** [comment]
1. *I think* ``data/difference_lanczos_grid.txt`` is generated during the test => no need to restore it;
2. ``data/reference_lanczos_grid.fits`` can be restored from ``nott public`` (please do not overwrite anything there).

@jhunkeler can you, please, take a look at this and see if ``data/reference_lanczos_grid.fits`` is part of the repository and if it is, can you replace it with a copy from ``nott public`` (if that one was not already overwritten when tests run 😭 ). If there are no back-up copies - I may provide a copy from my local directory.

**Comment by mcara** [comment]
@pllim @jhunkeler Let's wait for today test results before we do anything.

**Comment by pllim** [comment]
Thanks for the info, Mihai. I'll wait.

If `difference_lanczos_grid.txt` is generated output, why is it under version control? :thinking:

**Comment by mcara** [comment]
🔕

**Comment by mcara** [comment]
@jhunkeler Please copy ``reference_lanczos_grid.fits`` from ``public`` to ``dev``. Also, curiously, 
```
-rw-r--r-- 1 iraf daemon 15883200 Dec  8  2014 reference_gaussian_grid.fits
-rw-r--r-- 1 iraf iraf   15883200 Aug  1 15:39 reference_lanczos_grid.fits
```
How are ``daemon`` files actually created as opposite to ``iraf`` (I mean the difference in the "process" itself - not just user)? Also, I do not think @pllim has added this file to the repository or it would have appeared on all machines. Therefore, it should be safe to copy it from public to dev (on nott). Another approach is for you to run just unit test and pass "ok" as argument if this approach works at all - see code of the test:
```python
class TestDriz(object):

    def __init__(self):
        """
        Initialize test environment
        """
        args = {}
        for flag in sys.argv[1:]:
            args[flag] = 1

        flags = ['ok']
        for flag in flags:
            self.__dict__[flag] = flag in args
```

**Comment by mcara** [comment]
@pllim I can't find an appropriate label for this issue :)

**Comment by pllim** [comment]
I copied it over, so should pass today. Still not sure why this is even under version control, but the issue reported should be resolved.
```
-rw-r--r-- 1 iraf iraf 1.5K Aug  7 10:22 difference_lanczos_grid.txt
```
Mihai, you should add a "testing" label. 😉

**Comment by pllim** [comment]
OMG I can't spell... Should be fixed tomorrow.
```
-rw-r--r-- 1 iraf iraf  16M Aug  7 14:56 reference_lanczos_grid.fits
```
