### ISSUE TITLE
Update the annotation information which goes into the output catalog headers

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#782]
_Issue [HLA-410](https://jira.stsci.edu/browse/HLA-410) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Update the documentation of the source flagging (e.g., all possible values and associated descriptions) in the catalog headers.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-410?focusedCommentId=483043#comment-483043):_

Fixed typo which caused documentation of flag values in catalog headers to be displayed improperly (e.g., not displaying some values), and added documentation for flag 128.  Git PR#&#x2060;798.

**Comment by stsci-hack** [comment]
Resolved with #798 (on 8-Sep-2020).
