### ISSUE TITLE
Utilize the weight image in the catalog creation algorithms

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#783]
_Issue [HLA-411](https://jira.stsci.edu/browse/HLA-411) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Use the WHT extension of the input data file to either assist in the identification of sources, or for post-processing of found sources in order to filter out false detections.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-411?focusedCommentId=482069#comment-482069):_

DAOStarFinder only accommodates a single threshold value to be used as the discriminant for source detection - even though the background varies in a two-dimensional manner.  In order to improve control over source detection, the weight extension of the drizzled image is utilized.   The science image is segmented into regions

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-411?focusedCommentId=485661#comment-485661):_

See [PR 811](https://github.com/spacetelescope/drizzlepac/pull/811)

**Comment by stsci-hack** [comment]
Resolved with #811 (on 22-Sep-2020).
