### ISSUE TITLE
MVM: Revise sky cell definition code to support arbitrary numbers of input images

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#788]
_Issue [HLA-415](https://jira.stsci.edu/browse/HLA-415) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Generation of multi-visit mosaics (MVM) will require processing an arbitrarily large number of observations for a single field-of-view (sky cell only?).  The code for determining the sky cells that each observation overlaps will need to be able to handle this arbitrarily large number of inputs without running into memory problems.  

This ticket will investigate whether there are any remaining issues that would keep the SkyFootprint code from processing any number of inputs.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-415?focusedCommentId=530340#comment-530340):_

Use of S_REGION keyword values for each input may allow for less memory-intensive SkyCell overlap computations.  This may prove the biggest change to supporting large number of input exposures. 

Also, headerlet version of WCS for SkyCell may allow for enough operations to be performed for MVM processing, again, without using as much memory.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-415?focusedCommentId=530400#comment-530400):_

The SkyCell class can also be revised to return the Headerlet for the SkyCell.  This would also result in saving memory when working with SkyCells in cases where only the WCS is required and not the actual array or footprint.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-415?focusedCommentId=531926#comment-531926):_

[Drizzlepac PR #&#x2060;1049](https://github.com/spacetelescope/drizzlepac/pull/1049) was implemented to eliminate the memory use for each input exposure when computing the SkyFootprint object for a SkyCell.

This PR also resulted in a speed up of the SkyFootprint computation to about 1 second / input exposure, anywhere from 5-10X faster than before (maybe more) while limiting the memory use to 1.5 times the memory use of a single SkyCell science array size (about 2.56Gb) regardless of how many input exposures are included in the SkyFootprint.

Investigations will need to be undertaken to see what other components of the processing code use more memory with each additional input exposure to see what can be done to limit the usage where possible.

**Comment by stsci-hack** [comment]
Resolved with #1049.
