### ISSUE TITLE
Update WFC3 raw and generate new truth files to accommodate time-dependent photometry

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#790]
_Issue [HLA-416](https://jira.stsci.edu/browse/HLA-416) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Once the updated version of the CALWF3 pipeline which incorporates the time-dependent photometry is ready to be delivered (C pipeline code merged onto master), the raw input files have to modified with respect to the IMPHTTAB FITS keyword in the primary, and new truth files need to be generated.  These files are used for our PyTest system (Jenkins). The updated RAW and truth files will eventually be copied to Artifactory.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-416?focusedCommentId=483868#comment-483868):_

Added this to the sprint as it is believed the WFC3 team may be ready for delivery by 18 September.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-416?focusedCommentId=484535#comment-484535):_

The Jenkins results for the software branch which incorporates the necessary changes to support the time-dependent photometry indicates which tests fail using the new software.  I updated all the raws to use the new (preliminiary) imphttab file, and then I used the version of calwf3.e which incorporates these software changes to generate new *truth* files.  Finally, I ran PyTest, using the new calwf3.e executable, for all the WFC3 tests pointing to *input* and *truth* on my local machine.  All passed successfully.  Three new tests will be skipped as they are effectively duplicates (test_uvis_[11 | 14 | 22]single.py).

Once the test gives the OK to check in the software, I will first upload the new *input* and *truth* to artifactory.  I will then checkin the latest software and wait to see the PyTest results.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-416?focusedCommentId=485385#comment-485385):_

WFC3 Team has indicated all is well with the new software.  The updated raw and truth files have been uploaded to artifactory and the PyTests executed on the working branch for the new software have all passed successfully. The software was approved and merged onto HSTCAL master on 20 September.  The software was tagged as "2.5.0rc1", but there is some question out to Matt R. as to the proper tag.  The issue is that we are adding a new component to generate a new release candidate when a previous candidate "rc1" is already "in play".  Having said all of the above, this ticket is complete.

**Comment by mdlpstsci** [comment]
This issue has been resolved and closed in Jira.
