### ISSUE TITLE
Investigate and mitigate issues with 2D background determination

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#791]
_Issue [HLA-417](https://jira.stsci.edu/browse/HLA-417) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Dataset ibe809 (singleton) was found to have a very uneven (splotchy) source detection done for the segmentation catalog (See Jenn's report on 25 August on Slack).  This problem has been traced to the background determination algorithm.  Warren notes "our background computation (done by PhotUtils Background2D) is picking up the overlapping PSFs from the bright groups of stars in those regions".  This issue has impacted the Segmentation algorithm more severely than the Point algorithm as the Segmentation algorithm uses the full 2D image for background subtraction.  The Point algorithm currently uses only a single median value, but this is also about to change.  See HLA-409/411.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-417?focusedCommentId=484026#comment-484026):_

Reference Datasets: icgk02, ibe809, jbhf02, ibwb01, jby01y.

This particular issue is caused by the total detection image having regions of elevated intensity (fancy way to say bright clustered areas due to bright objects).  When the two-dimensional background is determined, it contains rosettes or large splotchy regions which are then “imprinted” on the background-subtracted image.  The large splotchy areas result in the Segmentation algorithm not finding sources these regions producing what look like “zones of avoidance”.

 

Based on discussions by the former Team Burgundy, experiments were done swapping out use of the Background2D algorithm and replacing the computation with the Astropy sigma_clipped_stats() which ultimately produces a single value for the two-dimensional background versus a full two-dimensional image.  Using 3-sigma and limiting the number of iterations to “2”, improved the source detection in the four reference datasets significantly. 

 

This algorithm needs more testing.  However, the harder problem is to find a discriminant which can be used to determine when this algorithm should be employed for the Segmentation algorithm.

 

It should be noted this specific solution did not produce any improvement for jby01y for the regions where there is no image overlap.  This particular dataset is a series of images which are offset from one another, and the Segmentation algorithm incorrectly identifies many cosmic rays in the“single” regions as sources.  Also, this fix only partially works for ibwb01.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-417?focusedCommentId=485393#comment-485393):_

Six datasets have been tested with the potential use of the sigma-clipped background as determined by the negativity factor for the background subtracted image.  The results, in terms of eliminating the zones of avoidance in detecting sources, showed improvement.  Next steps are to combine algorithms updated by Warren and Mike for comparison.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-417?focusedCommentId=485557#comment-485557):_

The PR#&#x2060;810 (Implement an alternative way to compute the background in support of Segmentation) has been generated and is awaiting review.

**Comment by stsci-hack** [comment]
Resolved with #810 (on 21-Sep-2020).
