### ISSUE TITLE
SVM: Part 1 - Rejection of catalogs due to insufficient cross matches between Point and Segment catalogs

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#792]
_Issue [HLA-418](https://jira.stsci.edu/browse/HLA-418) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The nearly final step in generating the HAP catalogs for public availability is to determine the statistics of cross-matches between the segment and point catalogs. If the fraction of matched sources is low for one or both catalogs, there are probably issues with spurious sources in the catalogs. Low match fractions lead to rejection of the catalogs. The details for the Part 1 criteria are discussed here
 <[https://innerspace.stsci.edu/x/_htlAg]> (updated discussion)
 and
 <[https://innerspace.stsci.edu/x/XgtlAg]> (older discussion but more rationale)

The procedures discussed in the background information sited above are independent of the HLA pipeline and are post-pipeline processes.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-418?focusedCommentId=483609#comment-483609):_

Rick suggested to delay the implementation of this discriminant.  While the code to implement the cross-matching is straightforward, how best to interpret the results is difficult.

**Comment by stsci-hack** [comment]
Resolved, as much as possible, with https://github.com/spacetelescope/drizzlepac/pull/1175.
