### ISSUE TITLE
Establish criteria to determine the contents of the catalogs distributed to the public

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#796]
_Issue [HLA-421](https://jira.stsci.edu/browse/HLA-421) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

By default, the HLA project only distributes the Point and Segmentation catalogs to the public with Flags <= 5 (point and extended sources, and saturated pixels) - the trimmed catalog.   It is felt this eliminates confusion for the users. 

HAP should adopt the same policy.

I asked Rick for the statistics on users requesting the full untrimmed catalogs.  
 cattype  all   trimmed %untrimmed
 segment 84,579  83,443  1.3
 point   81,287  79,860  1.8
 total  165,866 163,303  1.5
 To be fair, HLA has deliberately somewhat hidden access to the full catalogs.  If the full catalogs were easier to access, it is conceivable the download statistics would be higher.

If HAP were only to give out trimmed catalogs:
 * Less confusion for the users as we have already made the decision to "clean up" the catalog.
 * They can, with some effort and compute resources, compute the full catalog themselves since the code is public.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-421?focusedCommentId=484929#comment-484929):_

Trimming of both the point and segment catalogs based on Flags <= 5 has been implemented through [Drizzlepac PR #&#x2060;805](https://github.com/spacetelescope/drizzlepac/pull/805).

**Comment by stsci-hack** [comment]
Resolved with #805 (on 16-Sep-2020).
