### ISSUE TITLE
Detector-dependent Grism and direct image data should have the Grism 'a priori' WCS as the primary WCS

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#797]
_Issue [HLA-422](https://jira.stsci.edu/browse/HLA-422) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The GRISM image should have the same WCS as was determined for the corresponding direct image.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=485409#comment-485409):_

Headerlets are not designed to suppor this type of operation, so a separate method will need to be defined to pass along the WCS correction from the direct image to the Grism image.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=504179#comment-504179):_

WFC3 and ACS grism experts have requested that relative alignment between grism and direct images be preserved.

This is deemed high priority, as the users cannot begin their analysis with the current approach, and we request that these datasets be reprocessed as soon as the updated software is available.

+*Proposed solution:*+

For visits with grism images, DO NOT apply any a posteriori solutions to any datasets. Instead, we want to be sure the same a priori solution is used for the whole visit, preserving relative alignment.  

This means that the direct image data may be slightly off from the 'best' alignment we could provide, eg. if someone repeats the HDF with a grism/direct image pair, the new data may be slightly offset... Similarly for direct image visits in the same program which had no grisms may be slightly offset from other visits.  But we are okay with this.  

The same logic should be used for both the grisms and the HRC,SBC prisms.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=504193#comment-504193):_

Tentative decision at today's meeting: 
 * Use this logic for standard processing only.
 * For HAP products, the direct image can be updated to use the 'a posteriori' solution.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=504810#comment-504810):_

Update 1/19/21:

The grism experts have suggested a slightly revised strategy.  For standard products, go ahead and compute the 'a posteriori' solution for the direct images and populate these as a possible WCS solution, but not as the primary WCS. 

Therefore, at the end of the alignment process, we want the software to ***reset* the primary WCS of the direct image to the 'a priori' WCS** such that all images in the visit will have accurate relative alignment.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Roberto Avila](https://jira.stsci.edu/secure/ViewProfile.jspa?name=avila) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=504918#comment-504918):_

This seems like a good solution. The ACS team would be ok with this.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=505227#comment-505227):_

How to map Grism image to direct image as the Grism image has no
DIRIMAGE (value = NONE) and the association for the Grism images do not contain
individual exposure names?

===================================================

WFC3
(caldp_20201208) bash-4.1$ cat wfc3_b8c_5d_input.out
 DIRIMAGE ASN
ib8c5dw2q_flt.fits,11696,B8C,5D,1202.936035,G102,IR NONE | ib8c5d010_asn.fits
ib8c5dw3q_flt.fits,11696,B8C,5D,1002.935364,G102,IR NONE ib8c5d010_asn.fits
ib8c5dw6q_flt.fits,11696,B8C,5D,327.938995,F110W,IR NONE -
ib8c5dwbq_flc.fits,11696,B8C,5D,200.0,F600LP,UVIS NONE -


(caldp_20201208) bash-4.1$ cat wfc3_bbr_01_input.out
ibbr01zfq_flt.fits,11935,BBR,01,0.48,F200LP,UVIS NONE
ibbr01zgq_flt.fits,11935,BBR,01,0.48,F300X,UVIS NONE
ibbr01zhq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01010
ibbr01ziq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01010
ibbr01zjq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01010
ibbr01zkq_flt.fits,11935,BBR,01,0.48,F200LP,UVIS NONE
ibbr01zlq_flt.fits,11935,BBR,01,0.48,F300X,UVIS NONE
ibbr01zmq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01020
ibbr01znq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01020
ibbr01zoq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01020
ibbr01zpq_flt.fits,11935,BBR,01,0.48,F200LP,UVIS NONE
ibbr01zrq_flt.fits,11935,BBR,01,0.48,F300X,UVIS NONE
ibbr01zsq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01030
ibbr01ztq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01030
ibbr01zuq_flt.fits,11935,BBR,01,2.5,G280,UVIS NONE ibbr01030
ibbr01zvq_flc.fits,11935,BBR,01,0.0,G280,UVIS NONE ibbr01040
ibbr01zwq_flc.fits,11935,BBR,01,0.0,G280,UVIS NONE ibbr01040

===================================================

ACS
(caldp_20201208) bash-4.1$ cat acs_8eh_11_input.out
j8eh11iiq_flc.fits,9290,8EH,11,1170.0,F850LP;CLEAR2L,WFC NONE je8eh11010
j8eh11ijq_flt.fits,9290,8EH,11,1064.0,G800L;CLEAR2S,HRC NONE je8eh11040
j8eh11inq_flc.fits,9290,8EH,11,1170.0,F850LP;CLEAR2L,WFC NONE je8eh11010
j8eh11ioq_flt.fits,9290,8EH,11,1064.0,G800L;CLEAR2S,HRC NONE je8eh11040
j8eh11j5q_flc.fits,9290,8EH,11,1220.0,F850LP;CLEAR2L,WFC NONE je8eh11020
j8eh11j6q_flt.fits,9290,8EH,11,1114.0,G800L;CLEAR2S,HRC NONE je8eh11040
j8eh11jbq_flc.fits,9290,8EH,11,1220.0,F850LP;CLEAR2L,WFC NONE je8eh11020
j8eh11jcq_flt.fits,9290,8EH,11,1114.0,G800L;CLEAR2S,HRC NONE je8eh11040
j8eh11jqq_flc.fits,9290,8EH,11,1220.0,F850LP;CLEAR2L,WFC NONE je8eh11030
j8eh11jrq_flt.fits,9290,8EH,11,1114.0,G800L;CLEAR2S,HRC, NONE je8eh11040
j8eh11jzq_flc.fits,9290,8EH,11,1220.0,F850LP;CLEAR2L,WFC NONE je8eh11030
j8eh11k0q_flt.fits,9290,8EH,11,1114.0,G800L;CLEAR2S,HRC NONE je8eh11040

(caldp_20201208) bash-4.1$ cat acs_cat_24_input.out
jcat24irq_flc.fits,13420,CAT,24,278.0,CLEAR1L;F814W,WFC NONE jcat24010
jcat24isq_flc.fits,13420,CAT,24,658.0,G800L;CLEAR2L,WFC NONE jcat24020
jcat24iwq_flc.fits,13420,CAT,24,361.0,CLEAR1L;F814W,WFC NONE jcat24010
jcat24iyq_flc.fits,13420,CAT,24,741.0,G800L;CLEAR2L,WFC NONE jcat24020
jcat24j3q_flc.fits,13420,CAT,24,297.0,CLEAR1L;F814W,WFC NONE jcat24010
jcat24j5q_flc.fits,13420,CAT,24,677.0,G800L;CLEAR2L,WFC NONE jcat24020
jcat24j8q_flc.fits,13420,CAT,24,363.0,CLEAR1L;F814W,WFC NONE jcat24010
jcat24jaq_flc.fits,13420,CAT,24,743.0,G800L;CLEAR2L,WFC NONE jcat24020

===================================================

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=505327#comment-505327):_

Hi Michele, 

The title of this ticket is a bit misleading. At this point, we don't want to map the grism to the direct image, as I believe the two datasets are not associated.

Instead, we need to add some logic that looks at the visit-level products (not the ASNs) and resets the primary WCS for all images within that visit to use the 'a priori' solution.

This would be done at the end of the current processing, so that the direct images would still get 'a posteriori' solutions, but they would be an alternate WCS, not the primary one.

I realize this may be tricky, since the standard astrometry pipeline doesn't use 'visit-level' logic... but perhaps it could be borrowed from the SVM pipeline?

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=505370#comment-505370):_

Unfortunately, not only does the "standard pipeline processing" not know about the concept of a *visit*, the HAP SVM code also does not know ***on its own*** about a *visit*. The visit information is fed to the HAP SVM process by code developed in Operations as their code interacts with databases to construct the visit information.  Effectively, the Operations code invokes the HAP SVM process with a file containing the visit information as input.

As Warren and I discussed this, we have to do this during HAP SVM processing as this is the only stage where the visit information is known and *any* Grism data is associated with *any* direct image data. I will note that we cannot modify the original pipeline generated FLT/FLC images, so the visit exposure level products (e.g., hst_<propid>_<obsetid>_<instr>_<detector>_<filter>_<ipppssoo>_fl[ct].fits) will be the files modified to have their primary/active WCS set to that of the Grism exposures in a detector-dependent manner.  I say this as in my "Grism example visits" above, the ACS visit (acs_8eh_11_input.out) has all the Grism exposures taken with HRC and all the direct image exposures taken with WFC.  The WCS for the WFC direct exposures would NOT be modified.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=505385#comment-505385):_

This makes sense (eg. we can only fix the relative alignment of these datasets in the SVM products), and I think it will be an acceptable solution.  (I will confirm with the experts and let you know if otherwise).  We just need to teach people to look specifically for Project='HAP' when they download products.

I also agree that we don't need to align anything across detectors, eg. for this unusual ACS example with HRC and WFC.

Thank you for helping us work this out!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=505467#comment-505467):_

One pitfall is that the HAP images are drizzled to North up, so the grisms would be significantly resampled.

However, I'm not sure DRZ products are useful for these programs, (eg. only RAW, IMA and FLT are used by the reduction pipeline), so it may be ok.  I'm checking with the grism team now.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=508561#comment-508561):_

This ticket is slightly modified in that Ramp and Quad filter images no longer will be processed in the standard way.  They will only be processed through the alignment step.  The implementation to enable this will be the same as done for the Grism/Prism images.  The Quad/Ramp exposures will be tracked as a new Product object, QuadExposureProduct, in their own list as part of the TotalProduct object.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-422?focusedCommentId=509858#comment-509858):_

This is Git PR#&#x2060;543.  The Ramp/Quad filter issue is being handled by Jira HLA-480.

**Comment by stsci-hack** [comment]
Resolved (on 15-Feb-2021) with #543.
