### ISSUE TITLE
Logging when multiprocessing needs to be fixed

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#799]
_Issue [HLA-423](https://jira.stsci.edu/browse/HLA-423) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Work to get Drizzlepac to build and run under Windows revealed that the logging implemented in AstroDrizzle silently fails under Linux and Mac yets throws an Exception under Windows.  The initial workaround is to turn off multiprocessing when running AstroDrizzle under Windows (as implemented under [Drizzlepac PR #&#x2060;794](https://github.com/spacetelescope/drizzlepac/pull/794)). 

The Python documentation discusses the best practice for performing logging while multiprocessing in [this Section of the Logging Cookbook](https://docs.python.org/2/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes).  This method will require setting up Socket Server/Client system within the code to manage the logs from each thread.  

This issue does not significantly impact pipeline operations as it only affects the logs from the single-drizzle step, but it does cause problems for supporting this code on all platforms (particularly, Windows).

**Comment by stsci-hack** [comment]
Resolved with #794.
