### ISSUE TITLE
Tweakreg crashes when run with updatehdr=False

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#800]
User has reported that tweakreg crashes when being run with 'updatehdr=False'. The traceback looks like:
```python
  File ".../lib/python3.6/site-packages/drizzlepac/util.py", line 225, in wrapper
    result = func(*args, **kwargs)
  File ".../lib/python3.6/site-packages/drizzlepac/tweakreg.py", line 589, in run
    reusename=uphdr_par['reusename'])
  File ".../lib/python3.6/site-packages/drizzlepac/imgclasses.py", line 824, in updateHeader
    yrms=self.fit['rms_keys']['RMS_DEC'])
  File ".../lib/python3.6/site-packages/drizzlepac/updatehdr.py", line 257, in updatewcs_with_shift
    reusename=reusename, verbose=verbose)
  File ".../lib/python3.6/site-packages/drizzlepac/updatehdr.py", line 465, in update_wcs
    altwcs.archive_wcs(image, [extnum], wcsname=pri_wcsname, mode=altwcs.ArchiveMode.AUTO_RENAME)
  File ".../lib/python3.6/site-packages/stwcs/wcsutil/altwcs.py", line 185, in archive_wcs
    raise ValueError("'fname' must be a file object opened in 'update' mode.")
ValueError: 'fname' must be a file object opened in 'update' mode.
```
This is probably due to stricter enforcement in `altwcs` of files being updated to be opened in the `update` mode.

Tweakreg should not attempt to update headers when run in `updatehdr=False` mode.

CC: @stsci-hack

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-424](https://jira.stsci.edu/browse/HLA-424)._

**Comment by kmcquinn** [comment]
I'm running into the same problem using tweakreg. I just updated my stsci stack:
conda update -n astroconda stsci
but the problem persists. 

Is there another update that I should do to incorporate whatever fix was implemented? 
thanks!

**Comment by masolimano** [comment]
@kmcquinn Apparently this fix is included in version 3.1.9 of Drizzlepac, which is still unreleased.  So updating the stack via conda will only get you to version 3.1.8. 

https://drizzlepac.readthedocs.io/en/latest/CHANGELOG.html

**Comment by mcara** [comment]
@kmcquinn @masolimano It seems like `3.2.1` was released on PyPi and so try to get the latest version from there.

**Comment by kmcquinn** [comment]
Thanks!

From: Mihai Cara ***@***.***>
Date: Monday, May 17, 2021 at 8:58 AM
To: spacetelescope/drizzlepac ***@***.***>
Cc: Mcquinn, Kristen B ***@***.***>, Mention ***@***.***>
Subject: Re: [spacetelescope/drizzlepac] Tweakreg crashes when run with updatehdr=False (#800)

@kmcquinn<https://github.com/kmcquinn> @masolimano<https://github.com/masolimano> It seems like 3.2.1 was released on PyPi and so try to get the latest version from there.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-424?focusedCommentId=606125#comment-606125):_

Resolved with [Drizzlepac PR #&#x2060;801](https://github.com/spacetelescope/drizzlepac/pull/801) on 8-Sep-2020.
