### ISSUE TITLE
SVM Q&A: Limit number of sources plotted in astrometry comparisons

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#802]
_Issue [HLA-425](https://jira.stsci.edu/browse/HLA-425) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The number of sources used for the astrometry comparisons should be limited to the 500 brightest (non-saturated?) sources per chip from each product instead of using all sources.  Using all sources can masks systematic effects which would be critical to understanding the actual alignment between the images.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-425?focusedCommentId=487607#comment-487607):_

It turned out that this behavior was already implemented in 'haputils/quality_analysis' with a default limit set of 2000 sources per chip.  However, given the request, this default limit will be lowered to 1000 sources per chip and testing will be performed to insure that this change results in less crowded and more relevant/accurate astrometry residual plots.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-425?focusedCommentId=488580#comment-488580):_

Submitted changes as part of [Drizzlepac PR#&#x2060;815](https://github.com/spacetelescope/drizzlepac/pull/815).

**Comment by stsci-hack** [comment]
Resolved with #815.
