### ISSUE TITLE
SVM: Investigate scope of HLA-419 and HLA-420

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#804]
_Issue [HLA-427](https://jira.stsci.edu/browse/HLA-427) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Investigate what effort will be necessary to implement HLA-419 and HLA-420 in order to be able to size the ticket effectively and with some level of confidence.  This will provide us with the information necessary to plan what sprints these tickets can be worked and when we can complete this work.

**Comment by stsci-hack** [comment]
Resolved with #839.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-427?focusedCommentId=606127#comment-606127):_

Resolved with [Drizzlepac PR #&#x2060;839](https://github.com/spacetelescope/drizzlepac/pull/839) on 14-Sep-2020.
