### ISSUE TITLE
SVM: Trim total catalog based on flags

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#814]
_Issue [HLA-430](https://jira.stsci.edu/browse/HLA-430) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Work has been done to remove sources from each filter's catalog that had flag values > 5.  This insures that the point and segment catalogs for each filter only have the most probable valid sources in the field.  The total catalog, though, still contains the entire set of initial source positions regardless of flag values.  

The HLA method for handling this was to remove sources from the total catalog which had flag > 5 in ALL the filter catalogs.  This still needs to be implemented for the SVM processing in order to be consistent with the HLA catalogs.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Robert Swaters](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rswaters) on [JIRA](https://jira.stsci.edu/browse/HLA-430?focusedCommentId=488256#comment-488256):_

Already done under a different ticket.

**Comment by stsci-hack** [comment]
Resolved, as much as possible, with #1175.
