### ISSUE TITLE
Utilize the exclusion mask defined in the HAPCatalogBase for the HAPSegmentCatalog class

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#816]
_Issue [HLA-431](https://jira.stsci.edu/browse/HLA-431) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Use the exclusion_mask defined in HAPCatalogBase in HAPSegmentCatalog to avoid identifying spurious detections as seen for ICGZA1.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-431?focusedCommentId=487368#comment-487368):_

Use of the exclusion mask in combination with the regional WHT has resolved many issues. This also means both the Point and Segmentation algorithms are using the same exclusion mask which is better for consistency.

**Comment by mdlpstsci** [comment]
This issue has resolved and closed in Jira.  The exclusion mask is not is use.  A  footprint mask (illuminated portion of the  image) is used as a cleaner alternative.
