### ISSUE TITLE
MVM: Only generate sky cell layers being updated by input exposures

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#817]
_Issue [HLA-432](https://jira.stsci.edu/browse/HLA-432) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

MVM processing takes 2 lists of inputs:
* observations which need to be aligned to the projection cells
* observations which have ALREADY been aligned to the projection cell

Current MVM processing code will process all exposures, recreating all layers even if no new data was provided.  New logic needs to be added to recognize what layers are affected by the 'new' input exposures and ONLY align the data to the data in those layers and only run drizzle to generate those updated or new layers.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Robert Swaters](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rswaters) on [JIRA](https://jira.stsci.edu/browse/HLA-432?focusedCommentId=488511#comment-488511):_

Here's an example (with fake content) of what the poller file will look like. The skycell will also be in the poller file name.
ib3p01r9q_flc.fits,11635,B3P,01,1492.0,F469N,UVIS,/ifs/archive/dev/hst/info/rswaters/test/test_rswaters_20200506_05/regr_08120/pipe/science/hap/ib3p01r9q_flc.fits,<skycell>,old
ib3p01raq_flc.fits,11635,B3P,01,1492.0,F469N,UVIS,/ifs/archive/dev/hst/info/rswaters/test/test_rswaters_20200506_05/regr_08120/pipe/science/hap/ib3p01raq_flc.fits,<skycell>,old
ib3p01rbq_flc.fits,11635,B3P,01,1561.0,F469N,UVIS,/ifs/archive/dev/hst/info/rswaters/test/test_rswaters_20200506_05/regr_08120/pipe/science/hap/ib3p01rbq_flc.fits,<skycell>,new
ib3p01rdq_flc.fits,11635,B3P,01,1561.0,F469N,UVIS,/ifs/archive/dev/hst/info/rswaters/test/test_rswaters_20200506_05/regr_08120/pipe/science/hap/ib3p01rdq_flc.fits,<skycell>,new

**Comment by stsci-hack** [comment]
Resolved with #911.
