### ISSUE TITLE
MVM: Enforce GAIA WCS across entire projection cell

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#818]
_Issue [HLA-433](https://jira.stsci.edu/browse/HLA-433) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

MVM processing requires two sets of input exposures:
* new exposures to be aligned and added to sky cells
* exposures which have already been aligned to the sky cells (if any)

Current processing will attempt to completely redefine the alignment to GAIA based on all input exposures (both old and new).  We need to determine whether or not logic should be added to preserve the previous alignment to GAIA for the sky cell based on the WCS provided by previously processed exposures for the sky cell.  We do need to add logic to insure that the WCS remains consistent across all layers as well as consistent across the projection cell. 

Without this logic in place, we can not be sure that we are maintaining a consistent WCS for all the MVM products in a given sky cell, let alone across a projection cell.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-433?focusedCommentId=496536#comment-496536):_

Discussions with the AWG (on 4-Nov-2020) determined that when new data is being added to a sky cell where observations have already been aligned to GAIA in the sky cell, the source positions from the previously aligned observations would serve as the reference.  This would avoid completely re-defining the WCS for the sky cell.  

However, during reprocessing campaigns when all the data has already been aligned to GAIA, a whole new solution where all observations are considered 'inputs' to the fit and they are all fit to GAIA to refine/redefine the WCS for the inputs to match them to the (always predefined) sky cell WCS.   

This strikes a balance between always redoing the entire fit and only fitting what is new.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack) on [JIRA](https://jira.stsci.edu/browse/HLA-433?focusedCommentId=575300#comment-575300):_

INS will test the alignment of MVMs after processing with 2022.1, and we will advise whether we need to 'enforce the GAIA WCS' across the entire projection cell.  Initial tests show significant offsets between a priori and a posteriori solutions (see team_burgundy slack chat from Jan 20th):

**mvm_p0498x16y19_f555w.png** 
The UVIS F555W layer is composed of 4 separate visits. In the overlap region, you can see a misalignment caused by one of the visits (right) having a different WCS solution than the others. 
See also related ticket [HLA-554](https://jira.stsci.edu/browse/HLA-554) which addresses difficulty aligning UV and blue filters to Gaia.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-433?focusedCommentId=602594#comment-602594):_

No additional alignment processing will be done for MVM products, so there is no way to enforce or implement this functionality.  It was decided that the alignment from the SVM processing will be used for all MVM products for now.

**Comment by nden** [comment]
Jira ticket was cancelled. Closing
