### ISSUE TITLE
SVM: Re-organize and streamline background computation

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#823]
_Issue [HLA-436](https://jira.stsci.edu/browse/HLA-436) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Re-organize/streamline the various algorithms used for the background computation and re-locate the code to the compute_background method of CatalogImage.  In this way, both the Point and Segment catalogs will be starting with the same derived background image.  This will also require updating the HAP configuration files as some of the values are now "generalized" instead of being associated with a particular type of catalog.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-436?focusedCommentId=487904#comment-487904):_

A nearly completed version has been somewhat tested by another member of the team.  The fourth iteration has gone out for code review (Git PR#&#x2060;827) on Thursday, 01 Oct 2020.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-436?focusedCommentId=487919#comment-487919):_

This code has been merged and will serve as a good basis from which we can tune parameters.

**Comment by mdlpstsci** [comment]
This issue has been resolved and closed in Jira.
