### ISSUE TITLE
SVM: Thoroughly test re-organized background determination algorithm

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#824]
_Issue [HLA-437](https://jira.stsci.edu/browse/HLA-437) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The re-organized/streamlined background determination algorithm needs to be thoughly tested with a statistically significant number of datasets.  Mike, Warren, and Michele all need to participate in this testing.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-437?focusedCommentId=487955#comment-487955):_

I have made a comparison of the original background computation algorithm with the updated algorithm using `icnw34`.  This comparison of ONLY the point catalog shows the regions of avoidance induced by the original algorithm, regions which are now eliminated with the new algorithm which correctly switches to using the sigma-clipped background instead.  

 !icnw34_point_default_vs_fixed_bkg.png|thumbnail!

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-437?focusedCommentId=488568#comment-488568):_

Set "negative_threshold = 0.0" which works in conjunction with the re-organized background determination algorithm.  The threshold defines the pixels which are classified as "negative" values.  If the number of negative values exceeds "negative_percent = 15.0", then the algorithm used to define the background uses the sigma_clipped_stats().  This eliminates the "rosettes" or "zones of avoidance" found around regions.  Dataset JBHF02 (12254) was a fundamental dataset for this testing.

**Comment by mdlpstsci** [comment]
This issue has been resolved and closed in  Jira.
