### ISSUE TITLE
MVM: Support specification of output skycell in poller file

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#825]
_Issue [HLA-438](https://jira.stsci.edu/browse/HLA-438) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The poller file will almost always contain some exposures that overlap additional sky cells.  By default, ALL sky cells affected by those inputs would be processed/updated based on the specified input files.  However, this creates ambiguities during pipeline processing as it tries to insure that all affected sky cells are updated correctly.  

Resolving this ambiguity will require being able to have the pipeline specify that only a single sky cell should be updated based on the input exposures even if the input exposures overlap additional sky cells.  The intended output sky cell should be specified in the filename of the input poller file.  If no sky cell is specified in the poller file filename, then ALL sky cells affected by the inputs should still be processed as done by default.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-438?focusedCommentId=493105#comment-493105):_

Sample poller file has been provided in the comments in HLA-432.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Robert Swaters](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rswaters) on [JIRA](https://jira.stsci.edu/browse/HLA-438?focusedCommentId=494745#comment-494745):_

The order in the poller file will be changed, as described in HLA-388 and HSTSDP-1040.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-438?focusedCommentId=495603#comment-495603):_

It is my understanding that a sky cell will always be specified for each row/image in the MVM poller file.  Further, only one sky cell name is allowed to be specified per MVM poller file.  The issue arises if instead of a poller file, the input is a list of filenames.  In this case, the sky cells affected by processing each input image must be tracked.  For example, one input image could conceivably overlap multiple sky cells, and therefore, these multiple sky cells need to be updated.

**Comment by stsci-hack** [comment]
Ultimately, each poller file will ONLY apply to a single sky cell and the HAP code already supports the correct interpretation of the input poller files based on that assumption as enforced by the changes by HSTSDP-1040.
