### ISSUE TITLE
SVM: Investigate why WFC3 IR HAP astrometry is not as good as HLA astrometry

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#826]
_Issue [HLA-439](https://jira.stsci.edu/browse/HLA-439) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Comparison of the HAP astrometry for WFC3/IR catalogs with the HLA catalogs has revealed that the HAP astrometry is not as precise (accurate) as the HLA positions.  It is not clear what is causing the HAP positions to not be as accurate, and this needs to be understood in order to meet project requirements of being consistent with HLA.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-439?focusedCommentId=493243#comment-493243):_

Findings from WFC3_12110_05 (ibfo05) F160W -> F336W crossmatch:
Using HAP F336W sourcelist as reference, both HAP F160W and HLA F160W sourcelist crossmatches yielded similar statistics for the differences in positions of cross-matched sources.

HLA F160W point catalog -> HAP F336W point catalog crossmatched source position differences (mean-subtracted) 
Comparison - reference Separation statistics (HAP WFC3/UVIS pixels)
       Sigma-clipped Statistics; σ = 3, Number of clipping steps = 3
Sigma-clipped mean............................ 1.9560831580925189
Sigma-clipped median.......................... 1.2479587494508793
Sigma-clipped standard deviation.............. 1.5893860385716223
% all diff values within 1σ of clipped mean... 63.63636363636363%
% all diff values within 2σ of clipped mean... 99.17355371900827%
% all diff values within 3σ of clipped mean... 100.0%

HAP F160W point catalog -> HAP F336W point catalog crossmatched source position differences (mean-subtracted)
Comparison - reference Separation statistics (HAP WFC3/UVIS pixels)
       Sigma-clipped Statistics; σ = 3, Number of clipping steps = 3
Sigma-clipped mean............................ 1.622384711574567
Sigma-clipped median.......................... 0.9406135309951748
Sigma-clipped standard deviation.............. 1.3979573538396017
% all diff values within 1σ of clipped mean... 72.36842105263158%
% all diff values within 2σ of clipped mean... 96.05263157894737%
% all diff values within 3σ of clipped mean... 100.0%

Additionally, the sources with the largest differences between the reference HAP F336W positions an the comparison HAP F160W positions were not spatially coincident with any  anomalous or otherwise noteworthy sources or regions of the image (saturated sources, artifacts, image edges, etc). The largest 100 position differences were scattered randomly across the image, and were tied to sources that were unremarkable.

Overall, my findings so far are inconclusive. I could not find a definitive cause.

**Comment by stsci-hack** [comment]
Resolved as much as possible, for now, with #849 to allow comparisons to be made.  Analysis with v3.4.0 and later seems to indicate better agreement between the HAP and HLA catalogs for WFC3/IR observations.
