### ISSUE TITLE
Why is drizzlepac running on Travis CI?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#83]
I don't see any `.travis.yml` file and yet...

https://travis-ci.org/spacetelescope/drizzlepac/builds/214776978

https://travis-ci.org/spacetelescope/drizzlepac/builds/273370222

**Comment by mcara** [comment]
@pllim It may be helpful to mention the guilty party or the one who could fix this: @jhunkeler

**Comment by mcara** [comment]
Also, is this related to https://github.com/spacetelescope/drizzlepac/issues/45

**Comment by nden** [comment]
👍 to stopping Travis on drizzlepac.

**Comment by pllim** [comment]
At least I am consistent in my pestering... 😛 

I lost admin power to the drizzlepac Travis account, so someone please turn off the cron job and just turn it off for drizzlepac entirely.

**Comment by jhunkeler** [comment]
@pllim @mcara 
Justin created a travis cron job to run at a regular interval against the `deployment` branch.

The cron job has been deleted.

**Comment by mcara** [comment]
@jhunkeler This answer is similar to https://github.com/spacetelescope/drizzlepac/issues/45#issuecomment-289341777 looking at which makes me wonder who woke-up the demon?

**Comment by jhunkeler** [comment]
Maybe he added the cron job after that issue was submitted, and it wasn't failing or notifying people until recently? 🎱

**Comment by pllim** [comment]
> who woke-up the demon?

Maybe the same person who took away my admin privilege.

**Comment by mcara** [comment]
@pllim I was referring to travis/cron job but I am not opposite to your interpretation either :smiling_imp:
