### ISSUE TITLE
SVM: Define a minimum value for the threshold used for detecting sources

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#831]
_Issue [HLA-441](https://jira.stsci.edu/browse/HLA-441) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

This is primarily a Segmentation ticket, but a minimum threshold should be defined based upon the readnoise, A-to-D gain, number of exposures, and the total exposure time for cases where the background and RMS are very small.  The purpose is to help the Segmentation algorithm avoid identifying noise as a source.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-441?focusedCommentId=490745#comment-490745):_

This update is out as Git PR#&#x2060;837.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-441?focusedCommentId=491464#comment-491464):_

Software was reviewed, approved, and then merged on 21 Oct 2020.

**Comment by mdlpstsci** [comment]
As stated resolved and closed in Jira.
