### ISSUE TITLE
SVM: Ensure computations are handled properly for ACS/SBC

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#833]
_Issue [HLA-442](https://jira.stsci.edu/browse/HLA-442) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The SBC is a MAMA detector and does not have all of the same FITS keywords as the CCDs.  In particular, there is no "gain" factor.  However, the gain is used in computations of the flux and magnitude errors during the photometry calculations.  These values are set to **nan** currently by the software.  However, the magnitude error, in particular, is used in the flagging procedure in the evaluation of the photometry measurements.  Consequently, all the SBC measurements are flagged with 8 (Faint magnitude limit) and 16 (Hot pixel) causing the detected sources to be trimmed from the catalogs.  This causes an Exception to be thrown when trying to merge catalogs.

A decision has to be made as to how to set the "gain" value for SBC which would probably be 1.0.  Also, the code should have protection and not try to manipulate empty catalogs.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-442?focusedCommentId=490353#comment-490353):_

The fix for this issues has been filed as Git PR#&#x2060;834.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-442?focusedCommentId=490488#comment-490488):_

This PR was approved and merged.  There was a change in that the gain was set to 1.0 for not only ACS/SBC, but it was also set to 1.0 for WFC3/IR.

**Comment by mdlpstsci** [comment]
As note above this ticket is closed.
