### ISSUE TITLE
SVM: Detect large segment situations for which deblending takes a long time

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#838]
_Issue [HLA-443](https://jira.stsci.edu/browse/HLA-443) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

There are situations where the deblending of detected sources can take many hours of time.  The reason is the segments are very large in size (many pixels).  The idea here is to:

1) define what is meant by large,

2) detect if large segments are present, and 

3) to decide whether the implemented action (under HLA-441) was sufficient (if not, then a new ticket will be filed for further investigation)

The code which is currently used to detect crowded fields is effective and can be applied to Item 2.  Some work on this issue has already been done as part of HLA-441 in the form of feature creep.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Robert Swaters](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rswaters) on [JIRA](https://jira.stsci.edu/browse/HLA-443?focusedCommentId=499225#comment-499225):_

Goal for step 3) is to investigate the current iterative algorithm for changing the detection threshold

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-443?focusedCommentId=504750#comment-504750):_

**OLD ALGORITHM**
Determine segmentation image with Gaussian kernel
Deblend (This deblend typically dominated the processing time.)
If exceeds thresholds, determine segmentation image with RickerWavelet kernel
Deblend

**NEW ALGORITHM**
Determine segmentation image with Gaussian kernel
If exceeds thresholds, determine segmentation image with RickerWavelet kernel
Deblend
Revert to use of Gaussian kernel if "big island" value is larger than the
big island values computed with the Gaussian kernel.

 

Dataset PropID INST G/RW BigIsland/SourceFrac New_T Old_T Notes
id1x09 14393 uvis G 73851 0.6 5.3 - - 73851 8m better than pt in some areas
OLD 69549 7.5 15.3 6d/0

jcol05 13826 wfc revert 375 6.9 7.1 102586 10.3 375 2h12m defuse nebulae
OLD 1566 16.0 16.2 255629 2.9 3d + 5d

idx5a2 15583 uvis G 260 0.0 0.1 - - 260 2s many images scan_type=C, no cats
OLD 4861 5.4 11.9 12288 3.0 122288 1d + 7d

ibsf01 12499 uvis revert 54174 2.1 10.7 127948 5.4 54174 6m 4 overlap w/nebulae Seg sources in n=1
OLD 9301 5.6 6.4 110089 2.5d + 2.5h

idbhb1 14815 uvis G 240 0.0 0.0 - - 240 3s fine/gyro, no cats produced
OLD 6397 2.2 6.5 13156 1.4 13156 9h + 8h

ibwb01 12692 uvis 8353 0.2 1.0 - - 8353 45s 3 regions
OLD 3752 0.1 0.7 - - 3932 25s

ibe809 12094 uvis RW 57103 0.8 7.5 62605 1.1 62605 7m crowded field
OLD 12459 0.3 3.0 - - 13549 1.5m

icgk02 13572 ir RW 5015 1.4 8.8 17667 1.4 17667 2m crowded field
OLD

icas0j 13309 uvis G 1272 0.0 0.0 - - 1272 9s only noise?, no data
OLD 3013 1.1 3.6 - - 7562 7.5h

j92gc3 10273 wfc RW 106666 4.4 18.1 75403 4.2 72403 10m M31 - crowded field and lots of CRs, no cats
OLD 9710 2.4 2.9 2777 0.0 2777 5.5h + 16s

j9l947 3395 0.1 0.9 - - 3395 27s Looks like lock lost, no PCat only SCat (bug)
OLD 39595 1.9 5.5 68496 0.4 3.9 76840 4h + 5m
* No cats should be produced. Keyword to check?

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-443?focusedCommentId=504751#comment-504751):_

Code has been submitted as Git PR#&#x2060;917.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-443?focusedCommentId=504928#comment-504928):_

Here are some additional datasets to test which had nominal deblend times in the November 2020 processing.

id1k7x ir

j8rce1 wfc

 

These datasets took between 1000-5000 seconds to deblend:

icdm45 uvis
 j97c13 wfc

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-443?focusedCommentId=507180#comment-507180):_

Code and approved and merged Git PR#&#x2060;917.

**Comment by stsci-hack** [comment]
Resolved with #917.
