### ISSUE TITLE
SVM: Clean up FWHM specification

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#852]
_Issue [HLA-447](https://jira.stsci.edu/browse/HLA-447) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The good_fwhm values are currently hard-coded in the build_kernel() method of the CatalogImage class.  These values are also defined in the catalog configuration files.  The values should be read from the configuration files, and the hard-coded settings removed from the code.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-447?focusedCommentId=496826#comment-496826):_

The hard-coded values for the FWHM search range in the build_kernel method of the CatalogImage class have been removed, and the values which are read from the detector-specific configuration files are used instead. These values, as well as the default FWHM value used when no good candidate PSFs are found in the input image, are reported as log.info just before the call to build_auto_kernel.  This is Git PR#&#x2060;872.

**Comment by stsci-hack** [comment]
Resolved with #872.
