### ISSUE TITLE
SVM: Update Drizzlepac automated tests to run cleanly

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#859]
_Issue [HLA-448](https://jira.stsci.edu/browse/HLA-448) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The automated Drizzlepac tests need to be updated to pass based on the latest version of the software in order for the automated release process to work fully, automatically and correctly. 

As reported by M. Rendina:

> This page shows a recent example report of the aggregated tests for the various pipeline components.
> 
> <https://plwishmaster.stsci.edu:8081/job/Releases/job/HCALDP-w-tests/64/testReport/](https://plwishmaster.stsci.edu:8081/job/Releases/job/HCALDP-w-tests/64/testReport/)>
> 
> If this automatic gating objective of a delivery is to be successful, it would be best to either correct the drizzlepac results to passing (preferred), or configure the tests to be skipped so that the overall status of the test suite is passing.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Robert Swaters](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rswaters) on [JIRA](https://jira.stsci.edu/browse/HLA-448?focusedCommentId=496023#comment-496023):_

Need two follow up tickets:
1) determine why the tests were failing
2) add tests for single visit mosaics

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-448?focusedCommentId=498708#comment-498708):_

Initial determination found that the HAP pytests were failing due to issues with the tests themselves.  These are being corrected in a PR to be named later.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-448?focusedCommentId=499159#comment-499159):_

Other tests were found to be failing due to updates to other packages (like STWCS) and need to have their 'truth' files updated to reflect the new updated computations.  These will be corrected under a separate ticket.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-448?focusedCommentId=499164#comment-499164):_

The work for this ticket will be finished under HLA-464, HLA-465, and HLA-466.

**Comment by stsci-hack** [comment]
Fixed with #1185 and #1107.
