### ISSUE TITLE
User can't specify a custom parameter file for SVM processing when executing from the command line

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#860]
_Issue [HLA-449](https://jira.stsci.edu/browse/HLA-449) was created on JIRA by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude):_

Although hapsequencer.py has input arguments that allow the user to specify a custom input parameter file, this functionality can only be utilized via a direct call to hapsequencer.run_hap_processing(). The relevant arguments are not specified inputs in the calls to hapsequencer.run_hap_processing() in runsinglehap.perform() (line 83) or in hapsequencer.main() (line 107).
This makes it impossible for a user to specify a custom parameter file if he or she is executing hapsequencer or runsinglehap from the command line. 

Additionally, remove the 'user_parameters' parameter directory as it really serves no real purpose.

**Comment by stsci-hack** [comment]
Resolved with #896.
