### ISSUE TITLE
Limit discover of sky cells interpret_mvm_input when the cells are specified

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#865]
_Issue [HLA-452](https://jira.stsci.edu/browse/HLA-452) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

In poller_utils.py the interpret_mvm_input method, even when input exposures are only specified for a single sky cell, will discover the exposures overlap other sky cells as well. The search should be limited to the specified sky cell to save resources (memory and processing time).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-452?focusedCommentId=496696#comment-496696):_

This ticket has been completed as Git PR#&#x2060;867.  Since this is a different, short-circuited path through the code to save time and memory resources, the output drizzled files have been compared using this code to output generated using code which does not contain this fix.  The output files were identical.

**Comment by stsci-hack** [comment]
Resolved by #867.
