### ISSUE TITLE
MVM: Revise overloaded constructor for SkyCell class

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#868]
_Issue [HLA-453](https://jira.stsci.edu/browse/HLA-453) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The API for instantiating the SkyCell class currently has a number of parameters which can be provided.  However, when the first parameter is provided, it will ignore the values for all the remaining parameters except the 'scale' parameter.  This 'overloading' of the constructor is prone to user-error or confusion and should be revised to avoid this problem.  

Michele provided the following reference as a pattern to use to revise this interface:

<https://medium.com/@shamir.stav_83310/overloading-constructors-in-python-17e42b7430b6](https://medium.com/@shamir.stav_83310/overloading-constructors-in-python-17e42b7430b6)>

The current interface works, so this work is not critical, but would make the code more robust when being used for manual reprocessing by an end-user.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-453?focusedCommentId=498743#comment-498743):_

This will be addressed with [Drizzlepac PR #&#x2060;878](https://github.com/spacetelescope/drizzlepac/pull/878/files).

**Comment by stsci-hack** [comment]
Resolved by #878.
