### ISSUE TITLE
SVM: Correct logging to include all modules logs in final log file

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#869]
_Issue [HLA-454](https://jira.stsci.edu/browse/HLA-454) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Only log messages from astrodrizzle get included in the full log file created by 'runhapsingle', while log messages from other modules such as 'align_utils' or 'astrometric_utils' apparently are missing.  This needs to be corrected in order to provide a full record of the processing done to the data, especially the number of GAIA sources used for alignment.

**Comment by stsci-hack** [comment]
Partially resolved by #1209.
