### ISSUE TITLE
SVM: Address Segmentation algorithm for low number of sources identified

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#879]
_Issue [HLA-456](https://jira.stsci.edu/browse/HLA-456) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The Segmentation algorithm statistically (see Rick's analysis) finds far fewer sources than the Point algorithm.  This issues needs to be investigated and resolved.

**Comment by stsci-hack** [comment]
Resolved by #895.
