### ISSUE TITLE
SVM: Address Segmentation algorithm for low number of sources identified

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#880]
_Issue [HLA-456](https://jira.stsci.edu/browse/HLA-456) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

The Segmentation algorithm statistically (see Rick's analysis) finds far fewer sources than the Point algorithm.  This issue needs to be investigated and resolved.  The background level and/or associated threshold could be culprits, but it should be remembered both the Point and Segment algorithms use the same background determination.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Robert Swaters](https://jira.stsci.edu/secure/ViewProfile.jspa?name=rswaters) on [JIRA](https://jira.stsci.edu/browse/HLA-456?focusedCommentId=499219#comment-499219):_

1) We have a good set of test cases, ask Rick
2) Explore parameter space, in config files - does this improve the number of sources found? (Normalizing background already improved results, not enough)
3) May require code changes if config changes do not address the issue, but this would be under a new ticket
4) Testing for this ticket will be done with a smaller set, but we need to run the 1000 dataset test as well, possibly together with other tickets (e.g., HLA-457, HLA-458, HLA-443)

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-456?focusedCommentId=499404#comment-499404):_

Testing with dataset 'ia0m04' to determine that the background computation is flagged as returning over-subtracted data.  The tests were resulting only less than 300 sources being identified, while the HLA catalog returned over 1400 sources, and overlaying the catalogs on the image in DS9 confirmed that the difference comes from HAP not identifying the faintest of sources while the HLA catalog includes sources in the diffraction spikes and Airy rings as well.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-456?focusedCommentId=499458#comment-499458):_

This should be addressed with [Drizzlepac PR #&#x2060;895](https://github.com/spacetelescope/drizzlepac/pull/895).  

The changes in that PR revise the computation of the background and how it gets used for determining the sources in the segment catalog; including:

* using the -1 \* RMS of the background as the negative threshold
* removing the 'negative_threshold' parameter from the config files
* updated computation of sigma-clipped background to be less influenced by bright sources
* revising the Background2D parameters for the WFC3/IR format (smaller box size)
* reduced the source box size for the segment catalog sources for all detectors to pick up smaller/fainter sources
* eliminate background subtraction prior to calling photutils segmentation code (avoids applying the background twice)

These changes were tested using dataset 'ia0m04' (hst_11099_04, WFC3/IR). Original HAP segment catalog had <300 sources compared to HLA catalog of >1400 sources. Revised HAP segment catalog now has >1000 sources.

During the investigation of the catalog generation, the skew computation was also evaluated (HLA-457).  The skew computation was working as designed, except it was being overridden (like in this case) by the negative threshold check.  However, there did not appear to be any problems with the skew computation or its use based on initial testing for these changes to the segmentation catalog generation. 

Testing on additional datasets and a thorough review of the code changes still need to be performed before this problem can be considered successfully addressed.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-456?focusedCommentId=501067#comment-501067):_

In addition to the changes noted earlier, it was also discovered that the background was effectively being applied twice for the segmentation map due to not calling 'np.nan_to_num' correctly and inadvertently background-subtracting the original input image during point-source catalog generation.  All instances of this function were revised to get the calling sequence correct to always work on copies of the input and avoid the same confusion when maintaining this code. 

It was also discovered that the filter_kernel being used in creating the segmentation map was smoothing the input images a little too much resulting in sources more like point sources and not extended from being identified.  A much smaller more generic kernel based on the image-generated kernel FWHM was implemented instead resulting in more extended sources being identified as noted in the photutils docs. 

The logic for how to apply the skew computation was also inverted so that larger skew values triggered computation and use of the full 2D background.  This should make for the expected use of the backgrounds for all the different fields.

Fixing these issues while also separating the parameters for setting 'nsigma' (used for computing the detection threshold from the background) resolved nearly all the problems with the segmentation detection.  

These issues were all resolved when [Drizzlepac PR #&#x2060;895](https://github.com/spacetelescope/drizzlepac/pull/895) was merged in after being tested on datasets `ia0m04` and `j92c01`.

**Comment by stsci-hack** [comment]
Resolved with #895.
