### ISSUE TITLE
SVM: Re-evaluate the skewness discriminant

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#881]
_Issue [HLA-457](https://jira.stsci.edu/browse/HLA-457) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Currently, a skewness computation is used as the discriminant between a full two-dimensional background fit determination and using sigma-clipped statistics to determine the mean, median, and rms values to represent the background (median) and  background_rms (rms) of the input image.  In the latter case, the skew is computed [3 * (mean - median)/rms] and compared against a threshold which acts as the discriminant between the use of the two different computations.

The work for this ticket should focus on determining whether this discriminant allows the correct background to be used for the various types of fields, or whether the limit of 0.5 is correct or needs to be adjusted, or whether this computation needs to be removed altogether instead.  This will require evaluating what type background was selected for use for a large number of datasets like the 1000 dataset tests after being updated with the latest sky computation changes.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-457?focusedCommentId=498856#comment-498856):_

Here are some notes on datasets where the skew was computed.  These datasets span different types of fields in order to try to understand how the skew varies. 

# j900a5010_drc
* nebula fills the entire frame
* skew: 0.9282
# ib6w62 (hst_11360_62_wfc3_uvis_total_ib6w62_drc.fits):  mostly empty, localized nebulosity
*  skew: -0.08467
# icnw34 (hst_13691_34_wfc3_ir_total_icnw34_drz.fits)
*  crowded stellar field
*  skew: 0.8697
# j8ca07 (hst_9029_07_acs_hrc_f775w_drz.fits)
*  single PSF in otherwise empty field
*  skew: -0.1439
# j8cw03 (hst_8992_03_acs_wfc_total_j8cw03_drc.fits)
* Tadpole galaxy field
* skew: 2.6965
# jbnw02 (hst_12388_02_acs_sbc_f122m_drz.fits)
*  about 35 scattered point-sources in otherwise empty field 
* skew: -0.7977
# jbpb05 (hst_12549_05_acs_wfc_f606w_drz.fits)
*  low S/N, extragalactic field with numerous sources(HLA point cat: 853 sources)
*  skew: 2.7686
*  skew of background: 0.06696

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-457?focusedCommentId=499460#comment-499460):_

The skew computation was evaluated as part of the investigation for HLA-456 (segmentation catalog generation).  No problems were seen except that the background values used to compute the skew could be compromised by the clipping done to compute the background in the first place.  In addition, when the skew was being computed correctly, its use was also getting overridden by an overly aggressive setting of the negative threshold (corrected under HLA-456 and [Drizzlepac PR #&#x2060;895](https://github.com/spacetelescope/drizzlepac/pull/895)).  

Evaluation of the updated results based on HLA-456 on different types of fields (like those listed above) would still be necessary to insure that no additional issues remain with the computation or use of the skew.

**Comment by stsci-hack** [comment]
Logic for when to use 2D background based on the skew was inverted in #895.  This will impact the evaluation needed to close this issue.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-457?focusedCommentId=504305#comment-504305):_

Changes to how the skew gets used to determine what background should be applied was included in [Drizzlepac PR #&#x2060;895](https://github.com/spacetelescope/drizzlepac/pull/895) (which has been closed), then tested and refined as part of [Drizzlepac PR #&#x2060;903.](https://github.com/spacetelescope/drizzlepac/pull/903) Testing under #&#x2060;903 did not show any problems.  The testing was performed using datasets 'icnw34' (WFC3/IR), 'ibe809' (WFC3/UVIS), 'jbnw02' (ACS/WFC) and 'jbpb05' (ACS/SBC).

**Comment by stsci-hack** [comment]
Resolved with #895 and #903.
