### ISSUE TITLE
SVM: Fix two specific catalog bugs found during testing

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#882]
_Issue [HLA-458](https://jira.stsci.edu/browse/HLA-458) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

During testing with cataloging ON, two new problems were found:
 # AttributeError: 'HAPPointCatalog' object has no attribute 'is_big_island' (for acs_8e6_09, acs_8n2_14, acs_bag_03, and more)
 # ValueError: input tables for join must both have at least one row (for acs_8zo_02)

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-458?focusedCommentId=499397#comment-499397):_

Bug 1 is an easy fix and has been addressed.

Bug 2 has two aspects: (a) why are so few sources found (segmentation) and (b) what happens if the filter catalogs have entries, but the total catalog has none?  The (a) issue can be addressed later when overall improvements to the algorithm are done.  The (b) issue should be discussed. Currently an "inner" join is done to combine the data from the *total* and *filter* tables. Is this the best solution?  Regardless, the actual bug needs to be trapped.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-458?focusedCommentId=499686#comment-499686):_

Bug 1: Fixed test for "big island" message as it only applies for the segmentation algorithm.


 Bug2: Modified join of specified filter columns to be added to the total catalog - now a "left"
 join. Modified construction of Point total catalog with respect to the RA and Dec columns
 to ensure these columns are always present and totally populated. This change was necessitated
 by the change to the type of join now being performed.

These fixes are Git PR#&#x2060;898 awaiting review.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-458?focusedCommentId=499909#comment-499909):_

PR approved and code merged onto master.

**Comment by stsci-hack** [comment]
Resolved with #898 .
