### ISSUE TITLE
SVM: Determine cause of GAIA alignment failures for ACS/HRC

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#884]
_Issue [HLA-460](https://jira.stsci.edu/browse/HLA-460) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Despite having enough GAIA sources in the field, only a small fraction of ACS/HRC fields actually get aligned to GAIA.  Explanations for these failures should be determined, and if possible, addressed in the code and/or parameter settings for alignment to GAIA.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-460?focusedCommentId=498832#comment-498832):_

An example of alignment failure in ACS/HRC data has been identified by the HAP/HLA team for  [j8qy21 (hst_9974_21_acs_hrc) on Slack](https://stsci.slack.com/archives/GH3GNJ6QZ/p1607023334319700).  This dataset should be evaluated to understand the reason for this unexpected failure to align to GAIA.

**Comment by stsci-hack** [comment]
Closed based on alignment under v3.3.1.
