### ISSUE TITLE
SVM: Determine cause of GAIA alignment failures for ACS/SBC

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#885]
_Issue [HLA-461](https://jira.stsci.edu/browse/HLA-461) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Despite having enough GAIA sources in the field, only a small fraction of ACS/SBC fields actually get aligned to GAIA.  Explanations for these failures should be determined, and if possible, addressed in the code and/or parameter settings for alignment to GAIA.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-461?focusedCommentId=566226#comment-566226):_

Many alignment issues have already been addressed up through v3.3.1.  Additional issues will be resolved under HLA-691.

**Comment by stsci-hack** [comment]
Resolved through (at least) #1262.
