### ISSUE TITLE
SVM: Determine cause of GAIA alignment failures for WFC3/IR

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#887]
_Issue [HLA-462](https://jira.stsci.edu/browse/HLA-462) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Despite having enough GAIA sources in the field, only a small fraction of WFC3/IR fields actually get aligned to GAIA.  Explanations for these failures should be determined, and if possible, addressed in the code and/or parameter settings for alignment to GAIA.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-462?focusedCommentId=566227#comment-566227):_

Many alignment issues have already been addressed up through v3.3.1.  Additional issues will be resolved under HLA-690.

**Comment by stsci-hack** [comment]
Resolved by #1243.
