### ISSUE TITLE
SVM: update truth files for older drizzlepac tests

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#892]
_Issue [HLA-466](https://jira.stsci.edu/browse/HLA-466) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The 'truth' files need to be updated for the standard pipeline Drizzlepac regression tests.

Although these tests are not SVM tests, they are used as part of the automated release system for build a release of the code used for the SVM and MVM pipelines as noted by M. Rendina:

> This page shows a recent example report of the aggregated tests for the various pipeline components.
> 
> <https://plwishmaster.stsci.edu:8081/job/Releases/job/HCALDP-w-tests/64/testReport/>
> 
> If this automatic gating objective of a delivery is to be successful, it would be best to either correct the drizzlepac results to passing (preferred), or configure the tests to be skipped so that the overall status of the test suite is passing.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-466?focusedCommentId=550505#comment-550505):_

Pytest regression tests were updated as part of [Drizzlepac PR #&#x2060;1107](https://github.com/spacetelescope/drizzlepac/pull/1107).

**Comment by stsci-hack** [comment]
Resolved by #1107.
