### ISSUE TITLE
SVM: Address incomplete catalog due to bright sources (smiley faces)

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#893]
_Issue [HLA-467](https://jira.stsci.edu/browse/HLA-467) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

HLA flagging around bright sources often leads to not adding sources to the catalog.

New code has already been implemented for a new TinyTim PSF based source-finding algorithm to replace photutil's DAOFindStar/IRAFFindStar algorithms.  This new algorithm avoids (mostly?) identifying peaks in Airy rings and diffraction spikes as sources that were being flagged by the HLA flagging code as 'swarm' sources.   As a result, the HLA swarm flagging can be turned off (ideally).  This will resolve the problem with point catalogs resulting in rings of avoidance around bright sources (as seen in [the 'smiley face' example provided by INS on Slack ](https://stsci.slack.com/archives/GH3GNJ6QZ/p1605034180272600) for dataset `ib4103`).

This ticket's focus would be on calling the new source finding algorithm for point catalogs that use the new TinyTim source finding routine and verifying that it resolves the 'smiley face' catalog problem. If the problem persists in some datasets, then we will file a new ticket.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-467?focusedCommentId=503737#comment-503737):_

[Drizzlepac PR #&#x2060;903](https://github.com/spacetelescope/drizzlepac/pull/903) has been submitted to use the new PSF-based version of DAOFind to generate the point-source catalog by default.  This new algorithm is only another option which is selected by default for pipeline use, as opposed to replacing the previous algorithms.  The new code was originally developed using visit `ib4103` as the test dataset, and will need to be tested on additional visits to confirm its affect on the point-source catalog creation on all types of images from all detectors.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-467?focusedCommentId=507101#comment-507101):_

One feature of this new source identification algorithm that came out as a result of the testing is that larger PSFs are needed for more heavily saturated image sources. These larger PSFs need to be 2 as large in radius compared to the current set of PSFs in order to eliminate 'swarm'-sources farther from the core of the star.  Larger PSFs could be added to the code only for the most heavily used wide-band filters to catch the majority of the heavily saturated sources while keeping the source code repo size as small as possible.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-467?focusedCommentId=507264#comment-507264):_

[Drizzlepac PR #&#x2060;893](https://github.com/spacetelescope/drizzlepac/pull/903) was merged to use the PSF-based algorithm for creating the point-source catalogs.

HLA-485 has been added to document the evaluation of this new algorithm on the 1200 dataset test run on hlalab1 after it has been run.

**Comment by stsci-hack** [comment]
Resolved by #893 and #903.
