### ISSUE TITLE
SVM: Investigate the NaNs in the output catalogs

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#897]
_Issue [HLA-468](https://jira.stsci.edu/browse/HLA-468) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Both the Point and Segment catalogs contain NaN values where it seems the source was detected, but the measuring algorithms were unable to make viable measurements.  This issue should be investigated and rectified if possible.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-468?focusedCommentId=522277#comment-522277):_

This ticket is superseded by HLA-524.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-468?focusedCommentId=522278#comment-522278):_

Ticket superseded by HLA-524.

**Comment by stsci-hack** [comment]
Ultimately resolved by #1162
