### ISSUE TITLE
SVM: Process data with identical fields-of-view

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#908]
_Issue [HLA-473](https://jira.stsci.edu/browse/HLA-473) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

As reported by Tom Bair on 7-Jan-2021:

bq. ACS_969_01 failed this morning in HAP_SVM. I filed a JIRA ticket DPASMET-203 to document this event.

Discussing the cause of this Exception with Mihai, it turns out the sky matching code has a known and apparently insoluble failure mode triggered by this dataset related to exactly overlapping exposures.   The best available solution would be to update Drizzlepac itself to look for and catch this specific Exception and change the sky matching mode.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-473?focusedCommentId=503288#comment-503288):_

A new pytest needs to be added to provide test coverage for this error case.  A suitable test would include data which has CR-SPLIT or similarly exactly overlapping observations.  Ideally, new tests should be added for both standard pipeline processing as well as SVM mode testing, however, the minimum for this ticket would be to just cover the case that triggered this failure in pipeline processing (see DPASMET-203).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-473?focusedCommentId=527154#comment-527154):_

[Drizzlepac PR #&#x2060;1002](https://github.com/spacetelescope/drizzlepac/pull/1002) was merged on 08/Apr/2021 to iterate over the sky subtraction modes in the event that the sky matching algorithm triggered an Exception these types of datasets.

**Comment by stsci-hack** [comment]
Resolved with #1002.
