### ISSUE TITLE
Support updated IDCTAB WCSs

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#909]
_Issue [HLA-474](https://jira.stsci.edu/browse/HLA-474) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The logic in standard pipeline processing of HST imaging data turns out to not correctly use the latest distortion model information when the IDCTAB reference file specified in the header is newer than the IDCTABs used for WCSs retrieved from the astrometry database.  

This logic needs to be revised to be based on the latest distortion model specified for an exposure/file when computing the 'best' alignment available, especially when performing a posteriori fitting. 

INS input will be required to define this new logic to meet their expectations for pipeline processing.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-474?focusedCommentId=502888#comment-502888):_

A discussion with INS (Mack, Bajaj, and Avila) came to the following decisions:
 * the pipeline-default should always (and currently does) get defined based on the IDCTAB specified in the header (the latest, newest)
 * the a priori solution should be defined based on the newest IDCTAB
 ** For data taken after Oct-2017, the pipeline-default solution is a valid a priori solution based on GSC240, so the pipeline-default can be used as-is (assuming it passes its own verification of relative alignment)
 ** For data taken before Oct-2017, the offset applied to create the GSC240 solution based on a previous IDCTAB should be extracted and used to create a new GSC240 solution and run through verification of relative alignment. 
 ** Failure to verify alignment would cause pipeline-default to be used instead.
 * The a posteriori fit should be performed based on the same IDCTAB as the pipeline-default WCS.  
 ** Failure to align with an a posteriori fit would default to verified a priori or pipeline-default based on newest IDCTAB.

The discussion also came to the decision to request a change to the astrometry database to only return the solutions based on the most recent distortion model by default, and a separate switch/parameter would be defined to request all WCSs including those based on older IDCTABs.  It is not clear whether this is viable, but we will work with ASB to see what is possible.  

The updated logic will need to be implemented in 'runastrodriz' for basic pipeline use.  Data taken before the new IDCTAB was started to be used operationally will most likely need to be reprocessed with these changes in order to insure that the latest IDCTAB gets used to define the WCS for the 'older' data.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-474?focusedCommentId=502912#comment-502912):_

A discussion about these issues with Brian McLean resulted in:
 * Brian will provide the call to a web service which will return the offsets used to correct the guide star coordinates used for an exposure to align with the GAIA/ICRS frame.  
 * The pipeline code can more easily select what headerlet solutions from the database should be appended to the exposure, and will be updated to only apply the data from the most recent IDCTAB solutions.  

The only uncertain aspect of all this is whether or not multiple headerlet files can be generated during pipeline processing or reprocessing and correctly passed along one at a time to the astrometry database so that it can be updated with all the latest IDCTAB solutions.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Roberto Avila](https://jira.stsci.edu/secure/ViewProfile.jspa?name=avila) on [JIRA](https://jira.stsci.edu/browse/HLA-474?focusedCommentId=503632#comment-503632):_

I'm not sure if we have a problem with the data that is currently in the archive. Below is a table of information extracted from the yearly 47Tuc calibration observations. It looks like all but the latest images are using an incorrect IDCTAB. There are 3 IDCTABs for this kind of image, 4bb1536*idc.fits, and they were all activated before these images were re-processed.

 

`Filename date-obs date wcsname`

`hst_9443_01_acs_wfc_f606w_j6ll01yc_flc.fits 2002-07-07 2020-12-20 IDC_0461802ej-FIT_SVM_GAIADR2`
 `hst_9656_25_acs_wfc_f606w_j8hw25i3_flc.fits 2003-07-06 2020-12-22 IDC_0461802ej-FIT_SVM_GAIADR2`
 `hst_10048_c3_acs_wfc_f606w_j8urc3k0_flc.fits 2004-06-01 2020-12-24 IDC_0461802ej-FIT_SVM_GAIADR2`
 `hst_10375_c3_acs_wfc_f606w_j94rc3od_flc.fits 2005-06-08 2020-12-25 IDC_0461802ej-FIT_SVM_GAIADR2`
 `hst_10737_w4_acs_wfc_f606w_j9irw4ax_flc.fits 2006-07-08 2020-12-18 IDC_0461802ej-FIT_REL_GAIADR1`
 `hst_11397_w2_acs_wfc_f606w_ja9bw2zw_flc.fits 2009-07-09 2020-12-28 IDC_0461802dj-FIT_SVM_GAIADR2`
 `hst_11677_06_acs_wfc_f606w_jb6v06c3_flc.fits 2010-06-12 2020-12-28 IDC_0461802dj-FIT_SVM_GAIADR2`
 `hst_12389_03_acs_wfc_f606w_jbms03ol_flc.fits 2011-07-05 2020-12-30 IDC_0461802dj-FIT_SVM_GAIADR2`
 `hst_12734_03_acs_wfc_f606w_jbva03jc_flc.fits 2012-07-17 2020-12-31 IDC_0461802dj-FIT_SVM_GAIADR2`
 `hst_13159_03_acs_wfc_f606w_jc5003fp_flc.fits 2013-06-29 2020-12-31 IDC_0461802dj-FIT_SVM_GAIADR2`
 `hst_13596_03_acs_wfc_f606w_jce503bk_flc.fits 2014-07-07 2021-01-01 IDC_0461802dj-FIT_SVM_GAIADR2`
 `hst_13673_02_acs_wfc_f606w_jck302p3_flc.fits 2015-05-31 2021-01-01 IDC_0461802dj-FIT_SVM_GAIADR2`
 `hst_14402_15_acs_wfc_f606w_jd0q15hz_flc.fits 2016-08-02 2021-01-02 IDC_0461802dj-FIT_SVM_GAIADR2`
 `hst_14511_03_acs_wfc_f606w_jd5703jd_flc.fits 2017-07-11 2021-01-02 IDC_11d1433lj-FIT_SVM_GAIADR2`
 `hst_14949_01_acs_wfc_f606w_jdg301c4_flc.fits 2018-06-22 2021-01-03 IDC_11d1433lj-FIT_SVM_GAIADR2`
 `hst_15522_02_acs_wfc_f606w_jdw002g3_flc.fits 2019-07-01 2021-01-03 IDC_11d1433lj-FIT_SVM_GAIADR2`
 `hst_15760_01_acs_wfc_f606w_je5v01nm_flc.fits 2020-09-02 2021-01-04 IDC_11d1433lj-FIT_SVM_GAIADR2`
 `hst_16384_01_acs_wfc_f606w_jee301bn_flc.fits 2020-11-23 2021-01-04 IDC_4bb1536mj-FIT_SVM_GAIADR2`

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Roberto Avila](https://jira.stsci.edu/secure/ViewProfile.jspa?name=avila) on [JIRA](https://jira.stsci.edu/browse/HLA-474?focusedCommentId=504161#comment-504161):_

I should have checked before, but the problem with the images above doesn't seem to be HAP related. For some reason the IDCTAB is not being assigned correctly, so this looks like something I should take up with DMS/Redcat team. So you can ignore my report from above.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-474?focusedCommentId=509364#comment-509364):_

Support for new IDCTAB reference files was added to [STWCS PR #&#x2060;170](https://github.com/spacetelescope/stwcs/pull/170) and [STWCS PR #&#x2060;172](https://github.com/spacetelescope/stwcs/pull/172).  These PRs have been merged into STWCS and computes a new a priori WCS based on the new IDCTAB (new as in 'not found in the astrometry database').  This will insure that standard pipeline processing will result in new a priori WCSs that can be used as input to SVM processing as well as the basis for new a posteriori fits in the standard pipeline.  

This can be closed once we confirm that this works as intended on our test of 1000 datasets prior to delivery to the next HSTSDP build.

**Comment by stsci-hack** [comment]
Resolved with #922 , as well as related STWCS PRs 170 and 172.
