### ISSUE TITLE
Tests failed at "if errorobj" in util.py

### ISSUE THREAD

**Issue by pllim** [spacetelescope/drizzlepac#91]
See https://ssb.stsci.edu/pandokia/pandokia.cgi?query=treewalk&context=dev%3A3.5.4&host=nott&project=drizzlepac&test_run=conda-conda_tests_py3_2017-10-24-10%3A30%3A01&status=E

```
Trailer file written to:  astrodrizzle.log

  File "/srv/iraf/bldtmp/pO5n/p/envs/dev/lib/python3.5/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/srv/iraf/bldtmp/pO5n/p/envs/dev/lib/python3.5/unittest/case.py", line 605, in run
    testMethod()
  File "/srv/iraf/bldtmp/pO5n/p/envs/dev/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/srv/rt/betadrizzle/vary_perf/wfc3_binned_asn/inmemory.on_parallel.off/run.py", line 70, in test
    astrodrizzle.AstroDrizzle(input_files, mdriztab=False, configobj=cfg_fname)
  File "/srv/iraf/bldtmp/pO5n/p/envs/dev/lib/python3.5/site-packages/drizzlepac/astrodrizzle.py", line 123, in AstroDrizzle
    run(configObj, wcsmap=wcsmap)
  File "/srv/iraf/bldtmp/pO5n/p/envs/dev/lib/python3.5/site-packages/drizzlepac/util.py", line 228, in wrapper
    if errorobj:
None
```

**Comment by mcara** [comment]
All the failing tests are failing for the same reason as yesterday and https://github.com/spacetelescope/stsci.skypac/pull/19 was supposed to fix them. Same fix as in `utils.py` - see https://github.com/spacetelescope/stsci.skypac/pull/19/files#diff-fd30fc76245b9aff098bb9340d0c035bR27 - was supposed to be in in `skymatch.py` as well but for unknown to me reasons did not get into the commit (I know I put the fix there... maybe I just forgot to save the file before making a commit?). So the fix should be in `stsci.skypac`. Working on it...

**Comment by pllim** [comment]
Well, the failures are from yesterday's run. So if you think it has been fixed but just didn't get pick up, you may also opt to wait one more day for today's results.

**Comment by mcara** [comment]
Actually, I know I had the fix yesterday because the code was installing and running fine on my machine. I do not understand why it did not get into the PR https://github.com/spacetelescope/stsci.skypac/pull/19... Did I forget to `git add`???

**Comment by pllim** [comment]
Hmm. If you still have that branch locally, you can do a `git status` and see.

**Comment by mcara** [comment]
@pllim Should be fixed by https://github.com/spacetelescope/stsci.skypac/pull/20

**Comment by pllim** [comment]
Thanks for the quick fix. Note that you will see this failure in tomorrow's report of today's run, so you have to wait 2 days for the email to catch this.
