### ISSUE TITLE
MVM:  Define work for verification of alignment

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#912]
_Issue [HLA-475](https://jira.stsci.edu/browse/HLA-475) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The effort to implement verification of alignment of the data during MVM processing (as described in HLA-390) requires significant modifications to the logic within the MVM processing code as well as adding new algorithms. 

This ticket will cover the effort necessary to define exactly what changes need to be implemented and to define the steps needed to implement those changes with each step being suitable for a separate ticket.

**Comment by stsci-hack** [comment]
Alignment of MVM products will not be done and will rely exclusively on SVM alignment to account for proper motion of sources in the exposures over time.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-475?focusedCommentId=606120#comment-606120):_

Alignment of MVM products will not be done and will rely exclusively on SVM alignment to account for proper motion of sources in the exposures over time.
