### ISSUE TITLE
Fix drizzlepac regression tests on Jenkins

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#914]
_Issue [HLA-476](https://jira.stsci.edu/browse/HLA-476) was created on JIRA by [Nadia Dencheva](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dencheva):_

Drizzlepac tests on plwishmaster have been failing for a while and need to be fixed and reset

**Comment by stsci-hack** [comment]
Resolved with #915 and #916 .
