### ISSUE TITLE
SVM: Only Segment catalog generated

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#920]
_Issue [HLA-479](https://jira.stsci.edu/browse/HLA-479) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Found with dataset j9l947 where the Point algorithm finds no sources in the total image, so no further processing is done.  However, the Segment algorithm believes it is finding sources, so the processing continues.  This is deliberate logic in the hapsequencer, but this logic was put in place before the cross matching checking was emplaced.  Is this still the logic that is wanted?

FYI: It looks as though lock was lost during this visit as all of the sources are trailed.

The goal of this ticket is to identify the path forward, and to file ticket(s) to implement the desired solution.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-479?focusedCommentId=550976#comment-550976):_

The decision was made to insure that both point and segment catalogs are always generated, even if one or both are empty.  This was implemented under [Drizzlepac PR #&#x2060;1122](https://github.com/spacetelescope/drizzlepac/pull/1122).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-479?focusedCommentId=550977#comment-550977):_

The decision was made to insure that both point and segment catalogs are always generated, even if one or both are empty.  This was implemented under [Drizzlepac PR #&#x2060;1122](https://github.com/spacetelescope/drizzlepac/pull/1122).

**Comment by stsci-hack** [comment]
Resolved with #1122.
