### ISSUE TITLE
SVM: ACS and WFC3 ramp images should only be processed to the exposure level

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#921]
_Issue [HLA-480](https://jira.stsci.edu/browse/HLA-480) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

RLW note in Slack on 19 Jan 2021: In HAP ramp filter images have a combined drizzled image and a detection image.  That's really a mistake.  In many cases these ramp filters are using different central wavelength settings, meaning that they are effectively different filters; but they all get combined into a single HAP image.  An example is visit jbma01, which has 8 fr782n exposures, 4 at wavelength 7674 and 4 at 7637.  In HAP those all get combined into a single HAP image (hst_12371_01_acs_wfc_fr782n_jbma01_drz.fits) plus a detection image.  In the HLA there are only the 8 exposure-level products.I think the HLA approach of never combining ramp filter images is correct here, so the HAP logic should be changed to omit the combined image for FR filters and to omit ramp filters from the total (detection) image.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-480?focusedCommentId=505378#comment-505378):_

IBH602051 (21 Jan 2021)

Each quadrant is a different wavelength and requires a unique zeropoint. Typically, the user selects only a subarray of the quadrant of interest, but in some cases the images are full frame. This means the S/N will vary over the image and the detection image and catalogs might not be ideal.

I don't think I was aware of those!  It seems to me they are in the same category as the ramp filters, where they should not be included in the detection image and probably should not have combined images produced at all.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-480?focusedCommentId=509856#comment-509856):_

This is Git PR#&#x2060;543.  After much discussion, the Ramp filters will be processed only to the alignment to Gaia stage.  The subarray Quad filters will be fully processed as they are now.  It is the full-frame Quad filters which can be problematic, but there is real benefit to processing the subarray Quad filters.  The number of full-frame Quad filter observations is comparatively small.  Removing them from the processing can be addressed in a different issue as necessary.

**Comment by stsci-hack** [comment]
Resolved with #543.
