### ISSUE TITLE
Add keyword DRIZPARS to Drizzled Products pointing to the AstroDrizzle logfile 

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#924]
_Issue [HLA-482](https://jira.stsci.edu/browse/HLA-482) was created on JIRA by [Jennifer Mack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mack):_

AstroDrizzle parameter settings are difficult to determine from the image headers. 

Currently this is only possible by reading the 'MDRIZTAB' keyword and downloading the FITS reference file. This table is difficult to read, and it contains only parameter values but no description. 

Since the logfiles for the HST and HAP products capture both parameter settings and the code I/O, we propose to add a keyword pointing users to these logfiles. These are very useful for comparing parameters in different versions of drizzled products, for example: when an instrument team updates the MDRIZTAB or when users want to compare HST/HAP products. 

For example, in the two products below, the logfiles show that standard and SVM products for WFC3/UVIS use different sky background methods, and INS may decide to update the MDRIZTABs so that the two are consistent. 
```
HST skymethod : localmin   iedd01020_log.txt
HAP skymethod : match      hst_16284_01_wfc3_uvis_f475w_iedd01_trl.txt ```
 

Below is a list of 'txt' files produced for one associated dataset and their contents. We only want to highlight the AstroDrizzle parameters, so the first 4 files wouldn't be used.

 
```
iedd01p0q_log.txt - CALWF3 only
iedd01p2q_log.txt - CALWF3 only
iedd01p4q_log.txt - CALWF3 only
iedd01p6q_log.txt - CALWF3 only
iedd01020_log.txt - CALWF3 + AstroDrizzle

hst_16284_01_wfc3_uvis_f475w_iedd01_trl.txt   - AstroDrizzle only
hst_16284_01_wfc3_uvis_f475w_iedd01p0_trl.txt - AstroDrizzle
hst_16284_01_wfc3_uvis_f475w_iedd01p2_trl.txt - AstroDrizzle
hst_16284_01_wfc3_uvis_f475w_iedd01p4_trl.txt - AstroDrizzle
hst_16284_01_wfc3_uvis_f475w_iedd01p6_trl.txt - AstroDrizzle
hst_16284_01_wfc3_uvis_total_iedd01_trl.txt   - AstroDrizzle
```

**Comment by stsci-hack** [comment]
Linked to #934

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-482?focusedCommentId=508580#comment-508580):_

[Drizzlepac PR #&#x2060;934](https://github.com/spacetelescope/drizzlepac/pull/934) has been submitted to add this keyword to the Drizzle product primary header. Testing will need to be done with the SVM processing to insure that the correct name gets used for the value of this keyword.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-482?focusedCommentId=508795#comment-508795):_

As of [`8ff85fb`](https://github.com/spacetelescope/drizzlepac/commit/8ff85fb0047fffe667ebd06ec42b99bb2fad75de), the changes have been verified by processing:
 * SVM processing: ib2t06
 * runastrodriz (pipeline) processing: j9io03040
 * stand-alone drizzling: j9io03040

This verified that AstroDrizzle will put the correct value of the trailer file in the trailer file itself, as well as the DRIZPARS keyword. Both 'runastrodriz' and SVM processing ('hapsequencer') set up a temp file then build up the final trailer file from all the temp files, so those scripts update the DRIZPARS keyword on their own using the filenames they define for the trailer files. In addition, Flake8 updates were performed on both drizzlepac/util and drizzlepac/astrodrizzle since they were being edited for this PR anyway.
