### ISSUE TITLE
Astrodrizzle sets EXPTIME to 1 in single sci images

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#93]
A user reported - see Footprints ticket no. 10636 - that `astrodrizzle` sets `EXPTIME` keyword to 1 in the header of single sci images. This is an important keyword to have in single sci images and in the past `astrodrizzle` used to write out correct value of `EXPTIME`. However, staring with [r45809](https://trac.stsci.edu/ssb/stsci_python/changeset/45809/drizzlepac/trunk) or, alternatively, [this github adaptation](https://github.com/spacetelescope/drizzlepac/commit/fa70e27c77c5c9d1224bb15d26268ca5433af1e9#diff-1ec325ef04e8462150c016437086037cR137), `astrodrizzle` started setting `EXPTIME` to 1 for unknown to me reasons.

@stsci-hack What was the reason for setting `EXPTIME` to 1 in [r45809](https://trac.stsci.edu/ssb/stsci_python/changeset/45809/drizzlepac/trunk) and can we revert to the original code?

**Comment by pllim** [comment]
My very fuzzy memory from back in the days when it was still called "MultiDrizzle" and back when we drizzled WFPC2 data recalled that `EXPTIME` is set to 1 sec when output `BUNIT` is electrons/s because the data itself is already divided by exposure time. Is that not the case anymore?

**Comment by mcara** [comment]
@pllim That different from my memory. In addition, `EXPTIME` is still an important quantity even when image data are converted to rate - one cannot convert 'rate' to 'counts' without `EXPTIME`.

**Comment by pllim** [comment]
True... Maybe I misremembered. 🙈

**Comment by mackjenn** [comment]
I am running AstroDrizzle Version 2.1.18 and the exptime keyword is appropriately set in the final_drc_sci.fits image.

**Comment by mcara** [comment]
@mackjenn Indeed it is. This issue is not about `EXPTIME` in the *final* image but rather about its value in *single_sci* images. Check the `EXPTIME` in your `*single_sci.fits` images.

**Comment by mackjenn** [comment]
Ohhhh, yes.  It is set to 1.0.  I never noticed. (Don't use those)

**Comment by mcara** [comment]
No one noticed for 2 years: either not many people use them or learned how to work around this issue.

**Comment by pllim** [comment]
What is the `BUNIT` for `single_sci`? Is it electrons/s?

**Comment by mackjenn** [comment]
electrons/sec

**Comment by pllim** [comment]
That aligns with my fuzzy recollection, but only @stsci-hack knows for sure.

**Comment by mcara** [comment]
For UVIS images it is `'ELECTRONS/S'` but not necessarily: I think it can be 'electrons' for some instruments if `proc_unit` parameter is set to `'native'`.

**Comment by mcara** [comment]
Nope... I was wrong: setting `proc_unit` to `'electrons'` has no effect.

**Comment by pllim** [comment]
Since `single_sci` is used for the drizzling part, I think they *have* to be in electrons/s always. Otherwise, you will be drizzling different count rates together, no?

To convert `single_sci` back to electrons, you should still be able to grab the original `EXPTIME` from the corresponding FLT image.

Anyways, I am just guessing around. Feel free to ignore if it doesn't make sense.

**Comment by bernie-simon** [comment]
> On Oct 31, 2017, at 12:48 PM, P. L. Lim <notifications@github.com> wrote:
> 
> Since single_sci is used for the drizzling part, I think they have to be in electrons/s always. Otherwise, you will be drizzling different count rates together, no?

If the input units to drizzle are not counts per second, the code divdes the image by the exposure time.

**Comment by mcara** [comment]
@mackjenn Do you happen to know what is the difference between `proc_unit` parameter and `final_units`?

Description for `proc_unit`:

> The units to be used for the final output drizzled product. Valid values and definitions are:
> * **native**: Output DRZ product and input 'values' given in the native units of the input image.
> * **electrons**: Output DRZ product and input 'values' given in units of electrons. 

Description for `final_units`:

> This parameter determines the units of the final drizzle-combined image, and can either be ‘counts’ or ‘cps’. It is passed through to ‘drizzle’ in the final drizzle step.

Can someone, please, explain what is the difference between "final output drizzled product" and "final drizzle-combined image"?

**Comment by stsci-hack** [comment]
The definition of 'proc_unit' stems from the time when drizzlepac would perform cosmic-ray detection in either electrons or counts.  We made the change to the code a few years ago to always convert the input data to electrons for purposes of all internal processing.  

The 'final_units' parameter, on the other hand, allowed the user to specify what units the "final output drizzled product" (also known as "final drizzle-combined image").  This performed more computations when the input was not always converted to electrons as it is now, but it still controls whether the output is in units of counts or count/rate.

**Comment by mcara** [comment]
Fixed via https://github.com/spacetelescope/drizzlepac/pull/99
