### ISSUE TITLE
SVM: Evaluate 1k dataset test results for point-catalog issues

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#930]
_Issue [HLA-485](https://jira.stsci.edu/browse/HLA-485) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The changes implemented under HLA-467 dramatically changed how point-sources are identified when creating the point-source catalog.  Although initial testing indicated that this new algorithm works fairly effectively, there may still be cases where it requires improvement.  

Therefore, the results of running the 1200 dataset test on hlalab1 need to be evaluated after running with the new code to identify any cases where this new algorithm fails to produce a point-catalog consistent with the HLA results.  Any error condition should be documented here and used to define a new PR to resolve those lingering issue.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-485?focusedCommentId=510720#comment-510720):_

Initial analysis of the exceptions thrown during the first run of these 1k datasets found the following errors:
 * problem with handling of Grism data crossed with direct image filters (G800L + F814W, for example)
 * errors in creating the astrometric reference catalog during alignment
 * not finding PSFs for point-source catalog generation (nearly all datasets quit early due to this error)

The problem with finding the PSFs simply came as a result of `setup.py` for Drizzlepac not including the new PSF directories as part of the installation process, and NOT a problem with the code itself. 

PRs will be submitted to address the rest of the issues found.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-485?focusedCommentId=510769#comment-510769):_

[Drizzlepac PR #&#x2060;942](https://github.com/spacetelescope/drizzlepac/pull/942) has been submitted to address problems with the PSFs and the creation of the reference catalog.  The fix for the reference catalog will need to be backed out once STWCS has been updated with the real fix; namely, to get it to support multiple inputs instead of just a single file.  

In addition, this PR includes a fix for the code to better interpret the filter names in the input exposures so that the correct PSF can be found on disk for use in build the point-catalog.  This error was hidden behind the other PSF error (directories not installed).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-485?focusedCommentId=512766#comment-512766):_

A few PRs have been submitted to (try to) correct the issues found in the results_2021-02-19 test; specifically, 
 [Drizzlepac PR #&#x2060;950](https://github.com/spacetelescope/drizzlepac/pull/950)
 [Drizzlepac PR #&#x2060;946](https://github.com/spacetelescope/drizzlepac/pull/946)
 [Drizzlepac PR #&#x2060;945](https://github.com/spacetelescope/drizzlepac/pull/945)

The issues found were:  

> =========================
>  ibl737/HAP_ibl737.out
>  id9621/HAP_id9621.out
>  ide601/HAP_ide601.out
>  j92ql3/HAP_j92ql3.out
>  j9oi05/HAP_j9oi05.out
>  jb1f85/HAP_jb1f85.out
>  jbeuhz/HAP_jbeuhz.out
>  =========================
>  DRZ too large for PSF FFT
>    ==> ISSUE: DRZ image too large to perform FFT on as a whole.  Need to work on segments at a time... 
>  ==> FIXED by PR #&#x2060;950
> 
> In [17]: import tracemalloc
>  In [18]: tracemalloc.start()
>  In [19]: D_drz = np.fft.fft2(drz) # Original method
>  In [20]: current, peak = tracemalloc.get_traced_memory()
>  In [21]: tracemalloc.stop()
>  In [22]: current, peakOut[22]: (91239874, 182118100)
>  In [32]: tracemalloc.stop()
> 
> In [33]: tracemalloc.start()
>  In [34]: S_drz = window_fft(drz) # New block-based method
>  In [35]: current_S, peak_S = tracemalloc.get_traced_memory()
>  In [36]: tracemalloc.stop()
>  In [37]: current_S, peak_SOut[37]: (67635394, 167879606)
>    
> 
> =====================
>  ia1s70/HAP_ia1s70.out
>  iby07w/HAP_iby07w.out
>  ic40b1/HAP_ic40b1.out
>  ic5t01/HAP_ic5t01.out
>  icol05/HAP_icol05.out
>  icu504/HAP_icu504.out
>  id1x09/HAP_id1x09.out
>  idnm03/HAP_idnm03.out
>  idnm0u/HAP_idnm0u.out
>  idx205/HAP_idx205.out
>  j96r01/HAP_j96r01.out
>  j9fh49/HAP_j9fh49.out
>  j9i408/HAP_j9i408.out
>  j9l023/HAP_j9l023.out
>  j9ns01/HAP_j9ns01.out
>  jds323/HAP_jds323.out
>  =====================
>  Traceback (most recent call last):
>    File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/hapsequencer.py", line 610, in run_hap_processing
>      catalog_switches=cat_switches)
>    File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/hapsequencer.py", line 160, in create_catalog_products
>      total_product_catalogs.identify(mask=total_product_obj.mask)
>    File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/catalog_utils.py", line 564, in identify
>      self.catalogs[catalog].identify_sources(**pars)
>    File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/catalog_utils.py", line 917, in identify_sources
>      if len(user_peaks) == 0:TypeError: object of type 'NoneType' has no len()
> 
>   ==> RESOLVED: updated logic to revert to DAOFind allowed point-source catalog to be generated without error.
>    ==> SECONDARY Problem: Tiny-Tim PSFS have artifacts near the core causing source identification to fail, also did not fail over to a successful DAOFind use. [
>  ==> Fixed in PR #&#x2060;950
> 
> =====================
>  j9pr15/HAP_j9pr15.out
>  =====================
>  2021050170805 INFO src=drizzlepac.haputils.product- Copying j9pr15q4q_flt.fits to SVM input:     hst_10878_15_acs_hrc_pr200l_j9pr15q4_flt.fits
>  2021050170805 INFO src=drizzlepac.haputils.product- Grism Exposure object hst_10878_15_acs_hrc_pr200l_j9pr15q4_flt.fits created.
> 
> Traceback (most recent call last):  File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/hapsequencer.py", line 549, in run_hap_processing
>      manifest_name = total_obj_list[0].manifest_nameIndexError: list index out of range
> 
> ==> Fixed in PR #&#x2060;946
> 
> =====================
>  je4m30/HAP_je4m30.out
>  =====================
>  2021050105220 INFO src=drizzlepac.haputils.catalog_utils- UserStarFinder(fwhm=3.2594061776508507, threshold=5*0.007377948839587127) 
>  Looking for Library PSF /home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/pars/psfs/acs/wfc/acs_wfc.fits
>  2021050105221 ERROR src=drizzlepac.haputils.deconvolve_utils- No PSF found for keywords ['INSTRUME', 'DETECTOR']
>      with values of ['acs', 'wfc']
> 
> Traceback (most recent call last):  File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/hapsequencer.py", line 610, in run_hap_processing
>      catalog_switches=cat_switches)  File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/hapsequencer.py", line 160, in create_catalog_products
>      total_product_catalogs.identify(mask=total_product_obj.mask)
>    File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/catalog_utils.py", line 564, in identify
>      self.catalogs[catalog].identify_sources(**pars)
>    File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/catalog_utils.py", line 916, in identify_sources
>      mask=self.image.footprint_mask)
>    File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/deconvolve_utils.py", line 648, in find_point_sources
>      psfname = find_psf(drzname)  File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/deconvolve_utils.py", line 239, in find_psf
>      raise ValueErrorValueError2021050105222 INFO src=drizzlepac.hapsequencer- Processing completed at 2021-02-19 10:52:22.032595
>    ==> RESOLVED:  Logic for identifying correct PSFs was corrected to avoid this problem altogether. [PR #&#x2060;950|#&#x2060;950]

**Comment by stsci-hack** [comment]
Resolved by PRs mentioned in comments.
