### ISSUE TITLE
Update astrometry logic to use latest GAIA catalog as priority

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#932]
_Issue [HLA-487](https://jira.stsci.edu/browse/HLA-487) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The astrometry processing code needs to be updated to use the lastest GAIA release, currently now GAIAeDR3 (early-release DR3).  

In addition, the logic should be revisited to change how alignment should revert to other options should be reviewed and revised to be more in line with AWG recommendations.  Specifically, GAIAeDR3 should be used, then only if no successful fit can be made at all should GAIADr1 be used.  Later, as the Pan-STARRs catalog becomes available, this logic will need to be updated further to account for cases where the Pan-STARRs catalog can work when GAIA will not.  

This ticket, though, would only be responsible for identifying the level of work needed to implement such changes to the logic while updating to rely on GAIAeDR3 as the primary catalog over GAIADR2.   This work would primarily affect the standard pipeline astrometry processing (runastrodriz), but should also update the SVM alignment code as well.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-487?focusedCommentId=509840#comment-509840):_

A discussion with the AWG on 17-Feb provided guidance on how this logic should work.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-487?focusedCommentId=510535#comment-510535):_

The logic proposed by the AWG:
 * try to align the exposure (single or mosaic) to the 'hybrid' GAIA-consistent catalog (GAIA+Pan-STARRs+...)
 ** New catalog would use label something like 'GAIAPS'
 ** If successful, use this as the WCS
 ** sources should be weighted by 1/error (1/sigma), with the median being used as the offset instead of the mean
 * If fit is not successful, generate a reference catalog using a secondary, non-GAIA-aligned catalog like 2MASS
 * A successful fit with this catalog would then serve as the initial guess for fitting to GAIA with 1-4 sources (offset only?)

 ** If the fit to the GAIAPS catalog is unsuccessful, the 2MASS WCS would be used with a label based on the catalog name 

This logic will replace the current logic used in the standard pipeline which iterates over multiple GAIA catalogs in order to get a GAIA-based solution for more fields and provide a more accurate starting point for creating the SVM and MVM mosaics.  This algorithm could also be used for the SVM and MVM catalogs with failures to align reverting to standard pipeline WCS as done now.  Most likely, though, in >90% of the fields(?),  the SVM and especially the MVM mosaics should be able to fit successfully to the GAIAPS catalog in the first step.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-487?focusedCommentId=517450#comment-517450):_

Three tickets have been defined to finish this work:
* HLA-509 : implement HLA-based logic for determining fit success
* HLA-510 : create interface for using weights with tweakwcs
* HLA-511 : integrate new functions into final logic

**Comment by stsci-hack** [comment]
Resolved with #1001 and #1002.
