### ISSUE TITLE
Remove items which should not be in output manifest

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#939]
_Issue [HLA-491](https://jira.stsci.edu/browse/HLA-491) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

There are items which should not be present in the SVM output manifest: None and the metawcs.  These items should be removed from the manifest.  Also, if the item is an actual disk file, it should be deleted from disk once processing is completed.

**Comment by stsci-hack** [comment]
Resolved with #941.
