### ISSUE TITLE
SVM: Reconcile flag limit to be used for WFC3 IR

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#948]
_Issue [HLA-492](https://jira.stsci.edu/browse/HLA-492) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Double-check the "flag_trim_value" for WFC3 IR.  ACS (WFC,  HRC, and SBC) and WFC3 UVIS all us the value of 5.  WFC3 IR uses a value of 65368.  Check this again HLA and/or Rick White.  If HLA is not a viable source, just change the value to 5 in the parameter file _*and*_ the documentation.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-492?focusedCommentId=512017#comment-512017):_

This fix was done as part of HLA-305.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-492?focusedCommentId=512018#comment-512018):_

The fix was done as part of HLA-305.

**Comment by stsci-hack** [comment]
Resolved by #947, #953, #935, #936.  Documented in #748.
