### ISSUE TITLE
SVM: Delete temporary files created during processing

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#949]
_Issue [HLA-493](https://jira.stsci.edu/browse/HLA-493) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Ensure the hst*total*raw-point-cat.ecsv, hst*total*region*.fits, and hst*total*starfind_sources*.ecsv are deleted from disk once the processing is completed.  Also, hst*metawcs_all_ref_cat.ecsv, *psf_dr?.fits, *psf_fl?.fits, and *pickle. The manifest file is fine.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-493?focusedCommentId=514912#comment-514912):_

Surrounded the creation of hst*total*raw-point-cat.ecsv, hst*total*region*.fits, and hst*total*starfind_sources*.ecsv with "if self.diagnostic_mode".  These files are only used for diagnostic purposes and should not be created during standard processing.  The remaining files are already cleaned up by a code check-in done before this ticket was addressed.

Tested with acs_cat_24_input.out and acs_8eh_11_input.out. 

Generated Git PR#&#x2060;958

**Comment by stsci-hack** [comment]
Resolved with #958.
