### ISSUE TITLE
SVM: Evaluate 1k dataset test results for Grism/Prism/Ramp Issues

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#952]
_Issue [HLA-494](https://jira.stsci.edu/browse/HLA-494) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Address bugs detected during the 1K dataset test pertaining to the new functionality of handling the Grism/Prism and Ramp exposures.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-494?focusedCommentId=512462#comment-512462):_

Working this issue for the actual unhandled situation found in testing (the two Grism images were the only data in the visit), as well as follow-on details and bugs.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-494?focusedCommentId=512551#comment-512551):_

A large part of this ticket has been resolved with Git PR#&#x2060;946.  However, there are additional items which need to be addressed:
 * Save archived WCS solutions as headerlets and not FITS keywords
 * Only save the WCS if it is not already present in the file
 * Be careful when replacing the active WCS, it may be necessary to save all the alternate WCS solutions also if the underlying IDCTAB, for example, is different in the updated active solution.
 * There should always be a trailer file for every Grism product.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-494?focusedCommentId=513943#comment-513943):_

PR#&#x2060;956 is out for review as the items in the previous comment, as well as the same items pertaining to Ramp images, have been addressed.

**Comment by stsci-hack** [comment]
Solved with #956 and #946.
