### ISSUE TITLE
Some images from archive have misaligned WCS when it was aligned to GAIA

### ISSUE THREAD

**Issue by mcara** [spacetelescope/drizzlepac#955]
In help desk issue INC0165704 user has trouble drizzling images that came out of archive. The reason for massive clipping is misalignment between input images. Upon inspection, the WCS of file `iabj01a4q_flc.fits` as an example, contained the following WCSes:
```
'O': 'OPUS' 
'A': 'IDC_2731450pi' 
'B': 'IDC_2731450pi-HSC30' 
' ': 'IDC_2731450pi-FIT_IMG_GAIADR1' 
```
Resetting WCS made `'IDC_2731450pi'` to be the primary and solved the issue. However, why is the relative alignment of images destroyed after images have been aligned to GAIA?

Is this an issue in how "HAP" sets-up alignment for `tweakwcs` or is this an issue with `tweakwcs`?

CC: @stsci-hack

**Comment by stscijgbot-hstdp** [comment]
_This issue is tracked on JIRA as [HLA-495](https://jira.stsci.edu/browse/HLA-495)._

**Comment by mcara** [comment]
BTW, this data set contains plenty of good stars that should produce very good _relative_ alignment. Let's say, for whatever reason, alignment to GAIA is poor. I would still expect relative alignment to be good. So, either there is an issue in the quality of initial relative alignment, incorrect call (or set up of the problem) to `tweakwcs`, or `tweakreg` breaks relative alignment, I think...

**Comment by stsci-hack** [comment]
This data from this visit does not contain any associations defined by the pipeline.  As a result, the only time relative alignment will ever be defined or maintained would be during SVM processing.  The standard pipeline processed FLT/FLC images (such as ``iabj01a4q_flc.fits``), as a result, only get aligned individually so relative alignment does not get checked let alone retained with regard to any other data in this visit.  That said, alignment to GAIAeDR3 now works (with v3.5.0) for ``iabj01a4q_flc.fits`` allowing it to be well aligned in a relative sense to the rest of the F606W images.  The same goes for ``iabj01zdq_flc.fits`` which came from the archive with an a priori HSC30 WCS yet aligns to GAIAeDR3 using v3.5.0.  Reprocessing of this data in the pipeline will eventually restore the relative alignment of the data in the archive, but in the meantime, end-users can install and use the latest version v3.5.0 or greater to re-process and restore the relative alignment of all exposures in this visit.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-495?focusedCommentId=605066#comment-605066):_

This data from this visit does not contain any associations defined by the pipeline.  As a result, the only time relative alignment will ever be defined or maintained would be during SVM processing.  The standard pipeline processed FLT/FLC images (such as ``iabj01a4q_flc.fits``), as a result, only get aligned individually so relative alignment does not get checked let alone retained with regard to any other data in this visit.  That said, alignment to GAIAeDR3 now works (with v3.5.0) for ``iabj01a4q_flc.fits`` allowing it to be well aligned in a relative sense to the rest of the F606W images.  The same goes for ``iabj01zdq_flc.fits`` which came from the archive with an a priori HSC30 WCS yet aligns to GAIAeDR3 using v3.5.0.  Reprocessing of this data in the pipeline will eventually restore the relative alignment of the data in the archive, but in the meantime, end-users can install and use the latest version v3.5.0 or greater to re-process and restore the relative alignment of all exposures in this visit.
