### ISSUE TITLE
MVM: Replace tweakwcs fitting with AWG provided fitting algorithm

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#959]
_Issue [HLA-497](https://jira.stsci.edu/browse/HLA-497) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The tweakwcs fitting algorithm currently only fits for offsets, rotations and scales between the images as a whole.  However, data taken over long time periods will also need to take into account proper motions of each cross-matched source as well in the fitting.

A new algorithm will need to be developed that can replace the tweakwcs fitting code to also fit for proper motions based on the algorithm provided by the AWG.  This will then be used to align images for the MVM products. 

This effort will need to be broken down into several related tickets to cover all the work necessary for this implementation.  Those tickets will need to include (but not be limited to):
 * designing the API to replace the current tweakwcs fitting code and how to call it from the MVM code
 ** Initial implementation can simply replace or augment the fitting functions in 'tweakwcs.linearfit' [HLA-515]
 * developing the code needed to set up the new inputs for the fitting to include proper motions and their errors
 ** Current astrometric catalogs already provide values for the proper motions along with estimates of the errors.  The reference catalogs created for alignment will need to be revised to include this information for use by the fitting function. [HLA-516]
 * implementing the actual fitting code using scipy.optimize.curve_fit as the stand-in for the IDL curvefit used in the AWG implementation we were provided 
 ** Specific functions from the IDL code will need to be identified for translation and mapped to the APIs designed under HLA-515. [HLA-517]
 ** The IDL functions will then need to be translated to Python. [HLA-518]
 ** The new fitting functions will need to be tested (basic unit testing) to insure that it works and produces the expected results. [HLA-519]
 * integrating the new algorithm into the MVM alignment code to generate the output products from the fit, including the catalog containing the fit values for each source's position and proper motion and errors of the fit. [HLA-520] 
 * testing the new fitting algorithm [HLA-521]

 For this sprint, the goal is to define each of the components listed above in more detail and to file separate tickets for later sprints.

**Comment by stsci-hack** [comment]
This new algorithm ended up not being implemented in favor of simply relying on using the alignment of the SVM products to account for the proper motions.
