### ISSUE TITLE
SVM: Address issues with Grism/Prism processing

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#961]
_Issue [HLA-499](https://jira.stsci.edu/browse/HLA-499) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Handle duplicate WCS solutions (wcsname and hdrname are the same) when processing Grism/Prism data.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-499?focusedCommentId=515537#comment-515537):_

This ticket is meant to handle items 15 and 18 in the parent ticket which are both characterized with an error involving HDRNAME.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-499?focusedCommentId=516085#comment-516085):_

Out for code review PR#&#x2060;963. 

(1) Addressed restoration of WCS from headerlet when there are duplicate
 headerlets (as indicated by same HDRNAME and WCSNAME) for some Grism/Prism
 data. One of the duplicate headerlets is deleted. (2) Trap exception
 when cannot restore a WCS from headerlet as the HDRNAME keyword cannot
 be found. The exception is reported, and a "warning" message is used
 that the WCS cannot be restored for the Grism/Prism data. However,
 processing can and should continue for the remainder of the Grism/Prism
 and direct images.

**Comment by stsci-hack** [comment]
Closed by #963.
