### ISSUE TITLE
Ensure PHOTFLAM keyword can be found

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#967]
_Issue [HLA-502](https://jira.stsci.edu/browse/HLA-502) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Depending upon the instrument the PHOTFLAM keyword may be in the Primary or in an extension of a multi-extension FITS file.  Write a little utility to aid in finding the keyword and update so this particular bug is addressed.  Other parts of the code can be updated at a later time.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-502?focusedCommentId=516461#comment-516461):_

This problem has been addressed, albeit with a stopgap solution, in PR#&#x2060;969 which is out for review.

**Comment by stsci-hack** [comment]
Closed by #969.
