### ISSUE TITLE
SVM: Catalogs missing for j8ep07

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#970]
_Issue [HLA-504](https://jira.stsci.edu/browse/HLA-504) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Only some of the filter level Point catalogs were written out with no actual content for the SBC portion of this visit (no sources).

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-504?focusedCommentId=516638#comment-516638):_

This visit, both SBC and HRC images, now successfully process (exit code 0) using the Drizzlepac software of 17 March 2021 (commit 6759745).  There is trouble finding enough matches to align the SBC images, but the software recovers and is able to generate catalogs with viable content. For HRC, the Point catalog fails the CR threshold so neither the Point nor the Segment catalog is produced as an output product.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-504?focusedCommentId=516839#comment-516839):_

Merging in all the latest changes, including Git PR#&#x2060;972, resolved the resolvable issues with this ticket.  The HRC is able to perform the alignment while the SBC must fall back to the default.  This means the SBC total detection image shows sources offset from one another akin to "pearls on a string", but the code was designed to allow for this to happen.  Both detectors generate catalogs.  This ticket was essentially a short investigation, and it is done.

There is no code associated with this ticket.

**Comment by stsci-hack** [comment]
Closed with #972
