### ISSUE TITLE
SVM: Clean up the logic for rejection of catalogs and diagnostic mode

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#973]
_Issue [HLA-505](https://jira.stsci.edu/browse/HLA-505) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

If diagnostic mode is True, the .reg version of the catalogs should **always** be written for debugging/diagnostic purposes.  The "reject catalogs" controls whether or not the .ecsv files are written.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-505?focusedCommentId=516894#comment-516894):_

Dataset j8ep07 was used for testing.  The "reject_catalogs" setting was forced in order to test all four states of this ticket.

Reject_Catalogs   Diagnostic_mode

True                       True

False                       False

True                        False

False                      True

The fix is out for review Git PR#&#x2060;974.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-505?focusedCommentId=516904#comment-516904):_

This ticket was implemented, reviewed, approved, and merged.  Git PR#&#x2060;974.

**Comment by stsci-hack** [comment]
Closed with #974.
