### ISSUE TITLE
SVM: Clean up details in output catalogs

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#977]
_Issue [HLA-507](https://jira.stsci.edu/browse/HLA-507) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

Rick has taken a careful look at the output catalogs and compiled a list of items to correct.  Here is the list as provided by Rick.
(1) Pixel coordinate column names
point: names are X-Center, Y-Center
segment: names are X-Centroid, Y-Centroid
 
Should these be made the same?  I'm not certain, but if there is not a reason why they need to be different then they should be the same.
 
(2) Descriptions
segment: most columns have descriptions
point: no descriptions
 
The point catalog should have descriptions for the columns, which can probably be the same as the segment catalog descriptions.
 
(3) Flag column description
segment, point: no description
 
A description should be added for this column in both catalogs.  The Flags column is the only one in the segment catalog that is missing a description.
 
(4) Formats
 
Here's a table for point and segment column formats in the total catalogs:
 
Column   point segment recommendation
ID        .8g      6d    7d (see note 1)
X-Center  .8g   10.3f   10.3f
Y-Center  .8g   10.3f   10.3f
RA        .8g   13.7f   13.7f
DEC       .8g   13.7f   13.7f
MagAP2_* 6.3f    8.2f    7.3f
CI_*     7.3f    7.3f    7.3f
Flags_*    3d      5d     5d
 
Notes:
1. Some fields will have >100k sources, so the ID value can have 7 digits.
 
(5) Units
segment total: unit=pix for X,Y and unit=deg for RA,DEC; no other units
point total: no unit for X,Y or RA,DEC; unit=ABMAG for magnitudes, CI; unit=Unitless for ID, Flags
 
segment f160w: unit=pix for X,Y; unit=dec for RA,DEC; does have units for Mag, Flux; no units for CI
point f160w: unit=Pixels for X,Y; unit=Sky Coords for RA,Dec
 
I'm not sure of the value for Unitless columns, but it seems like these should be consistent for the X, Y, RA, DEC, magnitude, flux and CI columns.  They also should be consistent between the total and filter catalogs (for some reason the units did not get propagated for the Mag and CI columns for the segment catalog?)
 
(6) Null values
 
In the total catalogs at least, the null values are weird.
 
point: sometimes nulls are nan, and sometimes they are "" (for the same column)
segment: null values are almost always "", but there is a single row with a mix of "" and nan

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-507?focusedCommentId=517968#comment-517968):_

HLA-468 can be used to investigate the NaNs in the output catalogs.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-507?focusedCommentId=518509#comment-518509):_

Updates made to the Point and Segment catalogs to make them more consistent in terms of column units, descriptions, and formats. The X and Y column names (X-Center vs X-Centroid) were explicitly NOT changed at this time as these name propagate to other modules. Also, the issue with nulls/nans/"" was not addressed.

**Comment by stsci-hack** [comment]
Solved with #1162, #1316, #1178, and #1155.
