### ISSUE TITLE
SVM: Master ticket itemizing the bugs found in 1K test run done 19 March 2021

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#978]
_Issue [HLA-508](https://jira.stsci.edu/browse/HLA-508) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

1) /home/mburger/singlevisits/results_2021-03-19/ia0m04/HAP_ia0m04.out:KeyError: 'RA'
 ==> Failed in quality analysis - GAIA characterization.
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/svm_quality_analysis.py", line 149, in characterize_gaia_distribution
 x, y = outwcs.all_world2pix(gaia_table['RA'], gaia_table['DEC'], 1)

Michele will investigate. (HLA-512, Git PR#&#x2060;983)

 

2) /home/mburger/singlevisits/results_2021-03-19/iabk05/HAP_iabk05.out: raise ValueError
 ==> Failed in align_to_gaia for FilteredProduct - use previous best, but
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/align_utils.py", line 378, in apply_fit
 raise ValueError
 Quality analysis = characterize gaia distribution

Using the "previous best" solution is fine to do, and the failure in Quality analysis is fixed by HLA-512.

 

3) /home/mburger/singlevisits/results_2021-03-19/ibcd61/HAP_ibcd61.out:RuntimeError: Number of output coordinates exceeded allocation (2)
 ==> Failed in align_to_gaia for FilteredProduct - use previous best, but
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/stsci/stimage/*_init_*.py", line 254, in xyxymatch
 nreject)
 Quality analysis = characterize gaia distribution

Michele will investigate. (HLA-513)

The failure in Quality analysis is fixed by HLA-512.

 

 

4) /home/mburger/singlevisits/results_2021-03-19/ibeveo/HAP_ibeveo.out:IndexError: index 0 is out of bounds for axis 0 with size 0
 ==> Trouble updating products for CAOM.
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/cell_utils.py", line 428, in find_corners
 corner_dist = distance.cdist(edge_pixels, [xy_corners[radial_order[0]]])
 Quality analysis = characterize gaia distribution
 >>>> Warren submitted HLA-514 and [PR #&#x2060;985](https://github.com/spacetelescope/drizzlepac/pull/985) to correct this problem for this and other similar datasets.

 

5) /home/mburger/singlevisits/results_2021-03-19/ibmr02/HAP_ibmr02.out:numpy.core._exceptions._ArrayMemoryError: Unable to allocate 243. MiB for an array with shape (5313, 6004) and data type float64
 ==> Failed in align_to_gaia for FilteredProduct - use previous best, but
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/align_utils.py", line 378, in apply_fit
 raise ValueError
 Trouble updating products for CAOM.
 Axx = ndi.gaussian_filter(imx * imx, sigma, mode=mode, cval=cval)

Using the "previous best" solution is fine to do.

 

6) /home/mburger/singlevisits/results_2021-03-19/ic27sk/HAP_ic27sk.out:ValueError: Too few input images (or groups of images) with non-empty catalogs.
 ==> Failed in align_to_gaia for FilteredProduct - use previous best, but
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/align_utils.py", line 378, in apply_fit
 raise ValueError
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/tweakwcs/imalign.py", line 601, in align_wcs
 raise ValueError("Too few input images (or groups of images) with "
 One GAIA source found.
 Failure in quality analysis
 x, y = outwcs.all_world2pix(gaia_table['RA'], gaia_table['DEC'], 1)

Using the "previous best" solution is fine to do, and the failure in Quality analysis is fixed by HLA-512.

 

7) /home/mburger/singlevisits/results_2021-03-19/iccz72/HAP_iccz72.out:TypeError: 'NoneType' object is not subscriptable
 ==> Failed in align_to_gaia for FilteredProduct - use previous best, but
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/product.py", line 363, in align_to_gaia
 raise ValueError
 Quality analysis = find_gaia_sources: ref_table = ref_table[ref_table.mask['pmra'](https://jira.stsci.edu/secure/ViewProfile.jspa?name=ref_table.mask%5B%27pmra%27)] TypeError: 'NoneType' object is not subscriptable
 Quality analysis = characterize gaia distribution

Using the "previous best" solution is fine to do, and the failure in Quality analysis is fixed by HLA-512.

 

8) /home/mburger/singlevisits/results_2021-03-19/idw101/HAP_idw101.out:TypeError: object of type 'NoneType' has no len()
 ==> Failed in align_to_gaia for FilteredProduct - use previous best, but
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/product.py", line 363, in align_to_gaia
 raise ValueError
 Quality analysis -
 File "/home/mburger/anaconda3/envs/caldp/lib/python3.7/site-packages/drizzlepac/haputils/starmatch_hist.py", line 72, in run
 minimum_match=minimum_match, xref=xref, yref=yref,postarg_ref=postarg[coo_ref], postarg_img=postarg[coo_img])
 ValueError: not enough values to unpack (expected 3, got 0)
 Quality analysis = characterize gaia distribution

Using the "previous best" solution is fine to do, and the failure in Quality analysis is fixed by HLA-512.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack) on [JIRA](https://jira.stsci.edu/browse/HLA-508?focusedCommentId=517230#comment-517230):_

Just for clarification, none of the tests actually ended with return value of 1 (error).  This indicates that the code cleanly handled (hid?) any Exception that was triggered when processing the dataset.

**Comment by stsci-hack** [comment]
Resolved with #983 and #985.
