### ISSUE TITLE
MVM: Integrate alignment functions

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#981]
_Issue [HLA-511](https://jira.stsci.edu/browse/HLA-511) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

Work on HLA-509 and HLA-510 will result in new functions needed to implement the updated alignment algorithm described in HLA-487.  This ticket will focus on defining the logic for calling those interfaces and integrating them into a working algorithm that fully implements the AWG prescribed alignment logic.  Part of this effort will be to contact Brian McLean to confirm what catalogs should be used as the primary and secondary catalogs in this new logic.  

This logic will replace (not merely augment) the logic already in place in the `align_to_gaia` method of the FilterProduct class.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-511?focusedCommentId=519197#comment-519197):_

Sent Brian an email requesting the catalog names to support the Astrometric Working Group algorithm.

**Comment by stsci-hack** [comment]
Resolved with #1002.
