### ISSUE TITLE
MVM: Define API for new fitting function in tweakwcs

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#987]
_Issue [HLA-515](https://jira.stsci.edu/browse/HLA-515) was created on JIRA by [Warren Hack](https://jira.stsci.edu/secure/ViewProfile.jspa?name=hack):_

The fitting function for the MVM alignment will involve fitting proper motions for each source as well as overall offset and other global linear terms.  An API that closely follows the conventions used by the 'fit_<fitgeom>' functions in 'tweakwcs.linearfit' should be defined for the new function.  This API can be defined and tested separately from the implementation of the actual fitting function itself to make sure that we know how to replace (or supplement) the fitting functions already used by tweakwcs.  

The output should be defined to replicate the output from the current tweakwcs functions, but with the additional results from the proper motions fit for each source and their errors.

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michael Dulude](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dulude) on [JIRA](https://jira.stsci.edu/browse/HLA-515?focusedCommentId=530637#comment-530637):_

Current definition of latest version of tweakwcs.linearfit.iter_linear_fit:
 iter_linear_fit(xy, uv, wxy=None, wuv=None, fitgeom='general', center=None, nclip=3, sigma=(3.0, 'rmse'), clip_accum=False)
 Where:
 xy and uv are (N, 2) arrays of X, Y coords to match and fit.

To add proper motion fitting functionality, additional information is required. This includes
 * instead of just xy and uv, the code should accept multiple (more than just 2) catalogs and fit everything to a reference catalog
 * corresponding image names and a reference image name will probably be needed to supply additional information, such as WCS info, date-obs and time-obs, etc.

**Comment by stsci-hack** [comment]
Fitting for proper motions will no longer be done, since we will rely on the single-visit alignment to provide the best available alignment based on the proper motions from the astrometric catalogs.
