### ISSUE TITLE
SVM: Catalog cleanup - investigate nan/null/"" output 

### ISSUE THREAD

**Issue by stscijgbot-hstdp** [spacetelescope/drizzlepac#998]
_Issue [HLA-524](https://jira.stsci.edu/browse/HLA-524) was created on JIRA by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena):_

See Jira HLA-513 for background.

It is possible for the catalog output to contain nan/null/"" output, predominantly in the Point catalog, but it is possible in the Segment catalog also.  The difference between the Point and Segment catalogs in this regard is the Segment catalog is filtered to eliminate what it considers "bad" rows.
 # The reason for the nan values should be investigated.
 # The filtering should be reconsidered (Do it at all?  Do it for both catalogs? Do it differently?)

 

Comment from deprecated ticket HLA-468: Both the Point and Segment catalogs contain NaN values where it seems the source was detected, but the measuring algorithms were unable to make viable measurements.  This issue should be investigated and rectified if possible.
 
####

**Comment by stscijgbot-hstdp** [comment]
_Comment by [Michele De La Pena](https://jira.stsci.edu/secure/ViewProfile.jspa?name=mdelapena) on [JIRA](https://jira.stsci.edu/browse/HLA-524?focusedCommentId=553245#comment-553245):_

It seems that Rick/Steve can work with nan and/or "", but during HAP catalog generation, we might be able to make things a bit easier for them by addressing the nan/"" issues.  We just have to settle on what is actually wanted as Rick and Steve do not seem to agree.

*Rick:*  I personally prefer something like nan over a special value.  I'm not sure what the difference is between the nan columns and the "" null columns, but in any case we will be prepared to handle these missing values.

*Steve:* We would need to convert any nan value into null or 0 before inserting into the database. So it would be easier to assign it some such value in the file.

**Comment by stsci-hack** [comment]
Closed by #1162
